### ISSUE TITLE
Misc is deprecated but Label has a bug

### ISSUE THREAD

**Issue by geovex** [gtk-rs/gtk#1002]
Without `v3_16` feature text in Label can be aligned only through `gtk_misc_set_alignment` ([this bug](https://bugzilla.gnome.org/show_bug.cgi?id=733981)). But `gtk::Misc` is "deprecated". So what are my options without v3_16 and without wrapping label in another container?

**Comment by sdroege** [comment]
That seems like a bug in GTK: they deprecated it in 3.14 without providing a replacement until 3.16. So your only choices seem to be
* Use `v3_16`
* Use `label.set_property("xalign", &123f32)`
