### ISSUE TITLE
How to validate input of entry

### ISSUE THREAD

**Issue by DBLouis** [gtk-rs/gtk#1006]
How would you implement input validation on an entry widget?
I found an this [example](https://www.geany.org/manual/gtk/gtk-faq/x843.html) in C and try to do the same in Rust.
I am struggling with [signal_handler_block](https://gtk-rs.org/docs/glib/signal/fn.signal_handler_block.html) and [signal_handler_unblock](https://gtk-rs.org/docs/glib/signal/fn.signal_handler_unblock.html) because I don't know how to get the SignalHandlerId.

**Comment by sdroege** [comment]
The `connect_blablabla()` functions return the `SignalHandlerId` that you can use for this.

**Comment by DBLouis** [comment]
Ok but this kind of a vicious circle because I need the SignalHandlerId in the closure that I connect.

**Comment by sdroege** [comment]
Those things are annoying. You could store it in a `Rc<RefCell<Option<SignalHandlerId>>>` outside the closure (or in some other way in your application state), and pass a reference to that into the signal handler closure to get access to it.

**Comment by DBLouis** [comment]
I guess there is no other way. Is `g_signal_handlers_block_by_func` could be made available eventually?

**Comment by sdroege** [comment]
No as you don't have access to the function parameter you'd pass there. It's a private function specific to the closure you pass in, your closure (but boxed) becomes the user data.

**Comment by DBLouis** [comment]
Ok thank you
