### ISSUE TITLE
WidgetExt::hide_on_delete useless in current form

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk#1008]
```rust
fn hide_on_delete(&self) -> bool
```

should be connectable to

```rust
fn connect_delete_event<F: Fn(&Self, &Event) -> Inhibit + 'static>(
    &self,
    f: F
) -> SignalHandlerId
```

which doesn't work out that well.

- https://gtk-rs.org/docs/gtk/trait.WidgetExt.html#tymethod.hide_on_delete
- https://gtk-rs.org/docs/gtk/trait.WidgetExt.html#tymethod.connect_delete_event

**Comment by sdroege** [comment]
Yes it should return an `Inhibit`, needs a manual implementation for that. Do you want to create a PR?
As workaround for now you can do

```rust
window.connect_delete_event(|window| Inhibit(window.hide_on_delete(window)))
```

**Comment by sophie-h** [comment]
Actually, `|window, _|` :)

I will have a look at the manual implementations tomorrow. Doesn't sound that complicated

**Comment by sdroege** [comment]
Ok :) Let me know if you have questions
