### ISSUE TITLE
GTK application problem.

### ISSUE THREAD

**Issue by kevekop** [gtk-rs/gtk#1012]
Hi, I recently made an application with GTK/Python on my raspberry pi. Everything works fine, the application does what it needs to do. When I do "python3 application.py" on my raspberry pi, no problems, works just fine. When I try to do it over SSH, it gives me this error: 

" Unable to init server: Could not connect: Connection refused

(Main.py:2169): Gtk-CRITICAL **: 14:49:24.239: _gtk_style_provider_private_get_s                                     ettings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(Main.py:2169): Gtk-CRITICAL **: 14:49:24.239: _gtk_style_provider_private_get_s                                     ettings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(Main.py:2169): Gtk-CRITICAL **: 14:49:24.239: _gtk_style_provider_private_get_s                                     ettings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed"

Can someone help me with this one please?
Thank you guys

**Comment by GuillaumeGomez** [comment]
Not the good repository/organization.

**Comment by kevekop** [comment]
> repository/organization

I have no clue what you mean.

what do i need to do ?

**Comment by sdroege** [comment]
This repository is for the Rust bindings to GTK, completely unrelated to Python. But your problem also seems unrelated to Python, just a general GTK problem.

**Comment by kevekop** [comment]
> This repository is for the Rust bindings to GTK, completely unrelated to Python. But your problem also seems unrelated to Python, just a general GTK problem.

Ok, thanks for your reply. where can I post this issue without looking stupid? i'm sorry that i puted in the wrong repositorry, i'm pretty new in this.
Thank you very much

**Comment by sdroege** [comment]
https://discourse.gnome.org might be a good starting point. This doesn't look much like an actual bug in GTK but like a usage problem.
