### ISSUE TITLE
EventKey not being emitted on Windows when Backspace or Arrow Keys Are Pressed

### ISSUE THREAD

**Issue by john01dav** [gtk-rs/gtk#1025]
I'm trying to implement a cross-platform terminal, based on `gtk::TextView`,and I'm basically done but there's a problem. On Windows, `connect_key_press_event` does not emit an event when backspace or enter is pressed, which is highly problematic as backspace is an essential part of a working terminal. Backspace is emitted correctly on Linux.

Additionally, arrow keys do not emit the event on Linux or Windows. I'm not sure if this is an upstream GTK bug, or a GTK-rs bug, but it seems reasonable to start here as I'm using GTK-rs.

**Comment by sdroege** [comment]
The best place to ask such generic GTK questions would be https://discourse.gnome.org

The issue tracker here is meant for bugs in the bindings or feature requests for them.
