### ISSUE TITLE
argument to set_title not consistent

### ISSUE THREAD

**Issue by russel** [gtk-rs/gtk#1034]
For `Window`:
```
fn set_title(&self, title: &str)
```
for `NativeDialog`:
```
fn set_title(&self, title: &str)
```
but for `HeaderBar`:
```
fn set_title(&self, title: Option<&str>)
```
is the `Option` needed in this last case?

**Comment by sdroege** [comment]
Yes, see the docs: https://developer.gnome.org/gtk3/stable/GtkHeaderBar.html#gtk-header-bar-set-title . It allows `NULL`.
