### ISSUE TITLE
Subclassing: `gtk_container_forall ()` is missing

### ISSUE THREAD

**Issue by haecker-felix** [gtk-rs/gtk#1036]
I'm currently trying to port this widget from Vala to Rust:

https://gitlab.gnome.org/GNOME/gnome-games/-/blob/master/src/ui/titlebar-box.vala#L254

The current blocker is the missing `gtk_container_forall` func:
https://developer.gnome.org/gtk3/stable/GtkContainer.html#gtk-container-forall

As I understand this func is really necessary to create own custom widgets. 

Related PR: https://github.com/gtk-rs/gtk/pull/1035

**Comment by sdroege** [comment]
Done in 9e50ccaebee21523afe23ab1ef83842af4ae5a39

**Comment by garfreak** [comment]
@sdroege Sorry if this is the wrong location to ask (which it likely is, but I have no clue where to ask...). When can a version which contains the `gtk_container_forall` be expected on crates.io? I would really need this patch and currently use the git repo as dependency, but that does not feel legit to include into my project's main branch as it is no stable version.

**Comment by sdroege** [comment]
In a couple of weeks hopefully. There are a few more things waiting to be finished first.
