### ISSUE TITLE
LabelBuilder::wrap_mode could use gtk::WrapMode, not pango::WrapMode

### ISSUE THREAD

**Issue by Dieff** [gtk-rs/gtk#1037]
The [wrap_mode](http://gtk-rs.org/docs/gtk/struct.LabelBuilder.html#method.wrap_mode) method on `LabelBuilder` takes a`pango::wrap_mode` struct as an argument. However, the `gtk` library also exports an enum called `WrapMode` which appears to be almost the same (just with the addition of a `None` variant). Every place within `gtk` functions that I can find uses the pango version of `WrapMode`. 

It seems to me that the `gtk::WrapMode` is redundant, and maybe if it were changed than all of functions which use `pango::WrapMode` could use `gtk::WrapMode` instead. This would simplify the use of the library, because it wouldn't be necessary to import `pango` just to set the wrapping mode of gtk widgets.

**Comment by bilelmoussaoui** [comment]
Except the wrapping is handled by pango. The `gtk::WrapMode` is only used in GtkTextView I guess. Anyway, there's nothing that can be done here. Adding a `Into<gtk::WrapMode> for pango::WrapMode` doesn't make sense.
