### ISSUE TITLE
Include libportal in gtk-rs?

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk#1049]
I couldn't find any rust bindings for [libportal](https://github.com/flatpak/libportal) and was wondering if gtk-rs might be a good home for that. While it's hosted at flatpak, it is GObject based and closely related to the GNOME stack.

**Comment by sdroege** [comment]
Another option would be https://gitlab.gnome.org/World/Rust, which already collects various other GNOME-related Rust bindings.

**Comment by alatiera** [comment]
Yes, if you generate the bindings feel free to ping me and we can move it to the gnome gitlab above.

**Comment by sdroege** [comment]
Let's close this for now then
