### ISSUE TITLE
glib and gio compatibility scheme

### ISSUE THREAD

**Issue by matanster** [gtk-rs/gtk#1055]
Hi,

I assume it typically "simply works", but just maybe some explicit guideline might be useful as to [how to choose glib and gio versions when using the gtk crate](https://stackoverflow.com/a/63810863/1509695). 

I also wonder, just out of architectural curiosity, why doesn't the gtk crate bring along those two others.

I could assume that it all borrows/stems from the compatibility scheme of the native libraries themselves which these crates expose for rust, but am not very experienced about that.

Thanks in advance for any clarification!

Rust newb

**Comment by sdroege** [comment]
For the next round of releases I'd like to give everything the same version number, it's just too confusing otherwise. See https://github.com/gtk-rs/release/issues/130

**Comment by matanster** [comment]
I think giving the same version number might be just "cosmetics". It might e.g. be more meaningful to specify which version of the crate corresponds to which version of the underlying library. And which crates have been tested with which other crates, especially regarding gtk. 

IMHO.

**Comment by sdroege** [comment]
> It might e.g. be more meaningful to specify which version of the crate corresponds to which version of the underlying library.

You select the minimum version you want to support of the underlying library via cargo feature flags. That's independent of the crate version.

> And which crates have been tested with which other crates, especially regarding gtk.

In what sense?

**Comment by sdroege** [comment]
It seems like something is confusing with the documentation, but I'm not sure I understand what exactly.
