### ISSUE TITLE
Broken requirements URL in README.md

### ISSUE THREAD

**Issue by edgarogh** [gtk-rs/gtk#1060]
The [requirements URL](https://github.com/gtk-rs/gtk/blame/f6f3124c6d40990131693b7d9aa5dbae40b7deed/README.md#L10) is broken and leads to a GitHub 404.

I'm having troubles apt-installing the system dependencies and having access to this file would be useful.

**Comment by sdroege** [comment]
Having Rust and then via `apt` `libgtk-3-dev` and `pkg-config` should be sufficient.

**Comment by edgarogh** [comment]
The build fails with `Requested 'gdk-3.0 >= 3.24' but version of GDK is 3.22.30` unfortunately. I don't want to break my system by compiling the C libraries manually.

**Comment by sdroege** [comment]
You're trying to compile a crate then that requires the `v3_24` feature of `gtk` or `gdk`, but your system's version is too old. Either try to get it to not require such a new version of gtk, or you'll have to update it.

>  (this is a bit off-topic for this issue anyways)

Indeed, just trying to help you here :) I'm not sure where the requirements page disappeared to (@GuillaumeGomez ?) but it also wouldn't have helped you with this specific problem.

**Comment by GuillaumeGomez** [comment]
The requirements page was removed a while ago (you can see the follow-up PR [here](https://github.com/gtk-rs/gtk-rs.github.io/pull/141) when we fixed the URL). Now we just link to the GTK installation page.

**Comment by edgarogh** [comment]
Oh thank you @sdroege for mentioning the feature, I was actually trying to compile an example and didn't realize that the `gdk >= 3.24` version requirement was controlled by a feature. I thought that it was an absolute requirement. Regarding "(this is a bit off-topic for this issue anyways)", I simply didn't wan't to annoy anyone else with unrelated discussion, but I'm really thankful for the help.

**Comment by sdroege** [comment]
@edgarogh Do you have a suggestion where to add this in the documentation? Where would you have looked to find this? :)
