### ISSUE TITLE
Compiling a Graphical application in windows without command prompt

### ISSUE THREAD

**Issue by anfractuosity** [gtk-rs/gtk#107]
So far the only way, which is very hacky I've got the command prompt to disappear is to use the code on

http://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window

I'm wondering if anyone can explain how to link with -mwindows to make the application Graphical only

**Comment by GuillaumeGomez** [comment]
Sorry, I don't develop on windows, so I can't help you myself.
@gkoz: do you have an idea for his issue ?

**Comment by gkoz** [comment]
Not sure. I thought a build script was capable of passing extra compiler options. Can't test at the moment.

This question may have better chances of being answered on [discuss](https://users.rust-lang.org/).

**Comment by anfractuosity** [comment]
Cheers, I've just posted on there

**Comment by gkoz** [comment]
For the record, the easiest way to do this currently is to use `cargo rustc` like this:
```shell
> cargo rustc --release -- -C link-args=-mwindows
```

**Comment by jeandudey** [comment]
You can try hiding the console programatically, see [this][solink].

[solink]: http://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window/29764309#29764309
