### ISSUE TITLE
Pressing the mouse button yields two button events

### ISSUE THREAD

**Issue by Voker57** [gtk-rs/gtk#1073]
testcase: https://github.com/Voker57/gtk-rs-button-testcase
run and click somewhere in the window

Expected output:
```
ButtonPress
ButtonRelease
```

output:
```
ButtonPress
ButtonPress
ButtonRelease
ButtonRelease
```

Tested on: Debian Sid

C testcase also included, behaves properly.

**Comment by sdroege** [comment]
That looks like a bug in GTK that should also be reproducible from C. That's literally just printing the event type field of the event.

Can you report that here: https://gitlab.gnome.org/GNOME/gtk/-/issues/new ? Thanks

**Comment by sdroege** [comment]
The C testcase behaves different so something wrong here.

**Comment by sdroege** [comment]
I'm not sure why but this seems to behave correctly. Your difference is that you return `TRUE` in the C code but `Inhibit(false)` in the Rust code. If you make it the same in both then they behave the same.

**Comment by Voker57** [comment]
Right, thank you.
