### ISSUE TITLE
GestureDrag does not signal events

### ISSUE THREAD

**Issue by Voker57** [gtk-rs/gtk#1075]
Sorry if I'm again inadvertently using the issues as support, but I triple-checked the testcases to be identical this time :-)

So, creating a GestureDrag on ApplicationWindow in Rust, clicking (or dragging) in the window does not trigger the drag-begin-event, but in C it does.

Testcases: https://github.com/Voker57/gtk-rs-button-testcase/tree/drag

**Comment by sdroege** [comment]
`gesture_drag` is unreffed at the end of the `activate` signal handler closure. As nothing else is keeping a reference to it, it is then destroyed and there's no chance for the signal to trigger anymore. You need to keep it alive somehow for as long as you need it.

In the C code you're leaking `gesture_drag`.
