### ISSUE TITLE
Can't seem to find a way to get children from a container

### ISSUE THREAD

**Issue by anfractuosity** [gtk-rs/gtk#110]
I've just grepped the repo for gtk_container_get_children, but can't seem to find it currently?

So is there no way to obtain the children from a container currently?

cheers

Chris

**Comment by GuillaumeGomez** [comment]
That's because it's using `GList` object. This is one of the less binded features. @gkoz is currently working on the GObject reform so I try not to change code too much. I guess the question should be asked to him directly then. So, @gkoz, what do you think of this ?

**Comment by gkoz** [comment]
This will get fixed as a consequence of the objects reform (#59). Actually, the `ContainerExt` trait in that branch has this method but the converted crate isn't usable yet. Right now there's an [ongoing effort](https://github.com/gkoz/gir) to automate (at least some of) the work needed to convert over 100 structs there are in this crate.

**Comment by anfractuosity** [comment]
Awesome, look forward to that!

**Comment by gkoz** [comment]
Fixed by #221
