### ISSUE TITLE
Cairo update causes failed gtk build

### ISSUE THREAD

**Issue by thePalindrome** [gtk-rs/gtk#124]
Expected:
successful build.

Results:
Failed build due to signal.rs:574 calling Context::wrap(), which was removed in rust-gnome/cairo@54a06c59f6522f4c7cd270587572ae188fe5d112

Workaround:
Use commit before mentioned commit.

Thoughts:
Committer seems to imply that Context::wrap() is obsolete, I do not know enough rust to glean the meaning.

**Comment by GuillaumeGomez** [comment]
@gkoz

**Comment by gkoz** [comment]
cargo update?

**Comment by gkoz** [comment]
Right.
You should look into replacing git dependencies with crates.io ones.
