### ISSUE TITLE
Add gtk 3.16 functions

### ISSUE THREAD

**Issue by PhnxRbrn** [gtk-rs/gtk#125]
Add new functions from gtk 3.16

**Comment by chills42** [comment]
This would be great! I just tried the install on mac with `brew install gtk+3` and got

    ==> Downloading https://homebrew.bintray.com/bottles/gtk+3-3.16.6.yosemite.bottle.tar.gz
    Already downloaded: /Library/Caches/Homebrew/gtk+3-3.16.6.yosemite.bottle.tar.gz
    ==> Pouring gtk+3-3.16.6.yosemite.bottle.tar.gz
    ==> /usr/local/opt/glib/bin/glib-compile-schemas /usr/local/share/glib-2.0/schemas
    🍺  /usr/local/Cellar/gtk+3/3.16.6: 1298 files, 79M

**Comment by gkoz** [comment]
This issue doesn't describe any specific problem currently. I believe the library should just work with GTK 3.16 and higher.

**Comment by GuillaumeGomez** [comment]
It just won't have the specific functions from 3.16 and higher versions

**Comment by gkoz** [comment]
The bindings for functions and classes from various versions might be missing, simply saying "3.16" is not useful.

**Comment by PhnxRbrn** [comment]
Sorry I was referring to adding the new functions from 3.16
