### ISSUE TITLE
Access to TextIter from TextBuffer

### ISSUE THREAD

**Issue by pd40** [gtk-rs/gtk#139]
This is an enhancement request to read the contents of a TextBuffer, unless there is a mechanism to do this already..

TextView implements get_buffer() for access to [TextBufferTrait](https://github.com/rust-gnome/gtk/blob/master/src/traits/text_buffer.rs). TextBufferTrait only appears to implement set_text(). 

Is there a mechanism to get access to the TextIter of a TextBuffer?

**Comment by insanebits** [comment]
It seems TextBuffer is missing get_text method as well.

Yesterday did some testing on your fix and it seems to be working :)

Can you create a pull request so we can start using it?

**Comment by GuillaumeGomez** [comment]
Wo, this is an old one! Like, @insanebits asked, can you create a PR @pd40 please ? :)

**Comment by pd40** [comment]
Thanks for trying it out @insanebits. 

Pull request [#159](https://github.com/gtk-rs/gtk/pull/159)

**Comment by gkoz** [comment]
This should be fixed in #221
