### ISSUE TITLE
Add support for Glade

### ISSUE THREAD

**Issue by jacek99** [gtk-rs/gtk#140]
Pls document how to use this with Glade.

**Comment by GuillaumeGomez** [comment]
What is Glade ? A link please ?

**Comment by jacek99** [comment]
https://glade.gnome.org/

Visual GUI builder for GTK+. With ability to define callbacks in different languages for events, actions,e tc.

**Comment by jacek99** [comment]
http://www.gtk.org/language-bindings.php

**Comment by gkoz** [comment]
Here's an example: https://github.com/rust-gnome/examples/blob/pending/src/builder_basics.rs

**Comment by dubcanada** [comment]
All you need to do is support https://developer.gnome.org/gtk3/stable/GtkBuilder.html which is already supported as gkoz has showed.

**Comment by genodeftest** [comment]
This issue can be closed.

**Comment by ZelphirKaltstahl** [comment]
> Here's an example: https://github.com/gtk-rs/examples/blob/master/src/builder_basics.rs

Does no longer exist =(

The documentation at http://gtk-rs.org/docs/gtk/struct.ListStore.html does not tell me for example how I can specify Rust String type for a `Gtk::ListStore` column. More examples would be great, especially when it comes to how types in glade map to types in Rust.

Please reopen this.

**Comment by EPashkin** [comment]
All examples moved to `bin` subfolder https://github.com/gtk-rs/examples/blob/master/src/bin/builder_basics.rs
ListStore example https://github.com/gtk-rs/examples/blob/master/src/bin/simple_treeview.rs

**Comment by ZelphirKaltstahl** [comment]
@EPashkin Thanks, I did not know about the moved examples. True, it does not tell how to map the types. If there was some glade output next to it … but then the whole code might be different.
