### ISSUE TITLE
entry should have editablesignals

### ISSUE THREAD

**Issue by ztq56** [gtk-rs/gtk#141]
such as `connect_changed`, but I cannot find in the source.

**Comment by gkoz** [comment]
For now it'd probably be easier to add these three signals to both `EntrySignals` and `SpinButtonSignals`. Or just the `changed` if you only need this one.

**Comment by aethertap** [comment]
The `connect_changed` signal was included in [#208](https://github.com/gtk-rs/gtk/pull/208). I'll add the others when I get past my current project deadline.

**Comment by GuillaumeGomez** [comment]
@aethertap: Thanks! :)

**Comment by EPashkin** [comment]
@aethertap We replace `Entry::changed` signal by its `Editable` version. Your code still working?

**Comment by EPashkin** [comment]
@ztq56 Sorry for long wait, signal added. Can you check it?

**Comment by ztq56** [comment]
I'm sorry but I have switched to python now. I'll close the issue!
Thanks anyway!
