### ISSUE TITLE
Setting EntryCompletion for Entry

### ISSUE THREAD

**Issue by LordSentox** [gtk-rs/gtk#148]
The Entry trait is currently lacking the function *set_completion()*. It is included in the *ffi crate*, but somehow doesn't seem to have made it into the *gtk crate*.

**Comment by GuillaumeGomez** [comment]
Well saw, thanks ! Do you mind opening a PR to fix it ?

PS: [doc url](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-completion)

**Comment by LordSentox** [comment]
I have created one including the fix in #154
