### ISSUE TITLE
Add event controller and gesture suite

### ISSUE THREAD

**Issue by PhnxRbrn** [gtk-rs/gtk#151]
This currently exists in gtk-sys lib, but it does not appear to have made it into gtk or gtk_glue yet.

- GtkEventController
- GtkGesture
- GtkGestureDrag
- GtkGestureLongPress
- GtkGestureMultiPress
- GtkGesturePan
- GtkGestureRotate
- GtkGestureSIngle
- GtkGestureSwipe
- GtkGestureZoom

**Comment by gkoz** [comment]
I'd advise against implementing so much by hand. the generator development is progressing well now, I'll run it on these and you might then be able to backport them if you wish.
