### ISSUE TITLE
Update gtk_glue

### ISSUE THREAD

**Issue by PhnxRbrn** [gtk-rs/gtk#152]
Update gtk_glue current if defined for newly released GTK_3_18 and move GtkLevelBar into the same if statement as GtkMenuBar

**Comment by gkoz** [comment]
Are you sure there's a problem with the glue? It should be getting all of `GTK_3_4` to `GTK_3_18` defines, so putting more than one per ifdef is pointless.

**Comment by PhnxRbrn** [comment]
Then shouldn't it be updated to reflect that... Currently it has multiple ifdef and I was submitting the PR to stay consistent to what is currently there

**Comment by gkoz** [comment]
It's legacy infrastructure soon to be deleted. Sorry this hasn't been communicated better. Fixing it if something is broken is okay, making it prettier is a waste of time.
