### ISSUE TITLE
Missing GList implementation

### ISSUE THREAD

**Issue by insanebits** [gtk-rs/gtk#161]
Hey guys, the more I work on my GTK project, the more need there is for `GList` support. It is one of the reasons some GTK functionality cannot be implemented because native library returns `GList`. 

For example: to clear `gtk::Box` children you need to get hold of childen. There is native function `gtk_container_get_children` which returns `GList`. 

It would enable more functionality to be implemented easily. 

We could at leat create `struct GList` and implement `Iterator` trait for it. So people would be able retrieve results and iterate over them. Later other methods could be added, since they're already given by the GTK.

I would be willing to help with implementation.

**Comment by gkoz** [comment]
The conversion impl is [already in place](https://github.com/gtk-rs/glib/blob/master/src/translate.rs#L604-L664) and is used in the `object_reform_gir` branch [like this](https://github.com/gkoz/gtk-rs-gtk/blob/object_reform_gir/src/widgets/container.rs#L74-L80).

That branch is not ready for prime time yet, there's more work to do on the generator. The `container` module was created manually but it could as well be generated now.

**Comment by GuillaumeGomez** [comment]
Hi !

There are multiple issues with `GList`, not just the missing `Iterator` trait. it's complicated to provide a safe wrapper on it. When the reform will be complete, it'll be easier to do.

**Comment by gkoz** [comment]
PS. if you'd like to contribute, [gir](https://github.com/gkoz/gir) is where the work is needed most currently.

**Comment by insanebits** [comment]
Yeah, found out about object reform after created the issue :) 

Will have a look at the gir! 

We can close it now, thanks
