### ISSUE TITLE
Missing Menu, MenuBar widgets and MenuItemSignals trait

### ISSUE THREAD

**Issue by insanebits** [gtk-rs/gtk#167]
Hey guys, we're missing a couple of widgets and signals. I've got a working prototype for them but they're not yet fully functional to be ready for PR.  Because only activate signal is implemented just to test if it would even work.  

Can someone take a look at my signals implementation, because I'm not that comfortable with a ffi stuff.

Commit can be found here:
https://github.com/insanebits/gtk/commit/78362ba78ddd0047dce687c646253f54f5fd0384

**Comment by gkoz** [comment]
Don't be shy, open a PR :)

**Comment by gkoz** [comment]
#186 has added `Menu`.

**Comment by gkoz** [comment]
An update on `MenuBar` (see also discussion in #217): I believe implementing `MenuBar` and the `GMenu*` family requires adding some `GVariant` bindings first -- https://github.com/gtk-rs/glib/issues/113.

**Comment by wrnice** [comment]
Any news on MenuBar ? I am missing it a lot !

**Comment by gkoz** [comment]
We're more or less ready to generate `gio` and this should follow closely if all goes well.

**Comment by hmeyer** [comment]
This just stroke me as well. Now MenuBar? This is quite a blocker....

**Comment by GuillaumeGomez** [comment]
Continue to spam @gkoz and he will add it. :p
