### ISSUE TITLE
MenuItem::activate conflicts with Widget::activate

### ISSUE THREAD

**Issue by insanebits** [gtk-rs/gtk#168]
Both of those traits implement activate method and trying to call it results in error. Not exactly sure how it should be fixed because they're calling different functions(`gtk_widget_activate` and `gtk_menu_item_activate`).

**Comment by gkoz** [comment]
Looks like we should remove `MenuItem::activate` as redundant because it's handled by dynamic dispatch inside GTK.
To test this hypothesis try the UFCS disambiguation and see if `Widget`'s `activate` does what you expect it to:
```rust
    //item.activate();
    WidgetTrait::activate(&item);
```

**Comment by insanebits** [comment]
Yes it seems to work :) Unless it changes it's own state and then passes it for the `gtk_widget_activate` to handle rest of it. To know exactly you'd have to look at the implementation of `gtk_menu_item_activate`.

**Comment by gkoz** [comment]
Both [send the `activate` signal](https://github.com/GNOME/gtk/blob/master/gtk/gtkmenuitem.c#L1415) but the `Widget` impl has to [ensure such a signal exists](https://github.com/GNOME/gtk/blob/master/gtk/gtkwidget.c#L7722-L7727).
