### ISSUE TITLE
Incorrect input for headerbar set custom title

### ISSUE THREAD

**Issue by PhnxRbrn** [gtk-rs/gtk#173]
The input for set_custom_title under headerbar should take in a widget not an option.

**Comment by gkoz** [comment]
According to [the docs](https://developer.gnome.org/gtk3/stable/GtkHeaderBar.html#gtk-header-bar-set-custom-title):

> You should set the custom title to `NULL`, for the header title label to be visible again.

This `NULL` naturally translates to Rust's `Option::None` although it's slightly complicated by the function being generic, so you have to spell `None` as `None::<Widget>`.

**Comment by PhnxRbrn** [comment]
@gkoz This function can also be used to set other gtk widgets, like a gtk box, to be centered in the headerbar.  I have seen it used this way in other languages such as vala.  
Right now when I use it in that way it errors out with expected core::option::Option<&_>, found &gtk::widgets::progress_bar::ProgressBar.  If it is to be this way by taking in an option, how would I fix this?

**Comment by gkoz** [comment]
Put the reference into an option: `Some(&your_widget)`

**Comment by PhnxRbrn** [comment]
@gkoz Thnak you
