### ISSUE TITLE
Error trying to use combo box

### ISSUE THREAD

**Issue by esn01** [gtk-rs/gtk#174]
src/gui/mod.rs:35:13: 35:57 error: the trait `gtk::traits::widget::WidgetTrait` is not implemented for the type `core::option::Option<gtk::widgets::combo_box::ComboBox>` [E0277]
src/gui/mod.rs:35 		input_box.pack_start(&selection_combo, true, true, 10);
                  		          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I get this error trying to add a combo to a container (box or frame).
Since I'm a newbe to both rust and gtk I don't know how to work around that.
Can somebody help?
Thank you.

**Comment by GuillaumeGomez** [comment]
You have an `Option<ComboBox>`, the `pack_start` function awaits a `ComboBox`. Please take a look at the [Option](https://doc.rust-lang.org/nightly/std/option/enum.Option.html) enum.

**Comment by esn01** [comment]
Thank you for the hint.
Now I definitely know what the unwraps are for. -:)
Thanks!
