### ISSUE TITLE
gtk-sys 0.2.0 w/ gtk 0.0.4 not building

### ISSUE THREAD

**Issue by tsliwkan** [gtk-rs/gtk#179]
Referenced Issues
* https://github.com/rust-lang/cargo/issues/2049
* https://github.com/gtk-rs/gtk/pull/155

Like the rust noob that I am I deleted my `Cargo.lock` file this morning when updating my project that depends on various parts of gtk-rs.

I have tried to get my project building again, but no luck, eventually ending up at the issues referenced above. I have repro'd the case with the following `Cargo.toml` files beginning with what I started with a couple of weeks ago.

    [package]
    name = "repro-test"
    version = "0.0.0"

    [dependencies]
    gdk-sys = "0.1.1"
    gdk = "0.1.1"

    [dependencies.gtk]
    features = ["gtk_3_14"]

and a minimal code file

    extern crate gdk;
    extern crate gdk_sys as gdk_ffi;
    extern crate gtk;

    use gdk::pixbuf::Pixbuf;
    use gdk_ffi::enums::ColorSpace;
    use gtk::traits::*;

    fn main() {
        println!("Does this even work?!");
    }

which fails with 

    Package `gtk v0.0.4` does not have these features: `gtk_3_14`

So I specify the version instead

    [dependencies.gtk]
    version = "0.0.3"
    features = ["gtk_3_14"]

which fails with
    
    Package `cairo-rs v0.0.5` does not have these features: `cairo_1_12`
    
So finally with the new verisons of everything

    [dependencies]
    gdk-sys = "0.2.0"
    gdk = "0.1.3"
    gtk = "0.0.4"

which fails with the exact error detailed in cargo issue above.

I think this project moved repos recently? I previously dug around in in the branches/tags relating to specific crate versions to get the things I needed (esp. the `ColorSpace` enum).

Is this solved by releasing a new crate verison of gtk? Or am I doing something stupid in my configuration?

**Comment by gkoz** [comment]
First, even if the good `Cargo.lock` has been lost you can downgrade any and all of the dependencies manually, e.g.:
```
$ cargo update -p pkg-config --precise 0.3.5
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating pkg-config v0.3.6 -> v0.3.5
```

Next, you might want to read [this blog post](http://gtk-rs.org/blog/2015/09/09/crates-meet-automation.html). It should help you migrate to the new versions.

Whenever we make a large-scale breaking change to the crates, there will be a new announcement on the [front page](http://gtk-rs.org/).

**Comment by gkoz** [comment]
Regarding the `pkg-config` issue, we're planning to release the new crates before Monday so stay tuned. ;)

**Comment by tsliwkan** [comment]
Awesome. Thanks for the quick reply and extra info!
