### ISSUE TITLE
note_book's page_num has inconsistent type

### ISSUE THREAD

**Issue by Alex-PK** [gtk-rs/gtk#212]
In the note_book widget, many functions deal with page_num, but they have inconsistent types.

For example, get_current_page() returns Option&lt;u32&gt;, while set_current_page() and remove_page() accept a i32.

Original GTK uses gint, that equates to the architecture's signed int (i32 or i64).

It's probably safe to use 32bit, but I would make the types consistent, to avoid casting in the code.

**Comment by gkoz** [comment]
This is due to an unfinished attempt to use slightly smarter types for page numbers, as they can't be negative. The `get_current_page` return type is `Option<u32>` with `None` corresponding to negative values. For consistency, `set_current_page` would have to take some kind of `enum PageNumber { Number(u32), Last }` or `Option<u32>`. The former is a mouthful, the latter is somewhat confusing and so no one came around to finishing this.

Essentially this is a clash of Rust and GTK (C) idioms and we don't seem to have worked out a general policy for dealing with such issues. Personally I don't fancy putting `i32` everywhere.

**Comment by GuillaumeGomez** [comment]
At first, we tried to follow `GTK` API requirements as much as possible. But in a second time, we started to want to "improve" it a bit. However, this process isn't complete at all and is done quite randomly unfortunately... :-/

**Comment by gkoz** [comment]
It seems making `set_current_page`, `remove_page`, etc. take `Option<u32>` and converting `None` to `-1` would not be that bad, we could go with that here.

**Comment by GuillaumeGomez** [comment]
@gkoz: That seems less rusty... I really prefer to have `None` instead of `-1`.

**Comment by Alex-PK** [comment]
@GuillaumeGomez I really appreciate your work, and I know it's not easy or quick (there are A LOT of functions in GTK). I hope someday to be good enough with rust to propose some PRs, but until now I try to help by raising issues. :)

I think what @gkoz means is that rust-side you will pass None to set_current_page(), and in the unsafe{} you convert None to -1 to pass it to C-Gtk. I think it's a good idea and it would make the rust-side API more coherent.

The only problem with using u32 instead of i32 is that the user could pass an "overflow number" (3 billion, for example), that's valid for u32, but becomes negative for gint.
I honestly don't have a solution for this. :/

**Comment by GuillaumeGomez** [comment]
Yes, I thought about this, but since u31 doesn't exist. :p

**Comment by gkoz** [comment]
> rust-side you will pass `None` to `set_current_page()`, and in the `unsafe{}` you convert `None` to -1 to pass it to C-Gtk. I think it's a good idea and it would make the rust-side API more coherent.

Yep, that's what I meant.

> The only problem with using `u32` instead of `i32` is that the user could pass an "overflow number" (3 billion, for example), that's valid for `u32`, but becomes negative for `gint`.

Since it doesn't make sense to have `2^31` tabs, panicking on overflow should be sufficient.

**Comment by GuillaumeGomez** [comment]
Then we agree to keep the "rust-way". :)
