### ISSUE TITLE
Images in TreeView?

### ISSUE THREAD

**Issue by panpiotrs** [gtk-rs/gtk#213]
Is it possible to create something like this right now or is code necessary for that not yet implemented? I'm in my third day of learning rust, I know how to work with ordinary text columns, but making list with images is beyond me, can you help a little bit?
![Screenshot](http://i.stack.imgur.com/c2g54.png)

**Comment by GuillaumeGomez** [comment]
Yes, I already did something similar. However I don't really have time (holidaaaaays !). You'll certainly have to wait a few days before having an answer (at least from me), sorry.

**Comment by panpiotrs** [comment]
No problem, I will wait and learn rust in other ways, thank you and happy holidays! :)

**Comment by GuillaumeGomez** [comment]
Ok, I added it in the examples repo [here](https://github.com/gtk-rs/examples/blob/pending/src/treeview.rs#L85-L117). Good luck!
