### ISSUE TITLE
GTK for Windows links in Readme are broken

### ISSUE THREAD

**Issue by rnestler** [gtk-rs/gtk#216]
The links in https://github.com/gtk-rs/gtk#windows to GTK from GNOME are broken:
>  * The GNOME project has an official distribution of GTK+ 3.6: [x86](http://www.gtk.org/download/win32.php), [x64](http://www.gtk.org/download/win64.php).

**Comment by GuillaumeGomez** [comment]
Thanks for reporting it! Interested to open a PR to fix it?

**Comment by rnestler** [comment]
Yes I can do that. Should I just take the links from appveyor.yml?

**Comment by GuillaumeGomez** [comment]
If they work and correspond to what's wanted, then yes.

**Comment by gkoz** [comment]
Ugh, they've removed the download pages. This means we need to put up a howto for installing gtk from msys2. I'd expect the win32builder links used in appveyor to become broken as well, so perhaps those archives need to be backed up. Anyway, while they last, the appropriate link would be just http://win32builder.gnome.org/

**Comment by rnestler** [comment]
I made a PR with just the changed link. I could also try to write a howto for installing msys2 with gtk if that would be appreciated.

**Comment by GuillaumeGomez** [comment]
I totally approve this idea! Just update your current PR if you do it (in a separate commit or in the same one, I don't have preference here).

**Comment by rnestler** [comment]
With the merge of #218 this is fixed :smiley:.
