### ISSUE TITLE
Consider making strings non-optional

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/gtk#220]
Presently the generator produces parameters like `text: Option<&str>` and return values like `Option<String>` in some places, e.g.
```text
about_dialog.rs:fn get_comments(&self) -> Option<String>
about_dialog.rs:fn set_comments(&self, comments: Option<&str>)
```

That `Option` comes from the values being nullable internally.

Do we have reasons to care about the difference between `None` and `Some("")`? I'm inclined to make all string values non-nullable (modifying the conversions to handle `NULL`s gracefully).

**Comment by gkoz** [comment]
cc @EPashkin

**Comment by GuillaumeGomez** [comment]
I'd prefer if `None` corresponded to `NULL`.

**Comment by gkoz** [comment]
cc @csoriano89

**Comment by csoriano89** [comment]
I would say it's mostly ok, however, there can be little discrepancies. Look gtk_header_bar_get_title.
"returns the title of the header, or NULL if none has been set explicitly".
You cannot be sure in this case if title was set explicitly or not if the app set a title of "" and you return "" in both cases. But tbh cannot think that can be a problem from the app side...

I'm not aware of more problematic details for NULL vs ""  from the gtk+ side.

**Comment by csoriano89** [comment]
And I assume you will convert "" to NULL inside gtk-rs, because that is important for thing like GtkAboutDialog, where it only hides the widget containing the comments when the parameter is NULL, not when empty.
The widget with its margins etc is still rendered if i.e. the property comments is "".

**Comment by GuillaumeGomez** [comment]
@csoriano89: I had in mind that we didn't convert "" to NULL. From my point of view, NULL means "I don't want this parameter to be set" whereas "" means "I want this parameter to be empty".

**Comment by csoriano89** [comment]
@GuillaumeGomez then sadly it's not possible to remove the optional string because of what I said in the previous comment.

**Comment by GuillaumeGomez** [comment]
I'm absolutely against removing the optional string, so it's fine by me. :)

**Comment by EPashkin** [comment]
Agree with @GuillaumeGomez about input conversion.

**Comment by gkoz** [comment]
Thanks for the input, I'll leave them as they are :)
