### ISSUE TITLE
pkg-config panic when trying to build on win64 on win GNU Rust 32bit 

### ISSUE THREAD

**Issue by UrKr** [gtk-rs/gtk#222]
I apologize if I'm just missing something obvious.
I'm trying to build a rust project which uses rgtk. I'm building on win7 64bit for win32. 

I followed the instructions under "msys2 toolchain", but when running cargo build I get:

thread '<main>' panicked at 'failed to run `"pkg-config" "--libs" "--cflags" "gi
o-2.0"`: Navedene datoteke ni mogoče najti. (I don't know the english version of this error verbatim, something like, the following file could not be located) (os error 2)', C:\Users\user\.cargo
\registry\src\github.com-48ad6e4054423464\gio-sys-0.2.1\build.rs:17

This is lin 17 in build.rs
let lib = pkg_config::find_library(PACKAGE_NAME)
        .unwrap_or_else(|e| panic!("{}", e));

I'm assuming I have to add something to the path, but I don't know what.

**Comment by UrKr** [comment]
if I run cargo build --release, however, I get this:

thread '<main>' panicked at 'failed to run `"pkg-config" "--libs" "--cflags" "ca
iro"`: Navedene datoteke ni mogoče najti. (os error 2)', C:\Users\Urban\.cargo\r
egistry\src\github.com-48ad6e4054423464\cairo-sys-rs-0.2.1\build.rs:9

**Comment by UrKr** [comment]
adding C:\msys32\mingw32\bin to the PATH resolved it. Maybe it should be added to the instructions, unless I'm missing something

**Comment by GuillaumeGomez** [comment]
No, you're absolutely right. Do you want to make the PR?

**Comment by UrKr** [comment]
Ok, I submitted the pull request. I hadn't done that before, so I hope it's correct. If my edit isn't satisfactory, obviously feel free to substitute it with your own.

**Comment by GuillaumeGomez** [comment]
Don't worry, we're here to help.

**Comment by UrKr** [comment]
I think it's there now. I forgot to press "create pull request".
