### ISSUE TITLE
gtk::SelectionMode::Multiple usage isn't supported (e.g. ListBox)

### ISSUE THREAD

**Issue by UrKr** [gtk-rs/gtk#228]
I'm not sure if this belong in "issues", so let me know if I should ask it somewhere else. 

If I do:
```Rust
let list_box = gtk::ListBox::new().unwrap();
list_box.set_selection_mode(gtk::SelectionMode::Multiple);
```

There doesn't seem to be a method for getting all the selected ListBoxRows, or a method for checking if a row is selected.

```Rust
list_box.get_selected_row().unwrap()
```
Only returns the Row that was selected last.

Has something to solve this not yet been implemented, or am I missing something.

**Comment by EPashkin** [comment]
You tried `get_selected_rows`?

**Comment by UrKr** [comment]
That method doesn't exist as far as I can tell. I tried it, but the compiler said that ListBox doesn't have a method "get_selected_row()". It isn't in the docs either. 

ListBox isn't in shown in the gtktest in the examples repository, so maybe only those that are there are fully supported?

**Comment by GuillaumeGomez** [comment]
I used `Treeview` on my [process-viewer](https://github.com/GuillaumeGomez/process-viewer/blob/master/src/process_viewer.rs). I think it works almost the same way.

**Comment by EPashkin** [comment]
https://developer.gnome.org/gtk3/stable/GtkListBox.html#gtk-list-box-get-selected-rows
Maybe your gtk lower that 3.14 or some gtk-rs build error, it must autodetect gtk version, but seems failed that.

**Comment by gkoz** [comment]
You seem to be using a version from crates.io. The current github version has a lot of improvements (including `ListBox::get_selected_rows`) but it's not quite ready to crates.io.

**Comment by UrKr** [comment]
Thanks for the quick replies!

Aha, I see. I guess I'll use the github version and see how it goes. Otherwise, I'll use the TreeView.

**Comment by GuillaumeGomez** [comment]
@UrKr: My `TreeView` usage is just an example. Take a look at `ListView` if needed.

**Comment by UrKr** [comment]
@GuillaumeGomez I think TreeView would be fine, but I don't see ListView in the docs. Should I be looking at the original Gtk docs?

**Comment by gkoz** [comment]
@UrKr yes, the docs we have are woefully incomplete and we're working on improving them.

**Comment by UrKr** [comment]
@gkoz  Oh, I see. I wasn't aware of that.
