### ISSUE TITLE
Create multiple windows from the same root thread results in panic

### ISSUE THREAD

**Issue by 6D65** [gtk-rs/gtk#233]
Hi,

I'm writing an app that sits in the background and periodically creates windows, for the user to interact with. After those are closed the app would create new windows when needed.
I have tried to emulate this behaviour initially by creating a window with a button in a loop. The first time everything works as expected. The second time the window wouldn't create. I seem to be getting this panic. 

```rust
macro_rules! assert_not_initialized {
    () => (
        if ::rt::is_initialized() {
            panic!("This function has to be called before `gdk::init` or `gtk::init`.");
        }
    )
}
```

Am I missing something obvious? What would be the correct way to close the window to be able later to create another one?

```rust
           loop {
                std::thread::sleep(std::time::Duration::from_secs(3));

                let child = thread::spawn(move || {
                    if gtk::init().is_err() {
                        println!("failed to initialize gtk.");
                        return;
                    }

                    let window = gtk::Window::new(gtk::WindowType::Toplevel)
                    .unwrap();

                    window.set_title("App");
                    window.set_border_width(1);
                    window.set_window_position(gtk::WindowPosition::Center);
                    window.set_default_size(800, 600);

                    window.connect_delete_event(|_, _| {
                        gtk::main_quit();
                        Inhibit(false)
                    });

                    let yes_button = gtk::Button::new_with_label("Yes")
                    .unwrap();

                    window.add(&yes_button);
                    window.show_all();
                    gtk::main();
                });

                child.join();
            }
```

Thanks

**Comment by gkoz** [comment]
The root issue here is that there is a notion of a "main thread" (the very first thread in the app) and you must interact with GTK from that thread only. This is a requirement of OSX, which we don't currently enforce.

Even if you ignore OSX, everything must happen on a single thread (that's why none of the widgets are `Send`). I wouldn't touch GTK after the thread where `gtk::init` was run terminates.

**Comment by 6D65** [comment]
Ok, I think I get it. I get will have to work around this somehow.

For the moment I was able to get the wanted behaviour within the main thread. Actually I do get an error message, after I have extracted the gtk::init() out the of the thread::spawn.

```rust
extern crate gtk;

use gtk::traits::*;
use gtk::signal::Inhibit;
use std::thread;

fn main() {
    if gtk::init().is_err() {
        println!("failed to initialize gtk");
        return;
    }
    loop {
        std::thread::sleep(std::time::Duration::from_secs(2));

        let window = gtk::Window::new(gtk::WindowType::Toplevel).unwrap();
        window.set_title("App");
        window.set_border_width(1);
        window.set_window_position(gtk::WindowPosition::Center);
        window.set_default_size(800, 600);

        window.connect_delete_event(|_, _| {
            gtk::main_quit();
            Inhibit(false)
        });

        let yes_button = gtk::Button::new_with_label("Yes").unwrap();
        window.add(&yes_button);
        window.show_all();
        gtk::main();
    }
}

```

**Comment by gkoz** [comment]
A method of talking from other threads to the GUI thread via `idle_add` is shown in [this example](https://github.com/gtk-rs/examples/blob/master/src/multithreading_context.rs).
