### ISSUE TITLE
TreeStore.set_value should take ToValue instead of Value

### ISSUE THREAD

**Issue by sbstp** [gtk-rs/gtk#280]
Not sure if this was noticed, but the `set` method uses `ToValue` and the `set_value` method uses `Value`, which is less convenient.

http://gtk-rs.org/docs/gtk/struct.TreeStore.html?#method.set_value

**Comment by GuillaumeGomez** [comment]
cc @gkoz

**Comment by gkoz** [comment]
To me the only difference between `set` and `set_value` is that the latter takes a reference to an existing `Value`, potentially avoiding unnecessary copying through `to_value()`. This difference probably isn't anyone should care about. If that is the case, I'd rather just remove `set_value`.

**Comment by GuillaumeGomez** [comment]
@gkoz: Please remove it, it might create unneeded confusion (and doesn't seem to be useful anyway...).

**Comment by sbstp** [comment]
Are strings cloned when they go from rust to gtk?
