### ISSUE TITLE
How to include gdk_pixbuf::Pixbuf ?

### ISSUE THREAD

**Issue by gbersac** [gtk-rs/gtk#282]
I want to create an [`Image`](http://gtk-rs.org/docs/gtk/struct.Image.html) out of a [`PixBuf`](http://gtk-rs.org/docs/gdk_pixbuf/struct.Pixbuf.html). Problem, I don't know how to include `PixBuf`. None of this work :

```rust
use gdk::PixBuf;
use gtk::PixBuf;
use gdk_pixbuf::PixBuf;
use gdk::gdk_pixbuf::PixBuf;
```

How to include `PixBuf` ?

An, by the way, you should create an example for [this case](https://github.com/gtk-rs/gtk/issues/28) : (this is the one I am struggling on). I'll agree to create a pull request if you help me solve this problem.

**Comment by GuillaumeGomez** [comment]
I don't know "PixBuf" but we provide a `Pixbuf` type. And we'd be glad to add an example with it.

**Comment by gbersac** [comment]
Thanks for answering so quickly !

The struct I am talking about is this one : http://gtk-rs.org/docs/gdk_pixbuf/struct.Pixbuf.html

I need it because I need one to create an [image using `new_from_pixbuf`](http://gtk-rs.org/docs/gtk/struct.Image.html#method.new_from_pixbuf).

**Comment by GuillaumeGomez** [comment]
It was a joke. In your code you wrote "PixBuf" instead of "Pixbuf" for your import. So I thought it was your issue.

**Comment by gbersac** [comment]
Ok, I fixed the mistake in my post. But that leave the question open. How to include `PixBuf` ? Or create an `Image` out of a byte array. Or display a byte array using gtk.

**Comment by GuillaumeGomez** [comment]
So here is my Cargo.toml:

```Toml
[package]
name = "g_test"
version = "0.1.0"
authors = [""]

[dependencies]
gtk = "0.0.7"
gdk-pixbuf = "0.0.1"
```

And here is my main:

```Rust
extern crate gtk;
extern crate gdk_pixbuf;

use gdk_pixbuf::Pixbuf;

fn main() {
    println!("Hello, world!");
}
```

Works fine so I don't understand your import issue. Are you sure you imported the crate as well?

**Comment by GuillaumeGomez** [comment]
Since it works fine for me, I'll close this issue. Don't hesitate to comment on it if you're still having the problem.
