### ISSUE TITLE
HeaderBar not found

### ISSUE THREAD

**Issue by Max-Might** [gtk-rs/gtk#283]
Hello.

I an trying to build a simple window using the latest release but it is not able to find the `HeaderBar` struct.

The code I use is this:

```rust
use gtk::{Window, WindowType, Label, HeaderBar};
```
and the error is

`unresolved import gtk::HeaderBar. There is no HeaderBar in gtk`

**Comment by GuillaumeGomez** [comment]
Can you show us your `Cargo.toml` file please? And don't forget to run `cargo update` on your project if it's not a new one.

**Comment by Max-Might** [comment]
Ok, here is my dependencies section:

```toml
[dependencies]
gtk = "0.0.7"
gio-sys = "0.3.0"
```

**Comment by EPashkin** [comment]
`HeaderBar` required enabling v3_10 feature for gtk
Try add something like
```
[features]
default = ["gtk/v3_10"]
```

**Comment by Max-Might** [comment]
Ah, yes, that feature was need indeed. Thanks :)
