### ISSUE TITLE
clone!

### ISSUE THREAD

**Issue by anfractuosity** [gtk-rs/gtk#290]
I'm not sure if this is of any help for anyone, but I just tweaked your clone! macro, so it can accept typed 
parameters too (at the moment i'm not sure how to mix underscores's with typed parameters though) so for instance it can accept:

```
clone!(bob => move |_| { ... 
```

or

```
clone!(bob => move |x:String| { ...
```

but not 

```
clone!(bob => move |_,x:String| { ...
```

```
macro_rules! clone {
    (@param _ ) => ( _ );
    (@param $x:ident) => ( $x );
    ($($n:ident),+ => move || $body:expr) => (
        {
            $( let $n = $n.clone(); )+
            move || $body
        }
    );
    ($($n:ident),+ => move |$($p:tt),+| $body:expr) => (
        {
            $( let $n = $n.clone(); )+
            move |$(clone!(@param $p),)+| $body
        }
    );
    ($($n:ident),+ => move |$($p:tt : $z:ty),+| $body:expr) => (
        {
            $( let $n = $n.clone(); )+
            move |$(clone!(@param $p) : $z,)+| $body
        }
    );
}
```

**Comment by GuillaumeGomez** [comment]
Actually it can. However, I think remembering that @gkoz said something about not needing a workaround like this anymore in future version. If not, we should think of a way to implement it.

**Comment by gkoz** [comment]
No, the bad ergonomics of cloning stuff into closures are here to stay. I guess we could make a crate with just this macro.

> `clone!(bob => move |_,x:String| {`

This seems to work in the following form:

`clone!(bob => move |_: _, x: String| {`

**Comment by Cogitri** [comment]
Maybe it'd make sense to recommend using [enclose](https://crates.io/crates/enclose) or something similar then, instead of virtually every gtk-rs app using its own clone macro?

**Comment by GuillaumeGomez** [comment]
The `clone!` macro should be avoided now. We're working on making a new one available which doesn't have the issues that `clone!` has.

**Comment by Cogitri** [comment]
Ah, cool. Will that be integrated into gtk-rs somehow?

**Comment by GuillaumeGomez** [comment]
I think we'll put it into `glib`.

**Comment by Cogitri** [comment]
Alright, great, thanks for the info! :)

**Comment by sdroege** [comment]
The idea would be to have a macro like clone but extend it with support for weak references too. Are there any other things with the current (copied around) clone macro that you'd like to see changed?

**Comment by Cogitri** [comment]
> any other things with the current (copied around) clone macro that you'd like to see changed?

It'd be nice if I could do stuff like `clone!(struct.field`, right now I have to do `let field = struct.field; clone!(field`, which is a bit annoying (or maybe I'm just doing it wrong?)

Also, I think I prefer enclose's syntax a bit:

With clone:
`object.connect_changed(clone!(object2 => move |_, _|{}));`

With enclose:

`object.connect_changed(enclose!((object2) move |_, _|{})`

But I guess that's just me.

**Comment by GuillaumeGomez** [comment]
I don't like wrapping inside parens. :-/

**Comment by sdroege** [comment]
We'll probably need some kind of wrapping for distinguishing strong/weak references and also to allow renaming variables (e.g. also for being able to use struct fields). The parenthesis could work as delimiters for the different arguments.

**Comment by Cogitri** [comment]
Yup, enclose allows for renaming: `enclose!((old_name => new_name)`

**Comment by sdroege** [comment]
The `clone!` macro is now part of the glib crate.
