### ISSUE TITLE
Disable a signal temporarily

### ISSUE THREAD

**Issue by anfractuosity** [gtk-rs/gtk#291]
I'm just wondering if there is currently a way to disable signals for a widget temporarily, I can't seem to find any calls to any *block* functions for widgets.

cheers

Chris

**Comment by gkoz** [comment]
We don't have a safe way but the `connect_*` functions return the handler id, which can be given to `gobject_sys::g_signal_handler_block`.

**Comment by anfractuosity** [comment]
Thanks a lot! That did the job nicely.

**Comment by jlgerber** [comment]
HOW???? gobject_sys::g_signal_handler_block takes a *mut GObect and a u64... I have a widget and a glib::signal::SignalHandlerId....

**Comment by EPashkin** [comment]
https://gtk-rs.org/docs/glib/object/trait.ObjectExt.html#tymethod.block_signal
Example based on https://github.com/gtk-rs/examples/blob/master/src/bin/builder_basics.rs#L26
```
    let signal = bigbutton.connect_clicked(move |_| {
        dialog.run();
        dialog.hide();
    });
    bigbutton.block_signal(&signal);
```
