### ISSUE TITLE
Thousands of Theme parsing errors, resulting in unskinned programs

### ISSUE THREAD

**Issue by jonas-schievink** [gtk-rs/gtk#304]
When I start any application using gtk-rs, I get many screens full of these warnings:
```
...

(gtktest:27278): Gtk-WARNING **: Theme parsing error: gtk.css:3770:45: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(gtktest:27278): Gtk-WARNING **: Theme parsing error: gtk.css:3771:43: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(gtktest:27278): Gtk-WARNING **: Theme parsing error: gtk.css:3894:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(gtktest:27278): Gtk-WARNING **: Theme parsing error: gtk.css:3902:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(gtktest:27278): Gtk-WARNING **: Theme parsing error: gtk.css:3956:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(gtktest:27278): Gtk-WARNING **: Theme parsing error: gtk.css:4032:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'
```

This is how `gtktest` looks for me:
![2016-04-11-223445_4880x1080_scrot](https://cloud.githubusercontent.com/assets/1786438/14441580/c0473406-0035-11e6-880e-1b41191590f3.png)

This is on stable Rust 1.7. I'm on a x86_64 Arch Linux machine. Installed Versions of select packages:
```
local/glib2 2.48.0-1
    Common C routines used by GTK+ and other libs
local/gtk-engines 2.21.0-2
    Theme engines for GTK+ 2
local/gtk-update-icon-cache 3.20.2-1
    GTK+ icon cache updater
local/gtk2 2.24.30-1
    GObject-based multi-platform GUI toolkit (legacy)
local/gtk3 3.20.2-1
    GObject-based multi-platform GUI toolkit
local/gdk-pixbuf2 2.34.0-1
    An image loading library
local/lib32-gdk-pixbuf2 2.34.0-1
    An image loading library (32-bit)
```

**Comment by GuillaumeGomez** [comment]
You're already on 3.20?! That's quite impressive!

@gkoz: I guess we have to make a conditional code starting `3.20` on this example? Or maybe try to avoid deprecated stuff if possible (which I doubt).

**Comment by EPashkin** [comment]
No theme error if you run other gtk3 program from console?

**Comment by jonas-schievink** [comment]
@EPashkin Huh, Wireshark is indeed spewing the same errors and looks broken (I think that's about the only GTK 3 app I have installed). Maybe it's an upstream issue, or maybe Wireshark lacks support as well, I'll take a closer look.

**Comment by jonas-schievink** [comment]
Ugh, looks like my theme (Breeze-Dark) was broken by an update. Sorry for the noise! :sweat_smile:

**Comment by gkoz** [comment]
Isn't GNOME notorious for breaking themes in every release? :wink:
