### ISSUE TITLE
Applying new enums and bitflags to gtk-rs modules.

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gtk#307]
https://github.com/gtk-rs/gir/pull/229 added generation of enums and bitflags and changes in code that assumes that all of it has `.to_glib(_xxx)` and `from_glib(_xxx)` functions.
For this need add changes to all `gtk-rs` modules so I create this issue for tracking it progress.

- [x] gtk -> 310
- [x] gdk -> 115

/*Currently no change needed in other modules
- [ ] pango
- [ ] cairo ?
- [ ] glib
- [ ] gio ?
- [ ] examples

*/
Also I propose don't merge to any PR that unrelated to this issue until it was fixed.

EDIT: Goal this issue is get buildable `gtk` with generated enums,
we were lucky and it needed only changes in `gdk`,
so after 155 merged I update 310 and it must pass build.

**Comment by EPashkin** [comment]
@gkoz You doing changes yourself or want help?

**Comment by gkoz** [comment]
We should probably start from `gio` and gradually go up to `gtk` along the dependency tree, converting other crates to generated mode. I'll put up the gio crate and then I don't mind someone else trying to tinker with any of the crates.

**Comment by EPashkin** [comment]
Strange, but needed only changes in `gtk` and `gdk`, so I add PRs with auto regens.

**Comment by EPashkin** [comment]
Updated issue.

**Comment by EPashkin** [comment]
Now `gtk` updated and builds (not on travis) so I close this
