### ISSUE TITLE
ObjectExt trait links all 404 in docs

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#321]
[BuildableExt](http://gtk-rs.org/docs/gtk/trait.BuildableExt.html) is linked to from the [ToggleToolButton](http://gtk-rs.org/docs/gtk/struct.ToggleToolButton.html) page but doesn't appear to exist.

**Comment by gkoz** [comment]
That trait just shouldn't have existed, references to it will be removed from the docs.

**Comment by hectorgrey** [comment]
Similar error for [ObjectExt](http://gtk-rs.org/docs/gtk/trait.ObjectExt.html) in [MenuBar](http://gtk-rs.org/docs/gtk/struct.MenuBar.html)...

**Comment by Susurrus** [comment]
`BuildableExt` has been fixed, but `ObjectExt` is still a 404.
