### ISSUE TITLE
Invalid links

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#331]
On the [TextBuffer page](http://gtk-rs.org/docs/gtk/struct.TextBuffer.html) the link in the main description paragraph is improperly rendered.

**Comment by Susurrus** [comment]
Includes the [TextTag page](http://gtk-rs.org/docs/gtk/struct.TextTag.html) as well.

**Comment by GuillaumeGomez** [comment]
Thanks for the feedback!

**Comment by Susurrus** [comment]
These are actually all for the TextWidget class that doesn't seem to exist in the docs. So maybe the docs are trying to auto-link it, but not finding the reference, leave it as plain text.

**Comment by GuillaumeGomez** [comment]
I think yes. But since this doc is the one from the current crates.io version, these issues might be resolved since then.

**Comment by EPashkin** [comment]
Its plain text in `Gtk-3.0.gir` on real page https://developer.gnome.org/gtk3/stable/GtkTextBuffer.html links to https://developer.gnome.org/gtk3/stable/TextWidget.html.
We can replace [xxx][url] to link, but not sure it we need do that.

**Comment by gkoz** [comment]
I suppose the way to fix this would be to make the `struct TextBuffer` docs manual and put a correct link there. Eventually that page could be translated to Rust and hosted on gtk-rs.org

**Comment by GuillaumeGomez** [comment]
Isn't it better to wait for the next release? We can add it manually on the doc repo at that moment.

**Comment by gkoz** [comment]
The docs repo has so much machine-generated stuff that we can't hope to also manage manual patches. We could look into making the docs generator repwrite links from `[xxx][url]` to `[xxx](https://developer.gnome.org/gtk3/stable/url)`.

**Comment by GuillaumeGomez** [comment]
No I mean, we already have the doc overriding. Couldn't it the same here as well?

**Comment by gkoz** [comment]
Ah, that what I meant by manual docs.

**Comment by GuillaumeGomez** [comment]
Oh my bad. Then we agree . :smiley:

**Comment by GuillaumeGomez** [comment]
I think I'll do it. I never really work on the doc repo.

**Comment by EPashkin** [comment]
When changing `[xxx][url]` to `[xxx](https://developer.gnome.org/gtk3/stable/url)` we need check for links, that we already have in doc (example for `RadioButton` we need link to your site not gnome's).

**Comment by gkoz** [comment]
Indeed, looks like the dumb solution won't work.

**Comment by Susurrus** [comment]
The first link I posted on TextBuffer has been fixed, but the link on TextTag is still incorrect.

**Comment by Susurrus** [comment]
Both of my original examples here have fixed links now, so I'm going to go ahead and close this.
