### ISSUE TITLE
gtk::STYLE_PROVIDER_PRIORITY_* should be u32

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#333]
These are defined as unsigned ints in Gtk. Additionally them being i32 requires a cast before being able to use them properly with `StyleContext::add_provider()` as intended.

**Comment by EPashkin** [comment]
Its defined in manual part https://github.com/gtk-rs/gtk/blob/4a602797abc45adc12d453e14e4a9fa966cceb07/src/lib.rs#L179-L183
Feel free to make PR with fix (as you can check that it really working)

**Comment by Susurrus** [comment]
I modified just that file, but then I got a conflict because the FFI types are i32s. I would think the fix should be in the FFI bindings and not in this file, though I could cast them. I'll need some more time to dig into this as I've never dealt with FFI or gir and I don't understand how it works yet.

**Comment by EPashkin** [comment]
As FFI binding also auto-generated by gtk's gir files, and it says
```xml
    <constant name="STYLE_PROVIDER_PRIORITY_FALLBACK"
              value="1"
              c:type="GTK_STYLE_PROVIDER_PRIORITY_FALLBACK">
      <doc xml:space="preserve">The priority used for default style information
that is used in the absence of themes.

Note that this is not very useful for providing default
styling for custom style classes - themes are likely to
override styling provided at this priority with
catch-all `* {...}` rules.</doc>
      <type name="gint" c:type="gint"/>
    </constant>
```
So we can only add `as u32` to these lines if most functions that it used require `u32`

**Comment by EPashkin** [comment]
By way, on not-crate version of gtk IMHO was added some conversion from u32 to i32 and back (don't fount it now), so may be adding `.into()` to your code also works.

**Comment by gkoz** [comment]
I think guess the introspection tools assigned `gint` type by default because C defines aren't typed. If some functions still take `i32` instead of `u32` that should be handled via type rewriting (also #246).
