### ISSUE TITLE
Panic when issuing `gtk::main_quit()` in `window.connect_delete_event()`

### ISSUE THREAD

**Issue by mmstick** [gtk-rs/gtk#344]
In my [application](https://github.com/mmstick/systemd-manager), it would seem that quitting the program with `gtk::main_quit()` in the main window's `connect_delete_event()` closure is causing a panic with `Option::unwrap() on a None`, but issuing `gtk::main_quit()` when the Escape key is pressed does not cause a panic. [relevant code](https://github.com/mmstick/systemd-manager/blob/master/src/systemd_gui.rs#L567:L576)

**Comment by EPashkin** [comment]
Can you show stack trace with `RUST_BACKTRACE=1` ?

**Comment by GuillaumeGomez** [comment]
During my attempt to update your code, I fixed this issue. Build with debug and you'll see the stacktrace. It's not in this closure but in another one.

**Comment by mmstick** [comment]
@GuillaumeGomez I see now. I've fixed it.
