### ISSUE TITLE
Why does set_events() and get_events() use i32 as parameter and return type?

### ISSUE THREAD

**Issue by dhad05** [gtk-rs/gtk#346]
I think they should use `GdkEventMask` to be compatible those masks in `gdk_sys`. Because they use i32 I have to use `mem::transmute()` to write code like this: 
```rust
    unsafe {
        area.0.set_events(area.0.get_events() | mem::transmute::<gdk_sys::GdkEventMask, i32>(
                         gdk_sys::GDK_POINTER_MOTION_MASK | 
                          gdk_sys::GDK_POINTER_MOTION_HINT_MASK |
                          gdk_sys::GDK_LEAVE_NOTIFY_MASK |
                          gdk_sys::GDK_BUTTON_PRESS_MASK
                          ));
    }
```
Is there any better way to write the above code? Or can we change `set_events()` and `get_events()` to be compatible with `gdk_sys`?

**Comment by GuillaumeGomez** [comment]
Well, the transmute is totally useless. Take a [look](https://github.com/gtk-rs/sys/blob/8924ad29e0c551faa2f8b622c27a9dfed1044b74/gdk-sys/src/lib.rs#L2993).

**Comment by dhad05** [comment]
Oh sir I don't know how to write without that transmute. Can you help me!?

**Comment by GuillaumeGomez** [comment]
```rust
unsafe {
        area.0.set_events(area.0.get_events() | (
                         gdk_sys::GDK_POINTER_MOTION_MASK | 
                          gdk_sys::GDK_POINTER_MOTION_HINT_MASK |
                          gdk_sys::GDK_LEAVE_NOTIFY_MASK |
                          gdk_sys::GDK_BUTTON_PRESS_MASK
                          ));
    }
```

Should work, no?

**Comment by dhad05** [comment]
It gives 

    error: the trait `core::ops::BitOr<gdk_sys::GdkEventMask>` is not implemented for 
    the type `i32`

**Comment by GuillaumeGomez** [comment]
```rust
unsafe {
        area.0.set_events(area.0.get_events() as i32 | (
                          gdk_sys::GDK_POINTER_MOTION_MASK | 
                          gdk_sys::GDK_POINTER_MOTION_HINT_MASK |
                          gdk_sys::GDK_LEAVE_NOTIFY_MASK |
                          gdk_sys::GDK_BUTTON_PRESS_MASK
                          ));
    }
```

**Comment by dhad05** [comment]
`get_events()` is an `i32` , you need not cast it :-)

**Comment by GuillaumeGomez** [comment]
`gdk_sys::GDK_POINTER_MOTION_MASK` is an `i32` as well. What version are you using? The one from crates.io?

**Comment by dhad05** [comment]
Yes! In my machine, `gdk_sys::GDK_POINTER_MOTION_MASK` is a `gdk_sys::GdkEventMask` .
Someone on [reddit](https://www.reddit.com/r/rust/comments/4m7zqw/gtkrs_how_to_safely_use_set_events/) show me a way to use `bits()` like this:

```
area.0.set_events(area.0.get_events() | (
                      gdk_sys::GDK_POINTER_MOTION_MASK |
                      gdk_sys::GDK_BUTTON_PRESS_MASK
                      ).bits() as i32);
```
It works. But I would like to find a way to directly use the type :-)

**Comment by GuillaumeGomez** [comment]
On this version you can't. cc @gkoz

**Comment by dhad05** [comment]
Can we change it?

**Comment by GuillaumeGomez** [comment]
The lastest version isn't the one on crates.io (which is getting old now).

**Comment by gkoz** [comment]
The way to directly use it would be
* generate the higher-level type in the gdk crate,
* manually bind `[gs]et_events` to use that type.
