### ISSUE TITLE
TextView should implement gtk::EntrySignals

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#347]
According to [https://developer.gnome.org/gtk3/unstable/GtkTextView.html] `gtk::TextView` should implement `gtk::EntrySignals` as it supports the `insert_at_cursor` signal. I need this for the project I'm working on where I want to trigger an event whenever someone attempts to enter text into a central TextView.

**Comment by GuillaumeGomez** [comment]
https://github.com/gtk-rs/gtk/blob/master/src/auto/text_view.rs#L512 ?

**Comment by Susurrus** [comment]
Was this added since the last release? I was browsing the [documentation](http://gtk-rs.org/docs/) and searching it and this function didn't come up. Maybe they should be regenerated?

**Comment by GuillaumeGomez** [comment]
No, the doc corresponds to the crates.io version. If you want the last version, you need to set the dependency on this repo.

**Comment by Susurrus** [comment]
I was trying to understand if the docs are out-of-date, but it doesn't appear they are for the released version. And since there isn't a system to have up-to-date docs with this repo, I guess I'll need to start browsing the codebase more.

**Comment by GuillaumeGomez** [comment]
You can generate the doc yourself. Just run rustdoc on `src/lib.rs`.

**Comment by gkoz** [comment]
You'll get better docs with `cargo doc --features "embed-lgpl-docs v3_16"` (change `3_16` to whatever your target version is).

**Comment by mairsbw** [comment]
@gkoz This method of generating the docs isn't mentioned in the main README, though I think it'd be worth mentioning there, especially since this way you can specify what GTK version you're targeting.

**Comment by gkoz** [comment]
It is, perhaps not clearly enough.
