### ISSUE TITLE
Remove 4th callback argument for TextBuffer::connect_insert_text as its redundant

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#349]
Gtk provides both a character array and a length argument for the `insert_text` callback because it's necessary in C. This isn't necessary in Rust and the length argument is redundant with the 3rd argument, which already has a length. It should be removed to make it more Rusty.

Relevant function is here: https://github.com/gtk-rs/gtk/blob/d9295b9c776c1b15ec4db0a4025838cb2f92595a/src/auto/text_buffer.rs#L482

**Comment by GuillaumeGomez** [comment]
Indeed. I'll fix it.

**Comment by Susurrus** [comment]
Awesome, thanks! I'll try it out tonight.
