### ISSUE TITLE
Expose gobject_sys::g_signal_stop_emission

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#350]
My understanding is that functions in the `*_sys` modules should not be used in favor of them being exposed in safe Rusty APIs. I'd like to use `gobject_sys::g_signal_stop_emission` and a module allowing its safe use would be useful.

For context in case I should be going about this a different way, is that I'm trying to override the default signal handler for `insert-text` for a TextBuffer so that I can not render the characters in the entry field but still process them within my program.

**Comment by GuillaumeGomez** [comment]
cc @gkoz

**Comment by Susurrus** [comment]
Is this a simple operation, involving copy/paste plus a little modification? If so, I could possibly do this work, though I'm definitely a Rust newbie.

**Comment by gkoz** [comment]
This will take a trifle of design work but should be doable without much experience, mostly you'll need to 'get' how the bindings use the `translate` module and possibly take a peek at libgobject source.

**Comment by gkoz** [comment]
@Susurrus nah, I wasn't. Take a stab at it, it's more fun when more people look into the insides of GTK ;)

**Comment by Susurrus** [comment]
Okay, I've started digging into this a little bit, and I got gir compiling and think I'm ready to start stuff. But here's the question, where should these functions go ([list here](https://developer.gnome.org/gobject/unstable/gobject-Signals.html#g-signal-stop-emission-by-name))? They're in the `glib-object.h` header, logically listed in the docs as `gobject/signals`. I think this function should be `glib::signal::stop_emission_by_name` and put in the manually-created file `src/signal.rs`, does that sound right?

**Comment by EPashkin** [comment]
Yes, `g_signal_connect_data` as `connect` already there.

**Comment by gkoz** [comment]
I don't think gir will be of help here because it doesn't generate free functions in the high-level crates. Placement in `mod signal` is correct.

**Comment by Susurrus** [comment]
I'm getting pretty confused with the organization of this project, so I'd like to clarify some more here. I see that there is a separate `glib` project. Both `glib` and `gtk` have signal modules and it's not clear to me which functions should go in which modules. For example, `destroy_closure()` is actually implemented in both modules, which seems incorrect to me. Also `connect()` is implemented in `glib` only which `idle_add()` and friends are implemented in `gtk`. Can someone clarify where I should be adding a `stop_emission()` function, in `glib` or in `gtk`? I would think even the `idle_add()` functions and friends should be in `glib`, which is why I'm confused.

**Comment by gkoz** [comment]
`libglib` and `libgobject` stuff goes into the `glib` crate as outlined in its synopsis, that would place signal utilities into `glib::signal`.. Closures handling evolves gradually hence little inconsistencies like`destroy_closure` and `connect`. `idle_add` duplication is documented but perhaps not clearly enough?l

**Comment by Susurrus** [comment]
I've started work on this in the glib library for the `g_signal_override_class_handler()` lease see gtk-rs/glib#127, which I think is actually what I want actually. I'll add `stop_emission` once I get that PR sorted out.

**Comment by gkoz** [comment]
`stop_emission` feels like a more realistic target right now because it doesn't need to be aware of each signal's signature.

**Comment by Susurrus** [comment]
This should be done as of gtk-rs/glib@7ff176bb09f2c2b9787f6bb01e4863a04eae5511, but I don't know how glib gets included in gtk, I think it's exposed through gtk as well, so I think this can be closed.

**Comment by gkoz** [comment]
We don't reexport `glib` in `gtk` so you'll have to import it in your project. And yes I believe this can be closed.
