### ISSUE TITLE
Mutable vs non-mutable self

### ISSUE THREAD

**Issue by evmar** [gtk-rs/gtk#352]
Why do all functions use a `&self` rather than a `&mut self` in the case of mutating the object?  E.g. `gtk::ButtonExt::set_label(&self, ...)`.

I am new to Rust so I think this might be something about "interior" vs "exterior" mutability and Gtk references.  But even if that is right, it's worth calling out in the overview documentation.

**Comment by GuillaumeGomez** [comment]
To make it simple: to make gtk's users' life easier.

**Comment by gkoz** [comment]
It's discussed [here](http://gtk-rs.org/docs/glib/#objects) a bit.
