### ISSUE TITLE
Menu popup

### ISSUE THREAD

**Issue by Eilie** [gtk-rs/gtk#353]
Hello, 

It seems like [gtk_menu_popup](https://developer.gnome.org/gtk3/stable/GtkMenu.html#gtk-menu-popup) is missing, how to emulate it? Basically I'd like create a right click pop up menu.

**Comment by GuillaumeGomez** [comment]
Indeed. Strange... cc @gkoz

**Comment by Eilie** [comment]
@EPashkin Could you please provide an example of how to emulate `gtk_menu_popup`?

**Comment by GuillaumeGomez** [comment]
@Eilie: I'll add it in the next hours.

**Comment by gkoz** [comment]
@GuillaumeGomez I think we primarily need a simple variant, that only takes the last two parameters.

**Comment by GuillaumeGomez** [comment]
Well, I finish my patch and then if you find a better way, you can just close it. :)
