### ISSUE TITLE
make gir fails

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#356]
``` bash
$ make gir
find: ‘gir/src’: No such file or directory
find: ‘gir/src’: No such file or directory
git submodule update --init
Submodule 'gir' (https://github.com/gtk-rs/gir.git) registered for path 'gir'
Submodule 'gir-files' (https://github.com/gtk-rs/gir-files.git) registered for path 'gir-files'
Cloning into 'gir'...
remote: Counting objects: 4931, done.
remote: Total 4931 (delta 0), reused 0 (delta 0), pack-reused 4931
Receiving objects: 100% (4931/4931), 730.52 KiB | 1.23 MiB/s, done.
Resolving deltas: 100% (3609/3609), done.
Checking connectivity... done.
Submodule path 'gir': checked out '4d68d198066944dcb0a6f0f48b5bc4f87d829ab0'
Cloning into 'gir-files'...
remote: Counting objects: 75, done.
remote: Total 75 (delta 0), reused 0 (delta 0), pack-reused 75
Unpacking objects: 100% (75/75), done.
Checking connectivity... done.
Submodule path 'gir-files': checked out '11e0e6d1ffcca587f42d91c66064c0c9d21497da'
rm -f gir/target/bin/gir
cargo install --path gir --root gir/target
multiple packages with binaries found: gir, sys_build
Makefile:12: recipe for target 'gir/target/bin/gir' failed
make: *** [gir/target/bin/gir] Error 101
```

The README says that running `make gir` should work in the root directory of this project. I tried it and it fails for me with these errors. Any help is appreciated.

**Comment by EPashkin** [comment]
Strange it, works on new project with `cargo 0.12.0-nightly (7d79da0 2016-05-31)`
```
git clone https://github.com/gtk-rs/gtk.git
cd gtk
make gir
```

**Comment by Susurrus** [comment]
Does it require Cargo to be installed for just the user? It works on my laptop, where it looks like I used rustup to install just into my user account, but my desktop I believe have cargo/rust installed system-wide.

**Comment by EPashkin** [comment]
May be your desktop's cargo too old?
I have rust-nightly Windows (GNU ABI †) (.msi) 64-bit installed for all users on machine.
It still uses users `.cargo` for storage.

**Comment by gkoz** [comment]
The problem seems to be here:
```
cargo install --path gir --root gir/target
multiple packages with binaries found: gir, sys_build
```
Not sure where that `sys_build` comes from. Maybe running this command manually and tweaking options will shed some light.

**Comment by gkoz** [comment]
I can't reproduce with recent beta and nightly builds. stable blows up spectacularly though.

**Comment by gkoz** [comment]
Oh yeah, cargo 0.9.0 (from rustc 1.8) does complain about multiple packages.

**Comment by EPashkin** [comment]
Seems we need recommend remove gir's test folder if using non-stable not option.

**Comment by Susurrus** [comment]
Yes, building failed with the cargo that was installed along with Rust 1.8.0. Upgrading using rustup to 1.9 fixed compilation. Don't know if this is worth fixing, but maybe make Rust 1.9 a minimum requirement for gtk?

**Comment by gkoz** [comment]
gir is not required to build the crate though, only when modifying it, so to me it's almost a non-issue.

**Comment by Susurrus** [comment]
Yes, so if I want to work with GTK and add more GTK functionality I might need `gir` to do it, correct? I'd suggest adding better documentation about *when* you need to run `gir` and then also specify that Rust 1.9 (or whatever equivalent Cargo version) is necessary as a minimum version.

**Comment by Susurrus** [comment]
This isn't a problem for me anymore, so I guess we can close it. I think just updating cargo and/or rust fixed it.
