### ISSUE TITLE
The procedure entry point inflateReset2 could not be located in the dynamic link library zlib1.dll

### ISSUE THREAD

**Issue by ScottHuangZL** [gtk-rs/gtk#360]
I am use Rust 1.11 nightly for windows 7 X64.
I try to build the examples, it can complete successfully, 
however when run the sample exe, it pop up the error dialog with text:

**The procedure entry point inflateReset2 could not be located in the dynamic link library zlib1.dll**

Could you advise how to resove it? Thanks

**Comment by ScottHuangZL** [comment]
**The issue tentative resolved by:**
backup C:\Windows\System32\zlib1.dll to zlib1-w32.dll
**copy zlib1.dll from C:\Windows\SysWOW64 to C:\Windows\System32**

Another tentative try, but failed, so have to use above solution.
Copy the zlib1.dll to target\debug folder which same folder as the sample exes,
however, it still not work.

How to let the sample exe to try use the zlib1.dll which in same folder? Thanks.

**Comment by GuillaumeGomez** [comment]
cc @gkoz

**Comment by GuillaumeGomez** [comment]
But from what I read, the zlib lib missing.

**Comment by ScottHuangZL** [comment]
@GuillaumeGomez I think that is zlib1 version different, in windows 64 bit system, there are 2 folders, one is system 32, the other is sysWOW64, I think our GTK sample try to connect 32bit zlib1 and cause error, once I replace it with 64bit, it resolved.

**Comment by gkoz** [comment]
I believe you should not touch any files in `system32` and similar directories. How did zlib1.dll get there?

**Comment by ScottHuangZL** [comment]
May be myself put zlib1.dll into system32 long time ago.  :)
You can close this issue now, I got your link to donwload gtk3 windows 64 run time libs already. Thanks.
