### ISSUE TITLE
Why `Builder::new_from_string` does fail ?

### ISSUE THREAD

**Issue by Boiethios** [gtk-rs/gtk#362]
I tried this example:

```
extern crate gtk;

use gtk::Builder;
use gtk::prelude::*;

fn main() {
	if gtk::init().is_err() {
		println!("Failed to initialize GTK.");
		return;
	}
	let builder = Builder::new_from_string(include_str!("../win.glade"));
	let window: gtk::Window = builder.get_object("mainwindow").unwrap();
	
	window.show_all();
	gtk::main();
}
```

and got this error:

> ```
src/main.rs:15:16: 15:40 error: no associated item named `new_from_string` found for type `gtk::Builder` in the current scope
src/main.rs:15 	let builder = Builder::new_from_string(include_str!("../win.glade"));
               	              ^~~~~~~~~~~~~~~~~~~~~~~~
src/main.rs:17:28: 17:60 error: the type of this value must be known in this context
src/main.rs:17 	let window: gtk::Window = builder.get_object("mainwindow").unwrap();
```

Why this function is no more available?

**Comment by GuillaumeGomez** [comment]
Because of this line: https://github.com/gtk-rs/gtk/blob/master/src/builder.rs#L46

**Comment by Boiethios** [comment]
This line disable this function? But why? It is a useful one.

**Comment by GuillaumeGomez** [comment]
It depends what feature you activated. By default, the activated feature is "v3_4", so this function isn't available. If you want to activate it, you must build with "v3_10".

**Comment by Boiethios** [comment]
Ok, I added those lines in my `Cargo.toml`:

```
[features]
#default = ["gtk_3_18"]
gtk_3_10 = ["gtk/v3_10"]
gtk_3_16 = ["gtk_3_10", "gtk/v3_16"]
gtk_3_18 = ["gtk_3_16"] #for CI tools
```

found there https://github.com/gtk-rs/examples/blob/master/Cargo.toml but that did not work.

(Sorry, I am beginning in rust and I do not understand that concept. It is very abstract for me…)

**Comment by GuillaumeGomez** [comment]
The issue here isn't rust but cargo and gtk. First, check what version of gtk you have on your computer:

```bash
> dpkg -l | grep libgtk-3-dev
ii  libgtk-3-dev:amd64                    3.14.5-1+deb8u1                      amd64        development files for the GTK+ library
```

In my case, this is the 3.14, so I can use the `v3_14` feature. To activate your version in your project, you can just put in your `Cargo.toml`:

```toml
[features]
default = ["gtk/v3_10"] # in case your version is 3.10
```

If you have an older version, you won't be able to use this method and will have to use another one. So `Builder::new` followed by [`Builder::add_string`](https://github.com/gtk-rs/gtk/blob/master/src/builder.rs#L85).

**Comment by EPashkin** [comment]
Seems `#default` in examples need additional comment "Uncomment to build with gtk 3.18."

**Comment by GuillaumeGomez** [comment]
@EPashkin: We should really finish the gtk tutorial. This part is a bit difficult to understand for newcomers.

**Comment by Boiethios** [comment]
I have gtk 3.20. Thank you, it worked with those lines!

```
[features]
default = ["gtk/v3_10"] # in case your version is 3.10
```

And thank you for spending time doing this good job!
