### ISSUE TITLE
Is there any way to disconnect event handlers?

### ISSUE THREAD

**Issue by eeeeeta** [gtk-rs/gtk#363]
From what I can see, the only things the API exposes to do with event handlers currently are the `connect_` methods on `gtk::WidgetExt` - is there a way to *disconnect* event handlers?

The reason I ask is the following: when calling `destroy()` on a widget, GTK fires the focus-out event for the widget - which interrupts my program's flow and ends up borrowing a `Rc<RefCell<T>>` that is currently in use, because it's part of the code calling `destroy()`. Is there any remedy for this situation, for example blocking signal handlers for a brief period?

**Comment by GuillaumeGomez** [comment]
@susurrus is adding it it seems. Take a look [here](https://github.com/gtk-rs/glib/issues/133).

**Comment by eeeeeta** [comment]
@GuillaumeGomez Ah, I see. Great! I've subscribed to that issue, so I'll close this one.

**Comment by gkoz** [comment]
There is an unsafe way but we haven't made it available as a safe one.

Ideally [`RefCell::try_borrow`](https://github.com/rust-lang/rfcs/pull/1660) would make this unnecessary but it doesn't exist yet. Also note that if you can use `Cell` instead it doesn't have such a limitation.

Consider also `WidgetExt::in_destruction`.

**Comment by eeeeeta** [comment]
@gkoz I implemented a workaround with `RefCell::borrow_state` (subscribed to that issue for updates on stability) - sadly in_destruction doesn't seem to work for me :( How would one go about getting the IDs to pass to `g_signal_handler_disconnect`?

**Comment by gkoz** [comment]
The `connect_` methods return the handler ids.
