### ISSUE TITLE
Implement Debug for simple struct types

### ISSUE THREAD

**Issue by evmar** [gtk-rs/gtk#364]
It'd be really nice to be able to `println!("{:?"})` types like `cairo::FontExtents`.

**Comment by GuillaumeGomez** [comment]
Why not. I'll try to do something like this.

**Comment by evmar** [comment]
Hopefully it's enough to ![derive(Debug)].

**Comment by GuillaumeGomez** [comment]
I just checked, you can already do it. It can be closed then!
