### ISSUE TITLE
Is it desireable and possible to decrease the reference count of GtkListStore?

### ISSUE THREAD

**Issue by plerg** [gtk-rs/gtk#365]
Hello,
Sorry if this is stupid question, but I am not so skilled to figure it out myself.
I wanted to write simple program using GtkTreeView with GtkListStore corresponding respectively to gtk::TreeView and gtk::ListStore.
In tutorial/guide for GTK+:
https://en.wikibooks.org/wiki/GTK%2B_By_Example/Tree_View/Columns_and_Renderers
there is an example C program using GtkTreeView and GtkListStore.
There is a line of code:
g_object_unref(model);
I would like to know if there is a function/method in gtk-rs bindings to be used by programmer using bindings? Or is it automatically done under the hood by bindings?

**Comment by GuillaumeGomez** [comment]
Done under the hood. To put it simply: when an object is destroyed, we call this function.

**Comment by plerg** [comment]
"When an object is destroyed", does it mean that variable is going out of scope?
Like in this example with variable model_list_of_data?
```
    let box_container = Box::new(Orientation::Vertical,0);
    let view_list = TreeView::new();
    {
        let model_list_of_data = ListStore::new(types_inside_columns);
        view_list.set_model(Some(&model_list_of_data));
    }
    box_container.pack_start(&view_list,false,false,0);
```
If yes, I know everything I want. I think issue can be closed. Thanks for help and for your work on bindings.

**Comment by GuillaumeGomez** [comment]
Absolutely. Like in your example with `model_list_of_data`.
