### ISSUE TITLE
GdkWindowAttr optional fields

### ISSUE THREAD

**Issue by aeosynth** [gtk-rs/gtk#366]
https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#GdkWindowAttributesType

> Fields in GdkWindowAttr not covered by a bit in this enum are required

conversely, fields in the enum are optional

**Comment by gkoz** [comment]
I don't follow.

**Comment by GuillaumeGomez** [comment]
Me neither.

**Comment by aeosynth** [comment]
sorry, i'm new to rust - i'd like to create a struct without setting all of the fields:

```rust
extern crate gdk_sys;

fn main() {
  let attributes = gdk_sys::GdkWindowAttr{
    event_mask: 0,
    width: 800,
    height: 600,
    wclass: gdk_sys::GdkWindowWindowClass::InputOutput,
    window_type: gdk_sys::GdkWindowType::Toplevel
  };
}
```

```
$ cargo run
   Compiling rust v0.1.0 (file:///home/james/src/test/rust)
src/main.rs:4:20: 4:42 error: missing fields `title`, `wmclass_name`, `visual`, `cursor`, `type_hint`, `x`, `wmclass_class`, `y`, `override_redirect` in initializer of `gdk_sys::GdkWindowAttr` [E0063]
src/main.rs:4   let attributes = gdk_sys::GdkWindowAttr{
                                 ^~~~~~~~~~~~~~~~~~~~~~
src/main.rs:4:20: 4:42 help: run `rustc --explain E0063` to see a detailed explanation
error: aborting due to previous error
error: Could not compile `rust`.
```

the missing fields are optional. the equivalent c code works fine.

**Comment by EPashkin** [comment]
Seems we forgot to implement `Default` for `gdk::Attributes` (better use it instead of `gdk_sys::GdkWindowAttr`).
@aeosynth, IMHO your values good as default with adding only `override_redirect=false`
@gkoz, what you think?

**Comment by aeosynth** [comment]
i didn't know `gdk::Attributes` existed, does it have docs? `Gdk::Window::new` mentions `WindowAttr` without a link.

`override_redirect` is optional; i assume gdk already treats it as default false

**Comment by gkoz** [comment]
Oops looks like the `Attributes` struct has bitrotten slightly -- it should be named `WindowAttr` and reexported along with `Window` (https://github.com/gtk-rs/gdk/issues/126). I'm not sure we can implement `Default` for it, there're a lot of non-optional fields.

**Comment by aeosynth** [comment]
could make everything optional, with above values as defaults

**Comment by EPashkin** [comment]
@aeosynth, in rust IMHO you can't add default values for some struct's fields, but can make default value for struct itself via [Default trait](https://doc.rust-lang.org/std/default/trait.Default.html)
Example (after #127 merged):
```rust
let attrs = gdk::WindowAttr {
    event_mask: 0,
    width: 800,
    height: 600,
    wclass: gdk::WindowWindowClass::InputOutput,
    window_type: gdk::WindowType::Toplevel,
    ..Default::default()
};
let gdkwin = gdk::Window::new(None, &attrs);
```

**Comment by aeosynth** [comment]
neat. i'll close this in favor of the gdk repo issue/pr
