### ISSUE TITLE
Not able to retrieve elements out of a ListBox

### ISSUE THREAD

**Issue by miquelruiz** [gtk-rs/gtk#367]
I have a problem and I'm not sure if it's me not being able to figure it out, or an actual problem in the API:

I want to iterate over the rows of a ListBox, and then access the child of every ListBoxRow. To do that I use the method "get_children" on the ListBox, but that method returns a Vec<Widget>, which means I can not access the element inside the ListBoxRow because Widget does not implement BinExt.

Is there any way to access the child of the ListBoxRow's from a given ListBox? Any help will be very much appreciated. If this happen to be an issue in the API, I can work on a patch if you point me in the right direction.

**Comment by EPashkin** [comment]
You can use traits `glib::object::Cast`for converting `Widget` to `ListBoxRow`
It contains function `downcast` that convert any widget to needed class.
```
for wrow in list.get_children() {
   let row: ListBoxRow = wrow.downcast().unwrap();
   let inner = row.get_child().unwrap();
}
```
PS. May be you want change first `unwrap` to `match` if needed skip non-listboxrow children

**Comment by miquelruiz** [comment]
Perfect! this worked like charm :)
Thank you very much!
