### ISSUE TITLE
It's not possible to (safely) get the pressed button from an EventButton

### ISSUE THREAD

**Issue by Flakebi** [gtk-rs/gtk#368]
Hi, I didn't find a way to get the button from an `EventButton` (e.g. obtained by `connect_button_press_event`) without unsafe code.
`let button = unsafe { (*event.to_glib_none().0).button };` works for now, but it would be nice to have a safe method.

I use that code to create a popup menu with `popup_easy`, which takes the pressed button.

**Comment by EPashkin** [comment]
This count as unsafe?
```
let eb: gdk::EventButton = ...;
let state: gdk::ModifierType = eb.get_state();
let b: bool = state.contains(gdk::BUTTON1_MASK);
```

**Comment by Flakebi** [comment]
Hm, no that's not unsafe ;)
The modifier flags don't contain the button that created the event as far as I know, only buttons that were already pressed when the event occurs (so your check will succeed if you have button 1 pressed and then press button 2, the modifier for button 1 will be set in the second event).

**Comment by EPashkin** [comment]
`eb.as_ref().button` ?

**Comment by Flakebi** [comment]
Ah thanks, `as_ref` is a lot better than the code I used.
