### ISSUE TITLE
TextView's some signals don't emit

### ISSUE THREAD

**Issue by WinPooh32** [gtk-rs/gtk#369]
I'm trying to catch insert-at-cursor, preedit-changed signals, but nothing happens when I typing text into the TextView.
Other signals are working well, I tested some of them: move-cursor, delete-from-cursor and some other.

My code: 

```
    let text_view: TextView = builder.get_object("input_view").unwrap();
    let output_view: TextView = builder.get_object("output_view").unwrap();

    let tv_out = output_view.clone();
    text_view.connect_insert_at_cursor(move |_, _|{
        println!("INSERT EMIT");
        tv_out.get_buffer().unwrap().set_text("");
    });
```

**Comment by dessalines** [comment]
I noticed `text_view.connect_move_cursor(` also isn't firing any events.

**Comment by GuillaumeGomez** [comment]
That's weird... I'll try to take a look tomorrow.

**Comment by tmiasko** [comment]
This is similar to #553. The purpose of `insert-at-cursor` is to insert some
text at cursor position from key-bindings. You shouldn't connect to it in
general. Instead take a look and use signals and properties of `TextBuffer`.
