### ISSUE TITLE
unresolved import gtk::ListBox

### ISSUE THREAD

**Issue by timlyo** [gtk-rs/gtk#371]
For some reason I can't import `Listbox`. I have other parts working, so I've got everything installed correctly.

    use gtk::ListBox;

Results in

    error: unresolved import `gtk::ListBox`. There is no `ListBox` in `gtk

I'm probably doing something stupid, but I can't work out what it is.

**Comment by EPashkin** [comment]
Its ListBox
http://gtk-rs.org/docs/gtk/struct.ListBox.html

**Comment by timlyo** [comment]
Sorry mistyped the first one, I've got it as `ListBox` and it's still not finding it.

**Comment by EPashkin** [comment]
I forgot that it required feature `v3_10` in 'gtk'

**Comment by EPashkin** [comment]
You can enable in in cargo toml
```
[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"   //if latest version used 
features = ["v3_10"]
```

**Comment by timlyo** [comment]
That seems to be working. Thanks.

**Comment by wyq756543431** [comment]
why latest version lost this feature?

**Comment by GuillaumeGomez** [comment]
[It still has it](https://github.com/gtk-rs/gtk/blob/master/src/auto/list_box.rs) so what are you referring to?

**Comment by wyq756543431** [comment]
i want use listbox in lastest version, but listbox not in it, I can't import listbox!

**Comment by GuillaumeGomez** [comment]
What feature are you using in cargo? How are you importing `ListBox`?
