### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#372]
I'd like to push my GUI project up onto crates.io, but in order to do that all dependencies must be  available on crates.io. I depend on some `signal_*` functions that were added after the last release. Are there plans for a new release sometime soon? I don't know what's going on behind the scenes, but it'd be greatly appreciated at least for my use case (I don't know how involved a new release is, hopefully not much).

**Comment by GuillaumeGomez** [comment]
I'd like to release a new version but I'd prefer this version to contain the url doc thing I was working on but I need some news from @gkoz and @EPashkin.

**Comment by aeosynth** [comment]
Bump. Gtk 3.22 was released, and I'd like the new features documented (if we can use them at all).

**Comment by GuillaumeGomez** [comment]
We need to update the gir files, add a feature in Cargo.toml file and run gir and it should be done.
