### ISSUE TITLE
failed to run custom build command for `cairo-sys-rs v0.3.1`

### ISSUE THREAD

**Issue by hadrien-psydk** [gtk-rs/gtk#378]
Hi,

I am using Ubuntu 16.04 x64.

I followed the documentation at http://gtk-rs.org/ to build my first rust+gtk program: I added the three needed lines in Cargo.toml. However 'cargo build' gives me an error:

```
   Compiling gio v0.1.0
   Compiling c_vec v1.0.12
   Compiling gtk v0.1.0
   Compiling gdk-sys v0.3.1
   Compiling atk-sys v0.3.1
   Compiling gdk-pixbuf-sys v0.3.1
   Compiling cairo-rs v0.1.0
   Compiling gdk-pixbuf v0.1.0
   Compiling gdk v0.5.0
   Compiling bitflags v0.5.0
   Compiling cairo-sys-rs v0.3.1
failed to run custom build command for `cairo-sys-rs v0.3.1`
Process didn't exit successfully: `/home/hadrien/rust/dkalc/target/debug/build/cairo-sys-rs-f59614cd267c1996/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "cairo >= 1.10"` did not exit successfully: exit code: 1
--- stdout
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
```
Is there something missing in the documentation? I printed $PKG_CONFIG_PATH but it is empty.

**Comment by gkoz** [comment]
Do you have `libgtk-3-dev` installed as suggested [here](http://gtk-rs.org/docs/requirements.html)?

**Comment by hadrien-psydk** [comment]
> Do you have libgtk-3-dev installed as suggested here

Thank you gkoz, it worked. I got confused between the documentation on the home page and the documentation at http://gtk-rs.org/docs/ which is more complete.
