### ISSUE TITLE
Remove `get_` prefixes on getters?

### ISSUE THREAD

**Issue by frewsxcv** [gtk-rs/gtk#379]
https://aturon.github.io/style/naming/README.html#getter/setter-methods-[rfc-344]

Idiomatic Rust doesn't have `get_` prefixed names on getters. It'd be nice if the API didn't have the prefixes. If the prefixes intentionally exist to be me more similar to the native GTK API, that's understandable and you can can close this issue.

**Comment by GuillaumeGomez** [comment]
It's generated from gir files, we don't change functions' name. The goal is obviously to keep consistency with the gnome libraries and to make easier to read C code and translate it into rust code.
