### ISSUE TITLE
Implement IsA<Widget> for widgets of external crate

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gtk#380]
Hello.
I am currently trying to create a binding for webkit2: I have a working application showing a `WebView`, but I was unable to make `WebView` implement `IsA<Widget>` which makes the widget annoying to use.
The problem, I think, is that I cannot implement `IsA<Widget>` for a widget in another crate.
If I do the following:
```rust
glib_wrapper! {
    pub struct WebView(Object<ffi::WebKitWebView>): Widget;

    match fn {
        get_type => || ffi::webkit_web_view_get_type(),
    }
}
```
I get the following error:
```
error[E0119]: conflicting implementations of trait `glib::translate::ToGlibPtr<'_, *mut ffi::WebKitWebView>` for type `auto::web_view::WebView`:
  --> src/auto/web_view.rs:36:1
   |
36 | glib_wrapper! {
   | ^
   | |
   | first implementation here
   | conflicting implementation for `auto::web_view::WebView`
   |
   = note: this error originates in a macro from the standard library
```
Currently, I use a `widget()` method to get the actual `Widget`:
```rust
impl WebView {
    pub fn widget(&self) -> Widget {
       unsafe {
           from_glib_none(self.0.to_glib_none().0 as *mut GtkWidget)
       }
    }
}
```
but it is awkward to use.

So, how can I create a binding for a `Widget` in another Gtk+ based library?

Thanks.

**Comment by EPashkin** [comment]
Can show more code?

**Comment by gkoz** [comment]
You need the expanded syntax documented at the bottom here: http://gtk-rs.org/docs/glib/macro.glib_wrapper!.html#object

**Comment by antoyo** [comment]
@gkoz Thank you!
@EPashkin I will post the code on my GitHub soon.

By the way, do you prefer to include my work on the `webkit2` binding in this organization or is it okay if I upload the crates myself?

**Comment by gkoz** [comment]
It'd be nice to have them under this organization eventually but it's fine to start with separate repos. Please try to take advantage of code generation rather than coding everything by hand.

**Comment by antoyo** [comment]
OK, I made a [repository here](https://github.com/antoyo/webkit2-rs).
I used the code generation, but I hade to do manual edits (that I put in other commits).
Any feedback is appreciated!

**Comment by gkoz** [comment]
The generator should have done the right thing here. It's possible you need to adjust the config a little. It's also a good idea to put the config in source control.
