### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gtk#381]
Hello.
I generated a WebKit binding, but [I had to do manual edits](https://github.com/gtk-rs/gtk/issues/380) on the generated code, which should not be the case.
I uploaded the configuration file that I used. Here they are:

https://github.com/antoyo/webkit2-rs/blob/master/gir/Gir_WebKit.toml
https://github.com/antoyo/webkit2-sys-rs/blob/master/conf/gir-webkit2.toml
https://github.com/antoyo/webkit2-sys-rs/tree/master/gir-files

Is there anything wrong in the configuration that cause this code generation issue?

Thanks for your help.

**Comment by gkoz** [comment]
The generator ignores classes by default so if there are external super-classes you need to include them in the config. For instance this hierarchy

```
    GObject
    ╰── GInitiallyUnowned
        ╰── GtkWidget
            ╰── GtkContainer
                ╰── WebKitWebViewBase
                    ╰── WebKitWebView
```

means adding 

```
manual = [
    Gtk.Container,
    Gtk.Widget,
    GObject.Object,
]
```

(`InitiallyUnowned` we ignore). I'd also add `GLib.Error` used for error handling.

---

A GTK+ widget crate should have `generate_safety_asserts = true` option set, which requires a bit of manual work. Perhaps we should export [these macros](https://github.com/gtk-rs/gtk/blob/master/src/rt.rs#L21).

---

Editing generated files may make regenerating unnecessarily difficult and error-prone. What we do here is take advantage of multiple inherent `impl` sections being allowed ([like this](https://github.com/gtk-rs/gtk/blob/master/src/message_dialog.rs)) or in the trait case making a [second trait](https://github.com/gtk-rs/gtk/blob/master/src/widget.rs). Thus the files in `mod auto` are just a function of the config, gir-files, and gir revision; they can always be deleted and recreated safely.

**Comment by antoyo** [comment]
Thanks for your answer.

[I still have some manual edits to do](https://github.com/antoyo/webkit2-rs/commit/6c50114b596ff31d839638e5960b57708e754165), though.
Do you know why there are these `use u64` (that triggers an unresolved import)?
There are also some missing `feature` attributes.

So, what do I need to do with the safety asserts since the macro are not exported?
Will you update the code in the `gtk` crate to export them?

Thanks.

**Comment by gkoz** [comment]
> Do you know why there are these use `u64` (that triggers an unresolved import)?

Looks like a bug in `gir`, perhaps it doesn't know `u64` doesn't need to be imported.

> There are also some missing feature attributes.

Looks like the signals which reference `NavigationAction` don't carry appropriate `version` annotations and need that version supplied in the config. Something like

```toml
[[object]]
name = "WebKit.WebView"
status = "generate"
    [[object.signal]]
    name = "create"
    version = "2.6"
```

The import should become conditional then.

> So, what do I need to do with the safety asserts since the macro are not exported? Will you update the code in the gtk crate to export them?

Let's start by copying the macros (I believe all functions they use are public) to your crate and see how it goes.

**Comment by antoyo** [comment]
Thanks for your quick answer!

I added the following (and remove `WebKit2.WebView` in the `generate` array):
```toml
[[object]]
name = "WebKit2.WebView"
status = "generate"
    [[object.signal]]
    name = "create"
    version = "2.6"
```
(with the missing `2` after `WebKit`)
But, the `feature` attribute is still missing.

Am I using the right syntax?

Moreover, the [`rt` module is private](https://github.com/gtk-rs/gtk/blob/master/src/lib.rs#L187), so I cannot use it for the `assert_initialized_main_thread` macro.

**Comment by EPashkin** [comment]
Seems no `min_cfg_version = "2.0"` (or other sane value) in `options`, see https://github.com/gtk-rs/gtk/blob/master/Gir.toml

**Comment by gkoz** [comment]
> Moreover, the rt module is private, so I cannot use it for the assert_initialized_main_thread macro.

Public items from `rt` [get reexported](https://github.com/gtk-rs/gtk/blob/master/src/lib.rs#L225) at the top level.

**Comment by EPashkin** [comment]
About version: seems `min_cfg_version` don't help, as config info unused :cry: 
Compare https://github.com/gtk-rs/gir/blob/master/src/analysis/signals.rs#L48 and 
https://github.com/gtk-rs/gir/blob/master/src/analysis/functions.rs#L70-L71

**Comment by antoyo** [comment]
Thanks to both of you!

I have macros working and the attributes are not generated.

Now, with this [pull request](https://github.com/gtk-rs/gir/pull/274), I believe the code generation for webkit will not require manual edits.

**Comment by antoyo** [comment]
With the previously mentionned pull request, I do not need any manual edits for webkit.

I added the macros [here](https://github.com/antoyo/webkit2-rs/blob/master/src/lib.rs#L13).
Could you export them so that I don't need to copy them (that will probably needs some updates to the macros themselves so that they work in another crate)?

Besides that, I think this issue is fixed.

Thanks.

**Comment by antoyo** [comment]
I think I found another bug.
I added the missing enums to the config file and I had to do [these manual edits](https://github.com/antoyo/webkit2-rs/commit/683ac43c9d18dcb1b672784efbd9f4b2017b685d).
Thanks.

**Comment by EPashkin** [comment]
Maybe something wrong with you `WebKit2-4.0.gir` xml.
This string go almost directly from `glib:error-domain`
```
    <enumeration name="FileChooserError"
                 glib:type-name="GtkFileChooserError"
                 glib:get-type="gtk_file_chooser_error_get_type"
                 c:type="GtkFileChooserError"
                 glib:error-domain="gtk-file-chooser-error-quark">
```

**Comment by antoyo** [comment]
Thanks @EPashkin!
I've fixed the strings in the gir file.

**Comment by EPashkin** [comment]
@antoyo, now you can remove manual changes from `WebKit2-4.0.gir`
