### ISSUE TITLE
Custom widget

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gtk#382]
Hello.
I wonder how to create a custom widget with this crate.

In C++, for instance, I would create a class deriving from a `gtk::Widget`.

[Here is what I do, now.](https://github.com/antoyo/mg/blob/master/src/status_bar.rs)
It is a bit annoying because I have to use the `widget()` method.

I looked at other gtk-rs based projects and I found [this](https://github.com/GuillaumeGomez/process-viewer/blob/5d29b2223d7a587ac162187100d957ebc8f6916e/src/notebook.rs) which uses a similar approach (using the attribute directly instead of a method like me).

I wonder is there is a way to implement the `IsA<Widget>` trait for custom widgets like this.
It does not seem possible to the `glib_object_wrapper` macro, because it uses `self.0` and I prefer to use a struct than a tuple for custom widgets (and I don't even know if it makes sense to use this macro in this specific case).

Thanks for your help.

**Comment by gkoz** [comment]
We don't support subclassing currently. It is quite subtle and difficult to implement so there needs to be convincing motivation to go into that. If you manage to achieve your needs without `unsafe` it _probably_ doesn't justify adding that support.

It'd be valuable to know what you consider annoying or limiting. Some alternatives to `fn widget` could be implementing `AsRef<Widget>` or `Deref`. In some cases you might take advantage of objects implementing `Hash`.

**Comment by antoyo** [comment]
I tried using `Deref`, but it was not working. I found out it is because I needed to use `&*widget` instead of `&widget`.

I managed to create the required implementations and [I wrote a macro to make it easier to use](https://github.com/antoyo/mg/blob/master/src/widget.rs#L23).

**Comment by gkoz** [comment]
I don't get it, this is better than forcing a deref with `&*`?
`&*foo` (along with `&foo[..]`) is a relatively idiomatic coercion tool while that collection of impls is scary.

**Comment by antoyo** [comment]
Well, it is not necessary better, but I feel like it is more consistent with the gtk widgets, where you only need to use `&widget`.

**Comment by myfreeweb** [comment]
[gnome-class](https://gitlab.gnome.org/federico/gnome-class/) should handle this eventually

**Comment by jacobzimmermann** [comment]
I was wondering about the same thing and eventually got it to work using Deref. It's actually very easy. You can have a look at https://github.com/jacobzimmermann/rs-lines.

NB: of course there may be better ways to do it.
