### ISSUE TITLE
How to use Pixbuf::new_from_vec?

### ISSUE THREAD

**Issue by Eilie** [gtk-rs/gtk#388]
Hello,

From where do I get the arguments for this function?
Signature is: `fn new_from_vec(vec: Vec<u8>, colorspace: Colorspace, has_alpha: bool, bits_per_sample: i32, width: i32, height: i32, row_stride: i32) -> Pixbuf` but the only arguments I understand is `width` and `height`. Could you please explain the rest?
For example I have a byte vector from png image(100 width, 150 height) with transparency.

**Comment by EPashkin** [comment]
Seems something like this:
1. Load file with `cairo::ImageSurface::create_from_png`.
2. Get `get_stride` from surface.
3. Create `cairo::ImageSurfaceData` from surface via `ImageSurfaceData::new` or `ImageSurface::get_data`
4. `let bits_per_sample=8;` Only this supported by gtk-pixbuf.
5. Call `new_from_vec`
But IMHO simpler
1. Use `PixbufLoader::new_with_type("png")` or `PixbufLoader::new_with_mime_type("image/png")`
2. Write file data with `loader_write`
3. `close` loader
4. `get_pixbuf`
