### ISSUE TITLE
[GTK4] support

### ISSUE THREAD

**Issue by alex285** [gtk-rs/gtk#389]
Hello, 
do you plan to create GTK 4 bindings after GTK 3.90 release, or will be a branch following GTK 4 development?

**Comment by gkoz** [comment]
We don't have any specific plans for GTK 4 and I'm not sure there's enough information to plan anything at this point. Personally, I'd give them time to make all the breaking changes first and look into this closer to the stable 4.6 release. 3.90 doesn't seem like an interesting target to me. Regrettably, we haven't even embraced 3.18-3.22 yet.

**Comment by alex285** [comment]
@gkoz The stable release will be GTK 4.0 not 4.6. I think it will be 3.90, 3.92, 3,94 and the stable 4.0, but it 4.0 maybe happen after 3.92.

**Comment by gkoz** [comment]
Has anything changed since ["Gtk 4.0 is not Gtk 4"](https://blogs.gnome.org/desrt/2016/06/13/gtk-4-0-is-not-gtk-4/)?

**Comment by alex285** [comment]
@gkoz Yes, here is the latest. latest I think
https://blog.gtk.org/2016/09/01/versioning-and-long-term-stability-promise-in-gtk/

**Comment by gkoz** [comment]
Thanks for the link, I wasn't aware of that change. Putting aside version number specifics, the stable release still isn't on the roadmap and targeting unstable ones doesn't feel like a priority.

**Comment by alex285** [comment]
@gkoz Technically 3.9x isn't unstable, it is not a stable API, similar to the whole 3.xx cycle anyway. For example GNOME will update their apps on 3.9x.

The point of 4.0 is a stable API and LTS, and then it will be GTK 5.0

**Comment by GuillaumeGomez** [comment]
Well, on most distribution, it still GTK 3.x and I don't think they'll switch anytime soon unfortunately.

**Comment by alex285** [comment]
@GuillaumeGomez They wont switch. GTK3 and GTK4 play in parallel, there are different headers. Fedora (26) and Arch for sure will ship GTK4 when GNOME 3.24 is out. It is like dependency :)

**Comment by GuillaumeGomez** [comment]
Oh, I see. My bad, I thought it was the next "step".

**Comment by alex285** [comment]
@GuillaumeGomez I have some comments from developers about GTK4 porting here
https://plus.google.com/+WorldofGnomeOrg/posts/FbtcRMHuJny

And this video shows GTK4 running together with GTK3 on JHBuild, which is exactly like /usr enviroment
https://www.youtube.com/watch?v=mq5JiY_W2N0

**Comment by dariost** [comment]
Any updates on this now that [Gtk+ 3.90](https://git.gnome.org/browse/gtk+/tag/?h=3.90.0) has been released?

**Comment by GuillaumeGomez** [comment]
@dariost: Absolutely not. I'll need to check this out.
