### ISSUE TITLE
connect_*: allow callbacks of non-static lifetime

### ISSUE THREAD

**Issue by Nervengift** [gtk-rs/gtk#390]
As far as I can tell the ```'static``` lifetime for the function arguments of all ```connect_*``` functions (e.g. ```DrawingArea::connect_draw(…)```) is not really needed. Having a non-static lifetime would make it possible to use closures or methods on non-static objects as callbacks.

For reference: http://stackoverflow.com/questions/35651279/error-closure-may-outlive-the-current-function-but-it-will-not-outlive-it

**Comment by gkoz** [comment]
This has been discussed in #263, in particular consider the basic example

```rust
let button = gtk::Button::new();
button.connect_clicked(|_| { /* this closure outlives any 'a */ });
mem::forget(button);
```

If you come up with a specific way to solve this please share it.
