### ISSUE TITLE
Child properties

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gtk#392]
As mentioned in https://github.com/gtk-rs/gir/issues/287 gir can't generate child properties, but we can do it manually with using `gtk_container_child_g[s]et_property`.
This is tracking issue.

Classes with child properties.
- [x] [GtkActionBar](https://developer.gnome.org/gtk3/stable/GtkActionBar.html)
- [x] [GtkAssistant](https://developer.gnome.org/gtk3/stable/GtkAssistant.html) added without deprecated in 3.2 `header-image` and `sidebar-image`
- [x] [GtkButtonBox](https://developer.gnome.org/gtk3/stable/GtkButtonBox.html) already has functions
- [x] [GtkBox](https://developer.gnome.org/gtk3/stable/GtkBox.html) only need position
- [x] [GtkFixed](https://developer.gnome.org/gtk3/stable/GtkFixed.html)
- [x] [GtkGrid](https://developer.gnome.org/gtk3/stable/GtkGrid.html)
- [x] [GtkHeaderBar](https://developer.gnome.org/gtk3/stable/GtkHeaderBar.html)
- [x] [GtkLayout](https://developer.gnome.org/gtk3/stable/GtkLayout.html)
- [x] [GtkMenu](https://developer.gnome.org/gtk3/stable/GtkMenu.html)
- [x] [GtkNotebook](https://developer.gnome.org/gtk3/stable/GtkNotebook.html) already has functions 
- [x] [GtkOverlay](https://developer.gnome.org/gtk3/stable/GtkOverlay.html) has gtk_overlay_get_overlay_pass_through, only needed index
- [x] [GtkPaned](https://developer.gnome.org/gtk3/stable/GtkPaned.html)
- [x] [GtkPopoverMenu](https://developer.gnome.org/gtk3/stable/GtkPopoverMenu.html)
- [x] [GtkStack](https://developer.gnome.org/gtk3/stable/GtkStack.html)
- [x] [GtkToolbar](https://developer.gnome.org/gtk3/stable/GtkToolbar.html) [PR](https://github.com/gtk-rs/gtk/pull/399)
- [x] [GtkToolItemGroup](https://developer.gnome.org/gtk3/stable/GtkToolItemGroup.html) only has position, need all other [PR](https://github.com/gtk-rs/gtk/pull/394)
- [x] [GtkToolPalette](https://developer.gnome.org/gtk3/stable/GtkToolPalette.html) already has functions

**Comment by GuillaumeGomez** [comment]
Starting with `ToolItemGroup` then.

**Comment by EPashkin** [comment]
I'm add `GtkGrid` example and test child properties on it.

**Comment by EPashkin** [comment]
Interesting fact: `left-attach` and `left_attach` works in `gtk_container_child_get_property`, so we can make it `ident` in macro and convert it to string with `stringify!` when use as parameter.

**Comment by EPashkin** [comment]
Interesting fact: `left-attach` and `left_attach` works in `gtk_container_child_get_property`, so we can make it `ident` in macro and convert it to string with `stringify!` when use as parameter. This way we guarantee that property name is string.

**Comment by EPashkin** [comment]
Seems we can't detect that child not belong to container by result of `gtk_container_child_get_property`.
I changed function for return `Option<i32>`
```rust
    pub fn get_child_height<T: IsA<Widget>>(&self, child: &T) -> Option<i32> {
        let mut value = Value::from(&-1);
        unsafe { ffi::gtk_container_child_get_property(self.to_glib_none().0,
                                                       child.to_glib_none().0,
                                                       "height".to_glib_none().0,
                                                       value.to_glib_none_mut().0); }
        value.get::<i32>()
    }
 ```
and if I pass not child, then I get warning and `Some(0)`
```
(grid.exe:8084): Gtk-WARNING **: gtkgrid.c:318: invalid child property id 4 for "height" of type 'GParamInt' in 'GtkGrid'
```

**Comment by GuillaumeGomez** [comment]
Hum, strange...

**Comment by GuillaumeGomez** [comment]
I just thought: shouldn't you enforce `T` with `IsA<Whatever>` in addition to `IsA<Widget>`?

**Comment by EPashkin** [comment]
Runtime checking slows call. And seems we don't have normal way checking it.

**Comment by GuillaumeGomez** [comment]
So we have to believe that users will know what they're doing. In worst case, gtk, will just send an error as usual.

**Comment by EPashkin** [comment]
IMHO better way just check TODO and reference this PR in other (not add reference to other), this way status of PR's can be seen.

**Comment by GuillaumeGomez** [comment]
Works as well. I don't have preference on this matter so I'll do it this way from now on.

**Comment by EPashkin** [comment]
@GuillaumeGomez, maybe simpler add properties to `Gir.toml` and generate?
```
[[object]]
name = "Gtk.Grid"
status = "generate"
    [[object.child_prop]]
    name = "height"
    type = "gint"
    [[object.child_prop]]
    name = "width"
    type = "gint"
    [[object.child_prop]]
    name = "left-attach"
    type = "gint"
    [[object.child_prop]]
    name = "top-attach"
    type = "gint"
```

**Comment by GuillaumeGomez** [comment]
I didn't ok this way. However, it also means that at every gir update, we'll have to check/update them as well, no?

**Comment by EPashkin** [comment]
I mean that it will be added to normal `src/auto/grid.rs`

**Comment by GuillaumeGomez** [comment]
Yes, and 'm worried that we won't be able to use gnome's gir files just like that anymore.

**Comment by EPashkin** [comment]
Sorry, don't understand why :(

**Comment by GuillaumeGomez** [comment]
Hum, let me try to explain what I have in mind:

For now, the objects properties aren't in gir files if I'm not mistaking. Since we take these gir files from gnome, it means that every gir file updates we'll have to add again these objects properties, no?

**Comment by EPashkin** [comment]
How child properties, added one time in `Gir.toml`, and updating `Gtk-3.0.gir` linked?

**Comment by GuillaumeGomez** [comment]
Arf, my bad, I got confused. Nevermind then, this is a great idea! Sorry for the confusion...

**Comment by EPashkin** [comment]
Then I try do it on Saturday.
I forgot about child type:
```
[[object]]
name = "Gtk.ToolItemGroup"
status = "generate"
child_type = "ToolItem"
...
```

**Comment by GuillaumeGomez** [comment]
Great, can't wait to see it! :)

**Comment by EPashkin** [comment]
@GuillaumeGomez, can you add `GtkAssistant`?
It has untested child property types (Object, string, enum), and important `gtk_assistant_set_forward_page_func` that not generated and need be done manually.
Also may be add example with it and using child props and `gtk_assistant_set_forward_page_func`?

**Comment by GuillaumeGomez** [comment]
Today and tomorrow will be difficult since I'll be on a flight coming back and then I'll have the jetlag. I can try on sunday but don't hope too much. ;)

**Comment by EPashkin** [comment]
Only if you will have free time, it not that important.

**Comment by GuillaumeGomez** [comment]
Don't worry, I'll do it as soon as I have time.

**Comment by EPashkin** [comment]
I done generating string, but not tested, that it really works.
Seems `GtkAssistant`'s pixbufes deprecated since 3.2 and no other `Object` properties, so only last not generated is enums.

**Comment by EPashkin** [comment]
Added enum properties generation by transmuting it to `i32`, also not tested

**Comment by EPashkin** [comment]
As all done, I close this Issue.
Only unfinished but not directly related to issue: need be added manual version of `gtk_assistant_set_forward_page_func`
