### ISSUE TITLE
Add set_ellipsize() method on Label

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gtk#396]
Hello.
Could you please add the [`set_ellipsize()`](https://developer.gimp.org/api/2.0/gtk/GtkLabel.html#gtk-label-set-ellipsize) method on the [`Label` widget](http://gtk-rs.org/docs/gtk/struct.Label.html)?
Thanks.

**Comment by GuillaumeGomez** [comment]
It seems you're referring to GTK2 whereas we target GTK3.

**Comment by antoyo** [comment]
No, it also works in GTK3: https://developer.gnome.org/gtk3/unstable/GtkLabel.html#gtk-label-set-ellipsize
This link was down a few minutes ago, it is why I posted the link from another source.

**Comment by GuillaumeGomez** [comment]
The strange thing is that FFI is present: http://gtk-rs.org/docs/gtk_sys/fn.gtk_label_set_ellipsize.html

Weird...

cc @gkoz @EPashkin

**Comment by antoyo** [comment]
I think it is because the `pango` wrapper does not have the type for `PangoEllipsizeMode`.

**Comment by GuillaumeGomez** [comment]
It does have it actually: http://gtk-rs.org/docs/pango_sys/enum.PangoEllipsizeMode.html

Strange things...

**Comment by antoyo** [comment]
No, I mean a wrapper like [`Align`](http://gtk-rs.org/docs/gtk/enum.Align.html) is a wrapper for [`GtkAlign`](http://gtk-rs.org/docs/gtk_sys/enum.GtkAlign.html).

**Comment by GuillaumeGomez** [comment]
Ah right. Only C stuff once again.

**Comment by EPashkin** [comment]
@antoyo IMHO it #498 fixed this

**Comment by antoyo** [comment]
Indeed, thanks.
