### ISSUE TITLE
Bug with libgtk --enable-debug detection, loading shared library through Nautilus

### ISSUE THREAD

**Issue by talklittle** [gtk-rs/gtk#405]
On Ubuntu 16.04, libgtk is built properly with default debug configuration (equivalent to `--enable-debug=minimum`). Verified by building the gtk-rs examples and running "basic" example, works fine, no panic.

It's kind of a strange bug to reproduce. I'm building [this Nautilus extension](https://github.com/talklittle/tmsu-nautilus-rs) on [this branch using Gtk-rs high-level wrapper](https://github.com/talklittle/tmsu-nautilus-rs/tree/gtk-high-level). Then copying the resulting shared library `.so` file to the system Nautilus extensions directory.

When I run `nautilus` and call `gtk::init()` from a menu callback, it panics and claims that libgtk is built with `--enable-debug=no`. (and to see issue #270)

However, when I run `GTK_DEBUG=misc nautilus`, the same `gtk::init()` is successful, no panics.

Is there an issue with the libgtk debug detection in gtk-rs? Or does this suggest some other problem, perhaps with the way Nautilus was configured?

**Comment by talklittle** [comment]
Workaround:

```rust
fn init_gtk() {
    let mut argc = 0;
    unsafe {
        gtk_init(&mut argc, ptr::null_mut());
        gtk::set_initialized();
    }
}
```

**Comment by tmiasko** [comment]
It seems that initialization checks assume that the Rust code will be
responsible for initialization. Which means that in case of using gtk crate as
a library or a plugin in other application, they will fail and panic.

Sadly, there is no function to just check if Gtk+ is already initialized.

**Comment by sdroege** [comment]
There's `gtk::set_initialized()` now
