### ISSUE TITLE
Keyboard input not working in OSX bundles

### ISSUE THREAD

**Issue by languitar** [gtk-rs/gtk#408]
I have a simple program which only displays a single Entry. When invoked from the command line, I can enter text in that window. However, when bundled into an OSX application, normal letter keys do not work. Arrows, delete etc. still work.

When constructing a similar example using python, things work perfectly.

In order to "fake" bundle the app, I basically made this:
```
mkdir -p myapp.app/Contents/MacOS
cp mybinary myapp.app/Contents/MacOS/myapp
open myapp.app
```

**Comment by micahflee** [comment]
I can't reproduce this. I made a simple test app that includes a `gtk::Entry`, with a script to build an app bundle, and keyboard input works fine for me when running the app bundle: https://github.com/micahflee/rustywidgets

**Comment by sdroege** [comment]
This is a general GTK problem and not related to the bindings, so best discussed at https://discourse.gnome.org or reported at https://gitlab.gnome.org/GNOME/gtk/issues/new
