### ISSUE TITLE
Userdata with callbacks

### ISSUE THREAD

**Issue by psr31** [gtk-rs/gtk#412]
How can I pass some userdata into a callback? In C all the callbacks take a pointer to something that can be used as userdata, how can I do it in gtk-rs? Bit of a short question, hope I'm clear.

**Comment by EPashkin** [comment]
As you can create closure, you mostly don't need pass userdata directly.
But you need `move` cloned userdata to satisfy rust's borrow checker.
See https://github.com/gtk-rs/examples/blob/master/src/gtktest.rs#L89-L98 as example.
