### ISSUE TITLE
Rightclick on TreeView?

### ISSUE THREAD

**Issue by cars10** [gtk-rs/gtk#415]
Is it possible to connect to rightclick yet?

**Comment by EPashkin** [comment]
http://gtk-rs.org/docs/gtk/trait.WidgetExt.html#tymethod.connect_button_press_event ?
For connect examples you can look in https://github.com/gtk-rs/examples/tree/master/src

**Comment by cars10** [comment]
ConnectButtonPressEvent is good - it returns an `EventButton`. But how to check if the click was a rightclick? The documentation only mentions single, double and triple clicks, but no differention in left/right click.

**Comment by EPashkin** [comment]
It still not in doc's but http://gtk-rs.org/docs/gdk/struct.EventButton.html has method `pub fn get_button(&self) -> u32`

**Comment by cars10** [comment]
What would i need to import to make that work? I am getting `no method defined ..`

**Comment by EPashkin** [comment]
Strange, I must in crate `gdk = "0.5.1"`
You can also get it with `event.as_ref().button`

**Comment by EPashkin** [comment]
Maybe your `Cargo.lock` locked to `gdk = "0.5.0"` ?
