### ISSUE TITLE
How to bundle gtk for windows?

### ISSUE THREAD

**Issue by cars10** [gtk-rs/gtk#422]
Hi, the GTK docs say that (on windows) every application should bundle gtk completely. Is this possible with gtk-rs, and if so - how?

Note: see also the reddit thread, where apparently nobody knew the answer:
https://www.reddit.com/r/rust/comments/5ll0zg/gtkrs_how_to_bundle_gtk_for_windows/

**Comment by EPashkin** [comment]
For `x86_64-pc-windows-gnu` you just need ship these files from installed mingw64 with your program (tested on https://github.com/gtk-rs/examples repo)
```
share\glib-2.0\schemas\*
      icons\Adwaita\*
            hicolor\*
libatk-1.0-0.dll
libbz2-1.dll
libcairo-2.dll
libcairo-gobject-2.dll
libcairo-script-interpreter-2.dll
libepoxy-0.dll
libexpat-1.dll
libffi-6.dll
libfontconfig-1.dll
libfreetype-6.dll
libgcc_s_seh-1.dll
libgdk-3-0.dll
libgdk_pixbuf-2.0-0.dll
libgio-2.0-0.dll
libglib-2.0-0.dll
libgmodule-2.0-0.dll
libgobject-2.0-0.dll
libgraphite2.dll
libgtk-3-0.dll
libharfbuzz-0.dll
libiconv-2.dll
libintl-8.dll
libpango-1.0-0.dll
libpangocairo-1.0-0.dll
libpangoft2-1.0-0.dll
libpangowin32-1.0-0.dll
libpcre-1.dll
libpixman-1-0.dll
libpng16-16.dll
libstdc++-6.dll
libwinpthread-1.dll
zlib1.dll
```

**Comment by zmoazeni** [comment]
Hi there. I've stumbled my way into figuring out how to build with msys2/mingw64 and copy the necessary libs + assets.

However, I'd like a windows user to be able to double click on the .exe from the explorer and it _not_ also open the command prompt along with the gtk app. 

It seems it's doing that on both my test code and the stuff in that example repo. I could be entirely missing something obvious. Any ideas? I appreciate any help.

**Comment by zmoazeni** [comment]
Oh! I've found some tips on how to remove it.

* http://stackoverflow.com/a/34335140
* https://github.com/gtk-rs/gtk/issues/107#issuecomment-141487345

Sorry for the noise!

**Comment by EPashkin** [comment]
@zmoazeni, You don't need build msys2/mingw64, just install it (you do it for build anyway) and copy dlls from `%MSYS2_ROOT%\msys64\mingw64\bin\

**Comment by zmoazeni** [comment]
Right, I didn't mean that I was building msys2/mingw64. I just installed it.

I built some rust code using gtk-rs inside a mingw64 session.

**Comment by EPashkin** [comment]
I also windows\msys2 user and I install msys2 (with gtk libraries), and add `%MSYS2_ROOT%\msys64\mingw64\bin\`  to %PATH%.
After this I can use windows installed rustup with "-gnu" tool-chain to build gtk-rs applications without mingw64 session.

**Comment by Object905** [comment]
Note: now there is a `windows_subsystem` attribute implemented in 1.18 that works like this: 
```
#![windows_subsystem = "console"]
#![windows_subsystem = "windows"]
```

**Comment by phase** [comment]
>For x86_64-pc-windows-gnu you just need ship these files from installed mingw64

Where does one find these files online? I'm trying to bundle these up with my exe in my CI (AppVeyor) and I'd like it to happen during the build script.

When running my application on Windows, it says I'm missing:
```
libgdk-3-0.dll
libglib-2.0-0.dll
libgio-2.0-0.dll
libcairo-2.dll
```

Are the others `.dll`s you listed dependencies of the ones I'm listing?

**Comment by EPashkin** [comment]
Yes, but some of it may be don't needed if you don't use it (like libpangoxxx),
You can use http://www.dependencywalker.com/ to get full list

**Comment by phase** [comment]
![dependencies](https://i.imgur.com/cbedOaf.png)

So where would a good spot to get these be? Can rustc add them to the build?

**Comment by EPashkin** [comment]
You can ask Appveyor to copy dlls from its mingw64 install folder with your binaries

**Comment by phase** [comment]
```
C:\msys64\mingw64\bin\libcairo-2.dll
C:\msys64\mingw64\bin\libgdk-3-0.dll
C:\msys64\mingw64\bin\libgio-2.0-0.dll
C:\msys64\mingw64\bin\libglib-2.0-0.dll
C:\msys64\mingw64\bin\libgobject-2.0-0.dll
C:\msys64\mingw64\bin\libgtk-3-0.dll
C:\msys64\mingw64\bin\libpango-1.0-0.dll
```
found the file paths if anyone needs them

**Comment by phase** [comment]
So the amount of dlls needed ramped up real quick once I tried to run it.

```
libatk-1.0-0.dll*        libexpat-1.dll*       libgdk_pixbuf-2.0-0.dll*  libgobject-2.0-0.dll*  libpangocairo-1.0-0.dll*  libpng16-16.dll*
libbz2-1.dll*            libffi-6.dll*         libgdk-3-0.dll*           libgraphite2.dll*      libpangoft2-1.0-0.dll*    libstdc++-6.dll*
libcairo-2.dll*          libfontconfig-1.dll*  libgio-2.0-0.dll*         libgtk-3-0.dll*        libpangowin32-1.0-0.dll*  zlib1.dll*
libcairo-gobject-2.dll*  libfreetype-6.dll*    libglib-2.0-0.dll*        libharfbuzz-0.dll*     libpcre-1.dll*            
libepoxy-0.dll*          libfribidi-0.dll*     libgmodule-2.0-0.dll*     libpango-1.0-0.dll*    libpixman-1-0.dll*
```

and I'm also getting GTK errors saying that I'm missing `pngs`

```
(sbrx.exe:12420): Gtk-WARNING **: 20:52:39.718: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(sbrx.exe:12420): Gtk-WARNING **: 20:52:39.718: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

**Comment by EPashkin** [comment]
As I remember icons stored in msys64\mingw64\share\icons\Adwaita\ (33Mb with all sizes)

**Comment by reduz** [comment]
@phase , @EPashkin: Have the same problem, how do you copy the icons to the project folder? Just copying these folders as-is does not seem to work. More information would be appreciated.

**Comment by EPashkin** [comment]
As I remember, \bin with exe and dlls and \share\icons\Adwaita with icons
See more in Packaging section of https://gtk-rs.org/docs-src/tutorial/cross

**Comment by reduz** [comment]
oh thanks, I was missing the bin/ directory for the executable, works fine now!

**Comment by shadiakiki1986** [comment]
For future-comers, I was having the same issue as `phase` getting the below error about png

```
(sbrx.exe:12420): Gtk-WARNING **: 20:52:39.718: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

What fixed it for me was to create a `lib` folder at the same level as `bin` and `share`, and copy the gdk-pixbuf library to it as follows:

```
GTK_INSTALL_PATH=/c/msys64/mingw64
cp -r $GTK_INSTALL_PATH/lib/gdk-pixbuf-2.0/ wherever/release/lib/
```
This is in addition to the rest of the instructions at https://gtk-rs.org/docs-src/tutorial/cross

What helped me figure it out was the use of `strace target/release/myprogram.exe` with and without having the `libgdk_pixbuf-2.0-0.dll` file at the same level as `myprogram.exe`. Then I compared both traces and saw that `C:\msys64\mingw64\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-png.dll` was missing when the `libgdk_pixbuf-2.0-0.dll` file was present (as opposed to being used from `/c/msys64/mingw64/bin/`

**Comment by sdroege** [comment]
This is a general GTK question and not related to the bindings, so best discussed at https://discourse.gnome.org
