### ISSUE TITLE
CellRendererMode::Editable, CellRenderer:mode etc. are mentioned in docs but don't exist?

### ISSUE THREAD

**Issue by oxeb** [gtk-rs/gtk#423]
I apologize if I am doing something massively wrong, but I am trying to create a TreeView with editable text cells.  The documentation says to use CellRenderer:mode and CellRendererMode::Editable and these symbols do not seem to exist.

The relevant documentation is here: http://gtk-rs.org/docs/gtk/struct.CellRendererText.html

**Comment by GuillaumeGomez** [comment]
It's [here](https://github.com/gtk-rs/gtk/blob/master/src/auto/cell_renderer_text.rs) so are you sure you have correctly imported it.

**Comment by EPashkin** [comment]
Problem that to set renderer to editable he need change object property and we currently don't have way do to it (only though ffi)

**Comment by EPashkin** [comment]
```rust
extern crate gobject_sys as gobject_ffi;
extern crate glib;
use glib::translate::*;
use glib::Value;
...
    let cell = CellRendererText::new();
    unsafe { 
	gobject_ffi::g_object_set_property(cell.to_glib_none().0, "editable".to_glib_none().0, Value::from(&true).to_glib_none().0);
    }
```

**Comment by EPashkin** [comment]
@oxeb, try this

**Comment by oxeb** [comment]
Thank you very much!  That works perfectly.

**Comment by GuillaumeGomez** [comment]
I close it then.
