### ISSUE TITLE
Missleading error message for `.get_object()`

### ISSUE THREAD

**Issue by Ronaldho80** [gtk-rs/gtk#424]
The code:
```
let glade_src = include_str!("gui.glade");
let builder = Builder::new_from_string(glade_src);
//...
let button1: gtk::ToggleButton = builder.get_object("button1").unwrap();
```
If "button1" is another kind of button (a `Button` instead of a `ToggleButton`), it crashes at runtime with: `thread 'main' panicked at 'called 'Option::unwrap()' on a 'None' value`. I would have expected a `mismachted types` error, because the "button1" is defined in `gui.glade`.

This holds also for other kinds of Buttons.

**Comment by EPashkin** [comment]
As `ToggleButton` is also `Button` this error IMHO unrelated to `mismatched` types.
Can you show `gui.glade`?

**Comment by Ronaldho80** [comment]
Sorry, I made a mistake in the issue description. It is the other way round: I wanted to associate a `Button` to a `ToggleButton`. I already updated my issue. Please have a look. 

Also, here is the glade file: https://gist.github.com/Ronaldho80/de0ca3e3e315d8effc39eb16f71eaba9

**Comment by EPashkin** [comment]
Currently `get_object` return `Option` and it don't contains error info as it unneeded in most cases ("don't found" not different from "unconvertable type")
```
    pub fn get_object<T: IsA<Object>>(&self, name: &str) -> Option<T> {
        unsafe {
            Option::<Object>::from_glib_none(
                ffi::gtk_builder_get_object(self.to_glib_none().0, name.to_glib_none().0))
                .and_then(|obj| obj.downcast().ok())
        }
}
```
If you really need react to typecast error, it simpler do it manually by getting `gtk::Object` first and downcasting it after.

**Comment by Ronaldho80** [comment]
Thanks for the hint.

My point of this issue is that "not found" and "unconvertable type" made quite a difference to me, because I could not solve the problem for quite a while. I was always wondering why it gave me a "not found" error although it is there. 

I am a beginner with gtk-rs and I know that this lib is in its development. I was even wondering, if it is just now working.

I don't argue that this issue is a big thing. However, I think that a verbose and correct error message is really helpful. In particular, I am used to precise and verbose error messages from Rust.

**Comment by EPashkin** [comment]
Problem that error produced by not gtk's `get_object` but your `.unwrap()`, so we nothing can do about it :wink:

**Comment by Ronaldho80** [comment]
Ok, I see. It's a pity.

Anyway, thanks for your help and for gtk-rs!
