### ISSUE TITLE
Popover constrain API is not exposed

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#426]
The `Popover` class is missing `set/get_constrain_to` and the related `PopoverConstraint`. This code is commented out in the gir-generated files, but I'm not certain why. But re-running Gir locally within this repo doesn't regenerate any code for versions newer than 3.12. Is this because the Gtk.gir file needs to be updated for the Popover class?

**Comment by EPashkin** [comment]
In line `//fn get_constrain_to(&self) -> /*Ignored*/PopoverConstraint;` `/*Ignored*/` means that `PopoverConstraint` don't generated. Normally you need add `"Gtk.PopoverConstraint",` to `generate = [` array in config.
Don't understand why you don't get 3.14++ versions by generate (may be your installed gtk too old)?

**Comment by Susurrus** [comment]
Okay, I added the missing type. I definitely have Gtk3.20 on this machine (Runing Fedora 25). Do you know how `Gir` decides what version to generate for? I don't know where I'd even check what version it's trying to generate files for.

**Comment by EPashkin** [comment]
If I don't forgot anything, for `gir` just uses .gir files and add all versions from it.

**Comment by Susurrus** [comment]
When running it I got `WARN:gir::config::gobjects: Configured object `Gtk.PopoverConstraint` missing from the library`. But I don't actually understand what that means. In the Gtk-3.0.gir file the PopoverConstraint value is defined there.

**Comment by EPashkin** [comment]
@Susurrus, can you clone `gtk` to new place and do `make` in it? May be your `gir` \ `gir-files` submodules gone wrong.

**Comment by Susurrus** [comment]
I'm closing this in light of #427.
