### ISSUE TITLE
ModelButton is missing

### ISSUE THREAD

**Issue by ednachi** [gtk-rs/gtk#429]
Hello, I see that the ModelButton is missing, obviously he is useful for the PopoverMenu. The gtk documentation says it's a v3_16 feature, are there plans for the integration?
[GtkModelButton](https://developer.gnome.org/gtk3/stable/GtkModelButton.html)

**Comment by EPashkin** [comment]
As `GtkModelButton` don't contains any methods and properties [still unfinished](https://github.com/gtk-rs/gir/issues/304), we don't generate wrapper for this class.
IMHO this can't stop you from using class in `.glade` and use it as normal `Button` in program.
