### ISSUE TITLE
Disable draw_value on Scale elements disables snapping to value

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#432]
I'm not positive if this is a gtk bug or a gtk-rs bug, but if I create a Scale element with s couple of set values that the selector should snap to, it works fine. But then if I call `set_draw_value(false)`, the scale no longer snaps to the appropriate values. I've included sample code:

```rust
extern crate gtk;

use gtk::prelude::*;

fn main() {

    gtk::init().expect("");

    let window = gtk::Window::new(gtk::WindowType::Toplevel);
    window.set_default_size(400, 300);

    let scale = gtk::Scale::new_with_range(gtk::Orientation::Horizontal, 1.0, 2.0, 1.0);
    scale.set_draw_value(false); // Comment out this line to see "proper" behavior
    scale.add_mark(1.0, gtk::PositionType::Bottom, Some("1"));
    scale.add_mark(2.0, gtk::PositionType::Bottom, Some("2"));

    let vbox = gtk::Box::new(gtk::Orientation::Vertical, 0);
    vbox.pack_start(&scale, false, false, 0);
    window.add(&vbox);
    window.show_all();
    gtk::main();
}
```

with Cargo.toml:
```toml

[dependencies.gtk]
version = "0.1"
```

**Comment by EPashkin** [comment]
Seems snapping unrelated to marks and controlled by https://developer.gnome.org/gtk3/stable/GtkScale.html#gtk-scale-set-digits (`scale.set_digits(1);` in your case) and works only when current value shown.
This can be seen if you set max to 5.0 and add 3.5 (or 4.0) marks.
If you need disable smooth scroll and don't show current value, you can use this
```
        scale.connect_format_value(|scale, value| {
            String::new()
        });
```

**Comment by Susurrus** [comment]
Thanks, yes I see what you're saying. So it seems like this is a GTK+ bug, either in their docs for not noting this limitation or in their code. I can't imagine why the behavior changes when changing appearance, however. I'll file a bug upstream and close this one once I do.

**Comment by Susurrus** [comment]
Moving this discussion to GNOME's bug tracker: https://bugzilla.gnome.org/show_bug.cgi?id=777858
