### ISSUE TITLE
32bit windows bug with TreeView Model

### ISSUE THREAD

**Issue by anfractuosity** [gtk-rs/gtk#434]
I found when I run simple_treeview.rs compiled on Windows as a 32 bit program, the program terminates due to:

https://github.com/gtk-rs/examples/blob/master/src/simple_treeview.rs#L20

I get the following output from a debugger:

"Unhandled exception at 0x63C67367 (libgobject-2.0-0.dll) in simple_treeview.exe: 0xC0000005: Access violation reading location 0x5B9628F4."

Just wondering if anyone has any ideas?

Cheers

**Comment by anfractuosity** [comment]
I've found the problem seems to occur at:
https://github.com/gtk-rs/gtk/blob/master/src/list_store.rs#L38

**Comment by EPashkin** [comment]
Hm, you right, for me both treeview's examples won't work on `nightly-i686-pc-windows-gnu\1.16.0.
I try look more at evening

**Comment by EPashkin** [comment]
Found problem:
```
#[repr(C)]
pub struct GValue {
    g_type: GType,
    pub data: [gpointer; 2],
}
```
on i686 `gpointer` size 4 instead 8  and in C data contains 2 guint64.
```
struct _GValue
{
  /*< private >*/
  GType		g_type;

  /* public for GTypeValueTable methods */
  union {
    gint	v_int;
    guint	v_uint;
    glong	v_long;
    gulong	v_ulong;
    gint64      v_int64;
    guint64     v_uint64;
    gfloat	v_float;
    gdouble	v_double;
    gpointer	v_pointer;
  } data[2];
};
```

**Comment by anfractuosity** [comment]
Thanks for looking into this!  

I'm a bit confused, what can be done to fix this?

**Comment by EPashkin** [comment]
@anfractuosity I add PR to https://github.com/gtk-rs/sys.
Fix is simple, can you test it on your system?
```diff
diff --git a/gobject-sys/src/lib.rs b/gobject-sys/src/lib.rs
index c5e9705..82ae71a 100644
--- a/gobject-sys/src/lib.rs
+++ b/gobject-sys/src/lib.rs
@@ -420,7 +420,7 @@ pub struct GTypeValueTable {
 #[repr(C)]
 pub struct GValue {
     g_type: GType,
-    pub data: [gpointer; 2],
+    pub data: [u64; 2],
 }
 
 #[repr(C)]
```

**Comment by anfractuosity** [comment]
I just tried forking sys, and adding your change, but unfortunately I presume some of the other gtk-rs crates are pulling a different sys git repo.

**Comment by EPashkin** [comment]
It can be solved adding `.cargo\config` with
```
paths = [
 "<full_path>/sys/gobject-sys",
]
```
Cargo will nags, but works.

**Comment by EPashkin** [comment]
.. after you clone `sys` locally

**Comment by anfractuosity** [comment]
Woo, that did the job :)  No longer crashes :)
Cheers!

**Comment by EPashkin** [comment]
Thanks for confirming.
