### ISSUE TITLE
Changing datatype for 2nd arg to TextView::connect_populate_popup

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#436]
I'm trying to use the `connect_populate_popup()` for a text view. The second argument is of type `&Widget`, but the premise of the function is that it will be either a `&ToolBar` or `&Menu` such that it can be modified before the popup is shown and this needs to be tested at runtime by the callback to appropriately modify the menu.

This seems ideal for an enum to enforce this, if I'm thinking about this correctly. Does that make sense and if so can it be done easily with the current architecture of gtk-rs? I think the only current option is to use `mem::transmute()` in an `unsafe` block, yes?

**Comment by EPashkin** [comment]
May be I don't fully understand your question, but if you want check real `Widget` type (that it is `ToolBar`) in your handler, you can use [Cast](http://gtk-rs.org/docs/glib/object/trait.Cast.html) trait.

**Comment by Susurrus** [comment]
Maybe I'm misreading this, but I think the 2nd argument can only be a Toolbar or a Menu. If that's the case, instead of making this a widget that needs to be Cast (thanks for pointing that out btw, it's working for me) could an enum of those 2 widgets be used instead?

**Comment by EPashkin** [comment]
As https://developer.gnome.org/gtk3/stable/GtkTextView.html#GtkTextView-populate-popup says there can be `another kind of container`

**Comment by Susurrus** [comment]
Okay, then nvm. Thanks.
