### ISSUE TITLE
size argument for new_from_icon_name should be an enum

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#439]
See https://developer.gnome.org/gtk3/stable/gtk3-Themeable-Stock-Images.html#GtkIconSize

**Comment by Susurrus** [comment]
Looks like that enum is already generated by gtk-rs, but isn't used as the argument. I'm instead using '2', which is the index into the GtkIconSize image, it's not a value in pixels but an enum index.

**Comment by EPashkin** [comment]
It mistakes in `Gtk-3.0.gir`, sometimes it says that property "icon-size" is `int` (`Image` e.t.c.), sometimes - that it `IconSize` (`ScaleButton`, `ToolBar`, ...)
Until https://github.com/gtk-rs/gir/issues/264 landed we nothing can do about it.

**Comment by Susurrus** [comment]
Okay, looking at that issue is looks like there needs to be hand-coded transformations ints to their index in enums. Makes sense. The last comment on that issue was a while ago, is there any movement on it or has it stalled out?

**Comment by EPashkin** [comment]
Currently only https://github.com/gtk-rs/gir/pull/293 was merged month ago, no work was done for  functions.

**Comment by sdroege** [comment]
We should really fix this, and if by changing the .gir file :)

**Comment by EPashkin** [comment]
Working fix, maybe add it tomorrow if have time
```diff
--- a/Gtk-3.0.gir
+++ b/Gtk-3.0.gir
@@ -11581,7 +11581,7 @@ gtk_button_set_image().</doc>
           </parameter>
           <parameter name="size" transfer-ownership="none">
             <doc xml:space="preserve">an icon size (#GtkIconSize)</doc>
-            <type name="gint" c:type="GtkIconSize"/>
+            <type name="IconSize" c:type="GtkIconSize"/>
           </parameter>
```

**Comment by sdroege** [comment]
Should check if there are more instances of the same

**Comment by EPashkin** [comment]
Fixed most usage, not fixed:
`CellRendererPixbuf` property "stock-size"
function `gtk_icon_set_get_sizes` that return array of enums.

**Comment by sdroege** [comment]
What's the problem with fixing that one?

**Comment by EPashkin** [comment]
@sdroege Property or function?

**Comment by sdroege** [comment]
Both

**Comment by EPashkin** [comment]
Property getter need be manual or waiting https://github.com/gtk-rs/gir/issues/264.
Function also need be manual with `.map(FromGlib::from_glib)`
Both IMHO don't need change gir-files.
