### ISSUE TITLE
Accessing MenuItem in popup in populate-popup for a TextView draws funny

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#441]
I wrote a test example to demonstrate the issue I was running into:
```rust
extern crate gtk;

use gtk::prelude::*;

fn main() {

    gtk::init().unwrap();

    // Create the main window
    let window = gtk::Window::new(gtk::WindowType::Toplevel);
    window.set_title("TextView right-click menu example");
    window.set_default_size(400, 300);

    // Create a text view
    let text_view = gtk::TextView::new();
    window.add(&text_view);

    // Connect the populate-popup signal to modify the TextView's right-click
    // menu.
    text_view.connect_populate_popup(|_, p| {
        if let Ok(popup) = p.clone().downcast::<gtk::Menu>() {
            for c in popup.get_children() {
                if let Ok(child) = c.downcast::<gtk::MenuItem>() {
                    // Comment out the following line to see correct behavior
                    println!("{}", child.get_label().unwrap());
                }
            }
        }
    });

    // Make sure all widgets are visible and run the damn thing!
    window.show_all();
    gtk::main();
}
```

If you run this you'll see the following:
![screenshot from 2017-02-02 13-11-49](https://cloud.githubusercontent.com/assets/206363/22568655/877015be-e949-11e6-9897-a55616da043f.png)

Now if you comment out the `println!()` you'll see the correct rendering:
![screenshot from 2017-02-02 13-12-13](https://cloud.githubusercontent.com/assets/206363/22568674/96002f60-e949-11e6-9c3a-8262538f9f93.png)

If you remove the `println!()` and just do `child.get_label().unwrap()` you'll still see the problem. If you do just `println!("{:?}", child);` you won't see the problem.

I'm inclined to think this is a Rust binding problem and not a Gtk one, so I'm filing it here first.

**Comment by GuillaumeGomez** [comment]
The problem seems to come from `child.get_label()`. Strange...

**Comment by Susurrus** [comment]
Actually, the problem occurs with `child.get_use_underline()` as well, but it doesn't occur with `child.get_accel_path()`, but `get_accel_path()` is always returning `None` while `get_use_underline()` is always returning an actual value. It also isn't a problem with `get_submenu()`, but that's also always returning `None`. But `get_reserve_indicator()` doesn't cause the problem either and it always returns false.

**Comment by Susurrus** [comment]
I see the exact same behavior in an example C program, so I've filed [778162 in the GNOME Bugzilla](https://bugzilla.gnome.org/show_bug.cgi?id=778162) and we can close this bug in lieu of that one.

**Comment by EPashkin** [comment]
@Susurrus Thank for digging into it.
I'm sure that you found solution yourself, but for record:
need add line `if c.is::<gtk::SeparatorMenuItem>() { continue; }` before downcasting to `MenuItem`

**Comment by Susurrus** [comment]
Thanks @EPashkin, but that still seems like a workaround. I wouldn't expect a call to `get_label` to mess up the rendering of a separator. I will deploy this as a workaround in the meantime however.
