### ISSUE TITLE
Enable drag_dest_set()

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#442]
Need to add `DestDefaults`, `TargetEntry`, and `gdk::DragAction` to the Gir generation script. I couldn't figure out why adding `DragAction` to `gdk`s `Gir.toml` didn't generate anything, so I'm posting this issue instead of a general PR.

**Comment by EPashkin** [comment]
With `DragAction` is no problem, next diff will generate it.
Problem with `TargetEntry`:
1. It almost only one class that used with `const*` in sys, and your `ToGlibPrt` implementation for `Boxed<ffi::GtkTargetEntry>` defined for `mut*`, so many build error appears.
2. It don't have usable function or get/setters and `gir` currently don't support direct access to record fields.
(May be this record really don't need those and `new` is enough to use)
```diff
--- a/Gir.toml
+++ b/Gir.toml
@@ -9,6 +9,7 @@ generate_safety_asserts = true
 
 generate = [
     "Gdk.CursorType",
+    "Gdk.DragAction",
     "Gdk.GLError",
     "Gdk.Gravity",
     "Gdk.ModifierIntent",
```

**Comment by Susurrus** [comment]
So it sounds like there needs to be a manual implementation of `GtkTargetEntry` for this functionality to be exposed? Anyone interested in tackling that?

**Comment by GuillaumeGomez** [comment]
Why not doing it? Might be nice for you to discover a bit how it works under the hood. :p

**Comment by Susurrus** [comment]
As of gtk-rs/gdk#144 only a manual implementation of `TargetEntry` is necessary to get `drag_source` and `drag_dest` functions working.

**Comment by EPashkin** [comment]
IMHO as with [GdkRGBA](https://github.com/gtk-rs/gdk/blob/master/src/rgba.rs) better almost ignore `free` and `copy` functions and declare normal rust struct with `ToGlibPtr` ..
