### ISSUE TITLE
What about pangocairo crate?

### ISSUE THREAD

**Issue by RazrFalcon** [gtk-rs/gtk#453]
Is it planned? Or is it already exist and I didn't found it?

Or not even as a crate, but as a feature.

**Comment by GuillaumeGomez** [comment]
I know pango (which has a binding), I know cairo (which also has a binding), I didn't know pangocairo was a thing.

**Comment by RazrFalcon** [comment]
I'm speaking about this: https://developer.gnome.org/pango/stable/pango-Cairo-Rendering.html

As far as I understand, it's part of pango. On Gentoo I have `/usr/include/pango-1.0/pango/pangocairo.h` as part of pango package.

Looks like pango crate doesn't have such bindings. Probably title is a bit misleading.

**Comment by GuillaumeGomez** [comment]
Hum strange. Have you check the master branch or the crate one?

**Comment by RazrFalcon** [comment]
Yes. I didn't found anything about cairo here: https://github.com/gtk-rs/sys/blob/master/pango-sys/src/lib.rs

**Comment by GuillaumeGomez** [comment]
Then we haven't done it yet. Motivated to add it? :)

**Comment by RazrFalcon** [comment]
All I can found is: https://github.com/gtk-rs/gir-files/blob/master/PangoCairo-1.0.gir

Yes, why not. Any readme about how to do this? As far as I understand you are using codegen for this.

**Comment by GuillaumeGomez** [comment]
Yes, take a look at gir's [README](https://github.com/gtk-rs/gir/blob/master/README.md) (which is a bit short...). *Normally* you should be ok with it but don't hesitate to ask if you can't find out.

**Comment by RazrFalcon** [comment]
Well... I didn't really understand what I need to do.

As far as I understand, I should create `gir-pangocairo.toml` in `gtk-rs/sys/conf/`, because `gir-files` contains it as separate file. So it's really should be a create. Also there are an actual library called `libpangocairo`, which is part of the `pango` package.

Then I should hit `make`, but I get an error:
```
% make
gir/target/release/gir -c conf/gir-pangocairo.toml -o /media/data/Programming/Sources/gtk/sys/pangocairo-sys -d gir-files
thread 'main' panicked at 'src/parser.rs:659 Missing alias target's c:type in gir-files/freetype2-2.0.gir:12:7', src/parser.rs:53
note: Run with `RUST_BACKTRACE=1` for a backtrace.
make: *** [Makefile:9: pangocairo-sys/src/lib.rs] Error 10
```

Looks like it didn't like this line: https://github.com/gtk-rs/gir-files/blob/master/freetype2-2.0.gir#L12

**Comment by GuillaumeGomez** [comment]
And that's the moment when we summon @EPashkin to say: there is a panic! 😨

**Comment by RazrFalcon** [comment]
Looks like `freetype2-2.0.gir` is invalid. It should look like this:
```
<type name="int32" c:type="int"/>
```
but it's
```
<type name="int32"/>
```

**Comment by RazrFalcon** [comment]
Then I have to fix `PangoCairo-1.0.gir`
```diff
-        <type c:type="PangoFcFontMap"/>
+        <type name="FontMap" c:type="PangoFcFontMap"/>
```

**Comment by RazrFalcon** [comment]
Now I'm getting:
```
% make
gir/target/release/gir -c conf/gir-pangocairo.toml -o /media/data/Programming/Sources/gtk/sys/pangocairo-sys -d gir-files
thread 'main' panicked at 'Incomplete library, unresolved: ["freetype2.int32"]', src/library_postprocessing.rs:41
note: Run with `RUST_BACKTRACE=1` for a backtrace.
make: *** [Makefile:9: pangocairo-sys/src/lib.rs] Error 101
```

**Comment by RazrFalcon** [comment]
After patching `freetype2-2.0.gir`:
```diff
-      <type name="int32"/>
+      <type name="Int32" c:type="gint"/>
```

I got it working and I get a `pangocairo-sys` dir.

What next? I should send a pull request with it and then manually create bindings in a new git repo, like pango itself?

**Comment by RazrFalcon** [comment]
And I still can build it, because it depend on: cairo-sys, freetype2-sys.

**Comment by EPashkin** [comment]
Currently I against patching `gir-files` crate, so better not include `pangocairo-sys` to `sys` crate.
`int32` IMHO better fixed on `gir` side by adding its type (`gint` as can be 64bits)
Don't know how to fix `PangoFcFontMap` issue as no such type in `Pango-1.0.gir` (only found `PangoFontMap`).

**Comment by EPashkin** [comment]
Seems `PangoCairo-sys` will be written manually (maybe with using generated code as template).
I also found https://github.com/jpernst/pangocairo-sys on crates.

**Comment by RazrFalcon** [comment]
I see. Then I will try to write it manually. 

Yes, I saw this crate, but it has binding not only for `pangocairo` and I don't think it can be mixed with existing `cairo` and `pango` crates. And I want a crate, which will depend on `gtk-rs` libs.

**Comment by RazrFalcon** [comment]
So:

1. I have created `pangocairo-sys` crate, which works fine.
1. Then I have created `pangocairo` crate, which depend on `pangocairo-sys`, `cairo` and `pango`. Empty library has been build without errors.
1. Now I have to create an actual wrapper, to `pangocairo-sys` methods.

And there are problems. The root function looks like this:
```rust
pub fn pango_cairo_create_layout(cr: *mut cairo::cairo_t) -> *mut pango::PangoLayout;
```
so I have to write something like this:
```rust
pub fn create_layout(content: &cairo::Content) -> pango::Layout {
    unsafe { from_glib_full(ffi::pango_cairo_create_layout(content.to_glib_none().0)) }
}
```
but:
1. I get an error:
    ```
    the method `to_glib_none` exists but the following trait bounds were not satisfied: `cairo::Content : glib::translate::ToGlibPtr<_>`
    ```
1. There are no `pango::Layout` in [pango crate](https://github.com/gtk-rs/pango/blob/master/src/lib.rs).

Sorry for stupid questions, it's my first bindings.

**Comment by EPashkin** [comment]
[`Content`](http://gtk-rs.org/docs/cairo/enums/enum.Content.html) is enum 
May be you mean [`Context`](http://gtk-rs.org/docs/cairo/struct.Context.html).
And yes, no PangoLayout

**Comment by RazrFalcon** [comment]
Yes, my mistake. So I should implement/wait for PangoLayout?

**Comment by EPashkin** [comment]
I added generation of layout in https://github.com/EPashkin/pango/tree/add_generation
Commit not full due my git error (It can't init submodules).
`Makefile` copied from working project so IMHO it run normally.
For generating I used fixed `gir` from https://github.com/EPashkin/gir/tree/fix_for_pango

**Comment by RazrFalcon** [comment]
So I should wait until it will be merged to the main tree?

**Comment by EPashkin** [comment]
I prefer leave this branch to you :wink:
Feel free to use it in your PR to pango.
At minimum better deignore Layout::get_alignment by adding `"Pango.Alignment",` to `generate=[`

**Comment by RazrFalcon** [comment]
I did not think that adding a simple wrapper like pangocairo will be such pain.

Yours branch contain an `auto` folder which should be manually ported to the `widget` folder. Am I correct?

**Comment by EPashkin** [comment]
Not, `auto` folder is primary, `widget` in `pango` crates or files in `src` in other gir-connected crates used only for part that can't properly generated by gir.
In your case I think you need add generation pango classes that needed for pangocairo crate and try minimize commented functions in generated code (if it works without problem, ex. "Pango.Rectangle" currently can't be used/generated).

**Comment by RazrFalcon** [comment]
Well, from on side I still have no idea what to do, but from another, I really need this crate...

Is there are any plans for making it or it not even planned?

**Comment by EPashkin** [comment]
Is I remember, no certain plans about applying `gir` to `pango` crate, mostly due `gir` deficiencies.
I don't use `pango`, so I don't sure what classes needed first, that why I propose that you add PR with classes or other definition that needed for `pangocairo`.
If you don't want or don't have time do it, then I add PR on weekend with minimal changes from current add_generation branch

**Comment by RazrFalcon** [comment]
The problem is that I didn't know what I need too. I have C code that I should port to Rust. It uses pangocairo. As far as I can see it uses almost all pangocairo methods.

I can write, I hope so, a wrapper around ffi, like pango and cairo itself, but all this generator stuff are beyond my understanding.

**Comment by EPashkin** [comment]
I mean if your `pangocairo` method will use some `pango` definition (as with `Layout`) you can add it (or try) with `gir` just by adding it definition to `generate` array in `Gir.toml` and run `gir` on it.

**Comment by RazrFalcon** [comment]
>minimize commented functions in generated code

Manually?

**Comment by RazrFalcon** [comment]
I have finally figure out how to build your repo.

So I've added `Pango.Alignment` and got this error:
```rust
error[E0432]: unresolved import `glib_ffi`
 --> src/auto/enums.rs:5:5
  |
5 | use glib_ffi;
  |     ^^^^^^^^ no `glib_ffi` in the root
```

As I understand it's also should be fixed via gir?

**Comment by RazrFalcon** [comment]
I've added
```toml
[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.2"
```
and not it saying that it's useless:
```rust
warning: unused import: `glib_ffi`, #[warn(unused_imports)] on by default
 --> src/auto/enums.rs:5:5
  |
5 | use glib_ffi;
  |     ^^^^^^^^

warning: unused import: `glib::error::ErrorDomain`, #[warn(unused_imports)] on by default
 --> src/auto/enums.rs:6:5
  |
6 | use glib::error::ErrorDomain;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^
```

So it's shouldn't be generated at first place?

**Comment by RazrFalcon** [comment]
Finally I made my `create_layout` method from pangocairo working.

Then what? I should add all methods from `pangocairo` while adding missing types to pango's Gir.toml? And if it will work - I'll have to create a pull request to yours pango fork?

**Comment by EPashkin** [comment]
Seems you solved `extern crate glib_sys as glib_ffi;` problem.
About adding PR: you need add it to https://github.com/gtk-rs/pango
If you can, remove lines in `lib.rs` like `pub use ffi::PangoGravity as Gravity;` and add generate these enums and flags. After that you need add many `to_glib`\`from_glib` to files in `widgets` dir.

**Comment by RazrFalcon** [comment]
Ok.

Next problem:

I've added `"Pango.FontMap"` to the `Gir.toml`, because I need this struct, and it generates all the data, but under `#[cfg(feature = "v1_4")]`. And the problem is that there is no `v1_4` in `pango_sys`.

`pango` crate itself has `v1_38` and `v1_42`.

I've added `v1_4 = ["v1_38", "pango-sys/v1_38"]` manually to pango's Cargo.toml and it's works for now.

How it should be solved?

**Comment by EPashkin** [comment]
Change\add `min_cfg_version = "1.30"` in pango\Gir.toml
I forgot to do that.

**Comment by RazrFalcon** [comment]
Ok. Fixed.

Where should I implement ToGlibPtr/FromGlibPtr traits? Not in the auto dir, presumably. In lib.rs?

**Comment by EPashkin** [comment]
For what class?

**Comment by RazrFalcon** [comment]
Yeap. Looks like it already implemented in by `glib_wrapper!`, because I'm getting

```
conflicting implementations of trait `glib::translate::ToGlibPtr<'_, *mut ffi::PangoLayout>` for type `&auto::layout::Layout`:
```

But if I remove it - I'm getting:
```rust
error[E0277]: the trait bound `pango::Layout: glib::translate::ToGlibPtr<'_, *mut pango_sys::PangoContext>` is not satisfied
  --> src/lib.rs:35:74
   |
35 |     unsafe { ffi::pango_cairo_update_context(cr.to_glib_none().0, layout.to_glib_none().0); };
   |                                                                          ^^^^^^^^^^^^ the trait `glib::translate::ToGlibPtr<'_, *mut pango_sys::PangoContext>` is not implemented for `pango::Layout`
   |
   = help: the following implementations were found:
   = help:   <pango::Layout as glib::translate::ToGlibPtr<'a, *mut glib::object::GObject>>
   = help:   <pango::Layout as glib::translate::ToGlibPtr<'a, *const pango_sys::PangoLayout>>
   = help:   <pango::Layout as glib::translate::ToGlibPtr<'a, *mut pango_sys::PangoLayout>>
```

The method itself:
```
pub fn show_layout(cr: &cairo::Context, layout: &pango::Layout) {
    unsafe { ffi::pango_cairo_update_context(cr.to_glib_none().0, layout.to_glib_none().0); };
}
```

**Comment by RazrFalcon** [comment]
Wait. I've misspelled the method... Forget about it.

**Comment by RazrFalcon** [comment]
Now I'm getting:
```
error: linking with `cc` failed: exit code: 1
  |

... a lot of text
 "-l" "pango-1.0" "-l" "gobject-2.0" "-l" "glib-2.0" "-l" "cairo" "-l" "pango-1.0" "-l" "gobject-2.0" "-l" "glib-2.0" "-l" "gobject-2.0" "-l" "glib-2.0" "-l" "glib-2.0" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /media/data/Programming/Projects/rust/resvg/tools/rendersvg/target/debug/deps/libpangocairo-a39c28cc6685b440.rlib(pangocairo-a39c28cc6685b440.0.o): In function `pangocairo::create_layout':
/media/data/Programming/Projects/rust/pangocairo/src/lib.rs:27: undefined reference to `pango_cairo_create_layout'
collect2: error: ld returned 1 exit status
```

I understand that some libraries are missing during linking, but I've selected them in `build.rs`.

Here is `pangocairo-sys/build.rs`:
```rust
extern crate pkg_config;

use pkg_config::{Config, Error};
use std::env;
use std::io::prelude::*;
use std::io;
use std::process;

fn main() {
    if let Err(s) = find() {
        let _ = writeln!(io::stderr(), "{}", s);
        process::exit(1);
    }
}

fn find() -> Result<(), Error> {
    let package_name = "pango";
    let shared_libs = ["pango-1.0", "pangocairo-1.0", "pango-1.0", "pangoft2-1.0"];
    let version = "1.38";
    // let version = if cfg!(feature = "v1_42") {
    //     "1.42"
    // } else if cfg!(feature = "v1_38") {
    //     "1.38"
    // } else if cfg!(feature = "v1_36_7") {
    //     "1.36.7"
    // } else if cfg!(feature = "v1_34") {
    //     "1.34"
    // } else if cfg!(feature = "v1_32_4") {
    //     "1.32.4"
    // } else if cfg!(feature = "v1_32") {
    //     "1.32"
    // } else if cfg!(feature = "v1_31") {
    //     "1.31"
    // } else {
    //     "1.30"
    // };

    if let Ok(lib_dir) = env::var("GTK_LIB_DIR") {
        for lib_ in shared_libs.iter() {
            println!("cargo:rustc-link-lib=dylib={}", lib_);
        }
        println!("cargo:rustc-link-search=native={}", lib_dir);
        return Ok(())
    }

    let target = env::var("TARGET").unwrap();
    let hardcode_shared_libs = target.contains("windows");

    let mut config = Config::new();
    config.atleast_version(version);
    if hardcode_shared_libs {
        config.cargo_metadata(false);
    }
    match config.probe(package_name) {
        Ok(library) => {
            if hardcode_shared_libs {
                for lib_ in shared_libs.iter() {
                    println!("cargo:rustc-link-lib=dylib={}", lib_);
                }
                for path in library.link_paths.iter() {
                    println!("cargo:rustc-link-search=native={}", path.to_str().unwrap());
                }
            }
            Ok(())
        }
        Err(Error::EnvNoPkgConfig(_)) | Err(Error::Command { .. }) => {
            for lib_ in shared_libs.iter() {
                println!("cargo:rustc-link-lib=dylib={}", lib_);
            }
            Ok(())
        }
        Err(err) => Err(err),
    }
}

```

and Here is `pangocairo-sys/Cargo.toml`:
```toml
[package]
name = "pangocairo-sys"
version = "0.1.0"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]
build = "build.rs"
license = "MIT"
description = "Rust bindings for the PangoCairo library"
repository = "https://github.com/razrfalcon/pangocairo-sys"
keywords = ["pango", "cairo", "ffi"]

[dependencies]
libc = "0.2"
cairo-sys-rs = { git = "https://github.com/gtk-rs/cairo" }
pango-sys = { git = "https://github.com/gtk-rs/sys" }

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"

[build-dependencies]
pkg-config = "0.3.7"

[lib]
name = "pangocairo_sys"

```

**Comment by EPashkin** [comment]
In build, `package_name = "pangocairo";` ?
I don't see -l "pangocairo" in command line, may be you need minimize `shared_libs`

**Comment by RazrFalcon** [comment]
D'oh. Fixed by a proper `package_name`.

**Comment by RazrFalcon** [comment]
And again.

I've added `"Pango.FontDescription"` to the `Gir.toml` and removed one from `widgets`.

Now `pango` is failed to build:
```rust
error[E0277]: the trait bound `auto::font_description::FontDescription: glib::translate::FromGlibPtr<*const ffi::PangoFontDescription>` is not satisfied
  --> src/auto/layout.rs:86:13
   |
86 |             from_glib_none(ffi::pango_layout_get_font_description(self.to_glib_none().0))
   |             ^^^^^^^^^^^^^^ the trait `glib::translate::FromGlibPtr<*const ffi::PangoFontDescription>` is not implemented for `auto::font_description::FontDescription`
   |
   = help: the following implementations were found:
   = help:   <auto::font_description::FontDescription as glib::translate::FromGlibPtr<*mut ffi::PangoFontDescription>>
   = note: required because of the requirements on the impl of `glib::translate::FromGlibPtr<*const ffi::PangoFontDescription>` for `std::option::Option<auto::font_description::FontDescription>`
   = note: required by `glib::translate::from_glib_none`

error: aborting due to previous error
```

Method itself:
```rust
    pub fn get_font_description(&self) -> Option<FontDescription> {
        unsafe {
            from_glib_none(ffi::pango_layout_get_font_description(self.to_glib_none().0))
        }
    }
```

**Comment by EPashkin** [comment]
Problem in that sys says that `pango_layout_get_font_description` return `*const ffi::PangoFontDescription`, and generated defined only for `*mut ffi::PangoFontDescription`.
You need change in sys or add `impl FromGlibPtr<*const ffi::PangoFontDescription> for FontDescription {`.
Also I don't sure that you need generate classes in `widgets` if it work without it.

**Comment by RazrFalcon** [comment]
So I should add it to `auto/layout.rs`? But it will be overwritten. 

>Also I don't sure that you need generate classes in widgets if it work without it.
Not really understand it. I do not generate anything in widgets. I have removed `font_description.rs` from widgets, because it was generated in `auto`.

**Comment by EPashkin** [comment]
I mean that maybe you don't need generating any of `widgets` as it already present in crate.
But if it really need add something to generated crate, you can add module `font_description.rs` near `lib.rs` (or in case of pango in widgets) where be only `impl FromGlibPtr` for generated `FontDescription`

**Comment by RazrFalcon** [comment]
The problem is that in this case I will have to edit `layout.rs`, because it uses `FontDescription`. So in either cases I have to do manual corrections after each gen.

**Comment by EPashkin** [comment]
Seems there some misunderstanding. As I see call `pango_layout_get_font_description` don't compiled due `FontDescription` don't implement `FromGlibPtr<*const ffi::PangoFontDescription>` (only implement *mut ...) and you need add it somewhere. This can be added in separate module with  same name ` font_description.rs` but not in `auto` dir

**Comment by EPashkin** [comment]
Don't see reason to change generated `layout.rs`.

**Comment by EPashkin** [comment]
Also I missed your reason for generating "Pango.FontDescription".
If you need uncomment generated `pango_layout_get_font_description`, you can add "pango_layout_get_font_description" to `manual` array, without removing `widgets\font_description.rs`

**Comment by RazrFalcon** [comment]
>Don't see reason to change generated layout.rs.

Because all changes will be missed after next gen.

How exactly should I implement this trait?
```rust
impl FromGlibPtr<*const ffi::PangoFontDescription> for FontDescription {
    unsafe fn from_glib_none(ptr: *const ffi::PangoFontDescription) -> Self {
        let tmp = ffi::pango_font_description_copy(ptr);
        assert!(!tmp.is_null());
        FontDescription(tmp)
    }

    unsafe fn from_glib_full(ptr: *const ffi::PangoFontDescription) -> Self {
        assert!(!ptr.is_null());
        FontDescription(ptr)
    }
}
```
```rust
error[E0308]: mismatched types
  --> src/lib.rs:29:25
   |
29 |         FontDescription(tmp)
   |                         ^^^ expected struct `glib::boxed::Boxed`, found *-ptr
   |
   = note: expected type `glib::boxed::Boxed<ffi::PangoFontDescription, auto::font_description::MemoryManager>`
   = note:    found type `*mut ffi::PangoFontDescription`

error[E0308]: mismatched types
  --> src/lib.rs:34:25
   |
34 |         FontDescription(ptr)
   |                         ^^^ expected struct `glib::boxed::Boxed`, found *-ptr
   |
   = note: expected type `glib::boxed::Boxed<ffi::PangoFontDescription, auto::font_description::MemoryManager>`
   = note:    found type `*const ffi::PangoFontDescription`
```


I've tried using `widgets/font_description.rs`, but I still got the same error. There is no particular motivation, I'm just trying to make it work.

**Comment by EPashkin** [comment]
Strange, I added to manual, added impl for const * with only notable changes in from_glib_full and it works fine.
No changes in `auto\layout.rs`.
```
    unsafe fn from_glib_full(ptr: *const ffi::PangoFontDescription) -> Self {
        assert!(!ptr.is_null());
        FontDescription(ptr as *mut _)
    }
```

**Comment by EPashkin** [comment]
*no changes other that generated

**Comment by RazrFalcon** [comment]
`manual` is in `Gir.toml`? Doesn't seems like it changed anything. 

It's works for now. In the end I removed `FontDescription` from `Gir.toml` and edited `auto/layout.rs` manually.

**Comment by EPashkin** [comment]
Yes,
```
manual = [
    "Pango.FontDescription",
]
```
with removing it from generate, add impl to `widgets/fond_description.rs` and remove `auto/font_description.rs`.
I have no idea what you changed in `auto/layout.rs`

**Comment by RazrFalcon** [comment]
Cool. It works.

You sad:

>you can add "pango_layout_get_font_description" to manual array

So I put `pango_layout_get_font_description` in `manual`. Which was wrong. Now everything works fine, without any changes in `auto`.

**Comment by EPashkin** [comment]
Sorry, I was copied wrong text, fixed it, but don't say about it.

**Comment by RazrFalcon** [comment]
Finally! I drew some text. Mission accomplished.

Will try to prepare a pull request tomorrow.

**Comment by EPashkin** [comment]
@RazrFalcon, I merged gir's [PR](https://github.com/gtk-rs/gir/pull/318) with pango-related fixes.
Please, upgrade gir submodule to it. First line of generated file look `// This file was generated by gir (aacfc92) from gir-files (71d73f0)`

**Comment by RazrFalcon** [comment]
Done?.. It's my first pull request, so I could easily mess it up.

**Comment by RazrFalcon** [comment]
`pango` is done for now (I'll probably add new structs when I need them). But what to do with `pangocairo-sys` and `pangocairo`?

Should I publish them as two separate repos in my profile or in `gtk` project? Should I publish them oi n crates?

**Comment by EPashkin** [comment]
I prefer that it published in your profile (may be even only one crate as https://crates.io/crates/cairo-rs).
@GuillaumeGomez, what you think?

**Comment by RazrFalcon** [comment]
Ok. By one `crate` you mean that `sys` will be inside?

**Comment by EPashkin** [comment]
Yes.

**Comment by EPashkin** [comment]
Only problem with publishing your crate that we don't have planned date to publish pango, so at first it may depends not on crate but on git.

**Comment by RazrFalcon** [comment]
It's not a problem. I'm not planning to release my main project in crates any time soon.

**Comment by RazrFalcon** [comment]
How to reexport "defines" from sys? I need this define: https://github.com/gtk-rs/sys/blob/master/pango-sys/src/lib.rs#L573

Currently done by adding `pub use ffi::PANGO_SCALE as SCALE;` to the `libs.rs`.

**Comment by RazrFalcon** [comment]
Second problem. I need `Rectangle`. But adding `"Pango.Rectangle",`to `manual` doesn't work, because currently `Rectangle` is a trait. The object itself is `ffi::PangoRectangle`.

How is this should be solved?

PS: maybe we should create another issue for this tasks, because it's strictly `pango` crate problems.

**Comment by EPashkin** [comment]
Constant really can just reexported, but name better rustified like `Scale`.
As `gir` currently don't support direct record, you can only rewrite rectangle same as https://github.com/gtk-rs/gdk/blob/master/src/rectangle.rs

**Comment by EPashkin** [comment]
About new issue, it depend of you need of fast merging https://github.com/gtk-rs/pango/pull/54.
We can just move there and mark it as WIP.

**Comment by EPashkin** [comment]
I was wrong about constant name, `SCALE` is fine.

**Comment by RazrFalcon** [comment]
Ok. I will use this `Rectangle` implementations as a reference.

>it depend of you need of fast merging 
I'm not in rush. I'm using a local copy for now.

**Comment by GuillaumeGomez** [comment]
I'm fine with @RazrFalcon publishing the crate on his own, it's his code after all. We're just very glad to have his support for the gtk-rs project. ;)

**Comment by EPashkin** [comment]
@RazrFalcon, can you add link to your `pangocairo` git and close this Issue?

**Comment by RazrFalcon** [comment]
I do not publish it yet. I will do it later today.

But should it be closed? My crate will depend on `git` crates, and I can't release it on creates.io like this. Only when `pango` with my changes will be released to creates too.

**Comment by RazrFalcon** [comment]
Done: https://github.com/RazrFalcon/pangocairo-rs

Suggestions are welcome.

All the commented code in `src/lib.rs` can't be implemented now, because there are no such types in `pango`/`cairo` yet. But it's already supported all I need.

**Comment by RazrFalcon** [comment]
Done https://crates.io/crates/pangocairo !
