### ISSUE TITLE
Support GtkIconSize

### ISSUE THREAD

**Issue by aldonogueira** [gtk-rs/gtk#456]
The function Button::new_from_icon_name() expects an i32 called size. The name suggests that this value is the image size in pixels, but it's actually an index in enum GtkIconSize.
https://developer.gnome.org/gtk3/stable/gtk3-Themeable-Stock-Images.html#GtkIconSize

There should probably exist an enum gtk::IconSize with values Menu, Button, LargeToolbar, etc.

**Comment by Susurrus** [comment]
I believe this is a duplicate of #439

**Comment by GuillaumeGomez** [comment]
Part of at least. Will close in favor of #439.
