### ISSUE TITLE
Bump version of Cairo/cvec?

### ISSUE THREAD

**Issue by qdot** [gtk-rs/gtk#457]
I'm building a cross-platform GUI application which will use the gtk-rs bindings for linux. However, bringing in gtk in as a platform specific dependency runs into this bug in cargo:

https://github.com/rust-lang/cargo/issues/3512

It looks like the newest version of the cairo crate no longer has this dylib specification in the Cargo.toml. I realize this is a cargo bug, but since you mentioned you may be doing a new release soon according to #451, could you bump the required version of cvec in cairo, then bump the version of cairo here?

**Comment by EPashkin** [comment]
Version already bumped https://github.com/gtk-rs/cairo/commit/4112003b5f08e498c73284d9bd033c69d1edc5f8

**Comment by qdot** [comment]
Fixed now that #451 is resolved, thanks!
