### ISSUE TITLE
Bindings for VTE

### ISSUE THREAD

**Issue by alex285** [gtk-rs/gtk#460]
are you guys thinking to generate bindings for VTE widgets?

**Comment by takluyver** [comment]
@oakes has a commit in his fork (oakes/gtk@4d6325be9c795918fec6b209c3936485d49b666c) which adds bindings for VTE. He's using this in his [SolidOak](https://github.com/oakes/SolidOak) project, and it appears to be working, though I haven't tried to break it.

**Comment by EPashkin** [comment]
IMHO VTE is separate library, not gtk, so it need separate crate.
Also by `struct_Widget!` seems this fork done before https://github.com/gtk-rs/gtk/pull/221 landed

And https://crates.io/search?q=vte shows already implemented crates, some of which depend on gtk-rs

**Comment by takluyver** [comment]
Thanks @EPashkin . @antoyo's recent [vte-rs](https://github.com/antoyo/vte-rs) crate looks the most promising of those results; I'll give it a try.

**Comment by oakes** [comment]
@takluyver FYI I finally updated solidoak to use the latest gtk-rs and vte-rs. However I had to fork the latter to make some additions:

https://github.com/oakes/vte-rs

**Comment by takluyver** [comment]
:-) Have you dropped antoyo a pull request?

**Comment by antoyo** [comment]
Well, most of the manual edition in this fork can probably be autogenerated.
Also, it seems to be using the old `RGBA`. Is there any reason why?

**Comment by oakes** [comment]
Maybe I'm pulling in an old dependency, but I had to change the RGBA to fix an error. I'll take another look at it later.

**Comment by takluyver** [comment]
I also had some trouble compiling - I found a way to make it work without changing the type of the arguments, but I have no idea if it's correct:

https://github.com/antoyo/vte-rs/pull/1/files

**Comment by sdroege** [comment]
New bindings for non-platform GNOME libraries would be better placed in https://gitlab.gnome.org/World/Rust
