### ISSUE TITLE
Broken page in documentation for ObjectExt

### ISSUE THREAD

**Issue by SamWhited** [gtk-rs/gtk#463]
The [ObjectExt](http://gtk-rs.org/docs/gtk/trait.ObjectExt.html) page currently 404's in the documentation. However, it is linked from other pages like [gtk::Settings](http://gtk-rs.org/docs/gtk/struct.Settings.html).

**Comment by nt8r** [comment]
The link in `gtk::Settings` correctly points to [glib::object::ObjectExt](http://gtk-rs.org/docs/glib/object/trait.ObjectExt.html) now.

**Comment by SamWhited** [comment]
Yup, looks to be fixed. Thanks.
