### ISSUE TITLE
Builds failing since #464

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#465]
I've been trying to use the new `get_color` functions since you merged them yesterday, but since #464 was merged, `gtk` doesn't compile. You can see this on Travis as well. I just wanted to make sure you were all aware of the issue.

@GuillaumeGomez @EPashkin

**Comment by GuillaumeGomez** [comment]
Ah indeed. cc @EPashkin

**Comment by EPashkin** [comment]
I add emty PR to test it on CI

**Comment by Susurrus** [comment]
I think your strategy is to have a dev branch that people should be tracking that always tracks git and a master branch that tracks releases, yes? If that's the case, just revert #462 on this branch, and then apply it instead to the new dev branch where it uses git for all dependencies.

**Comment by Susurrus** [comment]
@EPashkin You can also re-run jobs directly from Travis if you have permissions (which you should as a member of this organization) instead of making fake PRs.

**Comment by EPashkin** [comment]
@Susurrus right, while examples builds fine, main build fails :( I missed that.
Also we now have strange travis fails on nightly cargo
```
@cargo --version
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Susurrus** [comment]
Nightly might be broken just on its own, so I wouldn't worry about that too much.

**Comment by EPashkin** [comment]
Seems non-nightly build fixed.
@GuillaumeGomez, now we have these options:
- undo `replace` PR's
- fix build with same `replace`
That caused warnings like `warning: package replacement is not used: https://github.com/rust-lang/crates.io-index#gtk:0.1.2`
- fix build with filtered `replace`
This remove warnings but maybe complicate your gtk-rs upgrade script

**Comment by Susurrus** [comment]
What's the point of specifying versions and then replacements, I don't understand how this is any different than specifying dependencies on git repos as before? I don't fully understand why this change was made in the first place either, however, so I might be missing a lot of context.

**Comment by EPashkin** [comment]
Main reason this changes that I wanted remove `crate` branch in `gtk`, but I was too focused on test with examples and though that only need change in it.
Second reason was many long override warning when building examples with `.cargo/config/path` overrides.

**Comment by GuillaumeGomez** [comment]
@EPashkin: Then I'd go for a reverting.

**Comment by EPashkin** [comment]
Currently contributors can't use method described in http://doc.crates.io/specifying-dependencies.html#overriding-dependencies to change one part of gtk-rs.
This happened due we change only version in `crate` branch before publishing,
change version in main branch was done after (if not forgotten).
Current version allow update all version in `master/Cargo.toml` then merging it to `crate` with removing `[replace]` part.

**Comment by EPashkin** [comment]
@GuillaumeGomez, Ok. you doing it or I?

**Comment by GuillaumeGomez** [comment]
Your mistake. :p

**Comment by EPashkin** [comment]
Added some manual revert PR for examples and auto revert PRs on other crates.
May be I need add update version on revert PRs ?
Or add it later?

**Comment by EPashkin** [comment]
*one manual revert on examples and auto revert PRs on some other crates

**Comment by GuillaumeGomez** [comment]
@EPashkin: It's fine, like this, I'll update the crate version next time we make a release.

**Comment by EPashkin** [comment]
Ok, the I create, you - merge ;)

**Comment by GuillaumeGomez** [comment]
Yes sir! :)

**Comment by EPashkin** [comment]
Created PRs for all but gtk, create it after all previous merged to build check

**Comment by GuillaumeGomez** [comment]
Ok, I start merges then.

**Comment by GuillaumeGomez** [comment]
All merged. Thanks for this @EPashkin! (remaing gtk) Too bad it didn't work. :-/

**Comment by EPashkin** [comment]
@GuillaumeGomez Sorry for the time taken away. Gtk not need be merged until appveyor passed.
Then please restart CI on crate.
@Susurrus Thanks for pointing on problem

**Comment by EPashkin** [comment]
@GuillaumeGomez sorry, CI restart not needed

**Comment by EPashkin** [comment]
May be I need also revert PR in https://github.com/gtk-rs/gtk-rs.github.io

**Comment by EPashkin** [comment]
Or change text to git version?

**Comment by EPashkin** [comment]
Appveyour passed for all revert merges.

**Comment by Susurrus** [comment]
This seems to be completely fixed so I'm closing.
