### ISSUE TITLE
Using WidgetExt::add_event is unergonomic

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#468]
`WidgetExt::add_event()` takes an `i32`, not a `gdk::EventMask`. Not only that but `gdk::EventMask`'s `bits()` method returns an `u32`, not an `i32`, so an additional cast is necessary.

Basically when using `add_events()` you have to write something like:
```
operations_icon.add_events((gdk::BUTTON_PRESS_MASK | gdk::BUTTON_RELEASE_MASK).bits() as i32);
```

instead of:
```
operations_icon.add_events(gdk::BUTTON_PRESS_MASK | gdk::BUTTON_RELEASE_MASK);
```

**Comment by EPashkin** [comment]
Possible duplicate #439

**Comment by EPashkin** [comment]
Oops, It not, but not done by same reason.

**Comment by sdroege** [comment]
This is fixed https://github.com/gtk-rs/gtk/commit/f4ad6ffc72b094e2f668d17e5ccd9d2765542d80

@GuillaumeGomez please close :)

**Comment by GuillaumeGomez** [comment]
Yes sir!
