### ISSUE TITLE
Support gtk::Clipboard::request_*

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#479]
Looks like there are a bunch of function pointer aliases that `gir` doesn't understand, but then there is also the data pointer for it that's not understood. `src/auto/clipboard.rs` currently lists one like:

```
//pub fn request_text(&self, callback: /*Unknown conversion*//*Unimplemented*/ClipboardTextReceivedFunc, user_data: /*Unimplemented*/Option<Fundamental: Pointer>) {
//    unsafe { TODO: call ffi::gtk_clipboard_request_text() }
//}
```

**Comment by EPashkin** [comment]
`Pointer` almost always come with some function pointer (ClipboardTextReceivedFunc).
By this reason `request_text` need be done manually.
So supporting type `Pointer` is minor priority.

**Comment by Susurrus** [comment]
@EPashkin So the correct process here is not to implement `ClipboardTextReceivedFunc` and instead manually create `clipboard::request_text()`. I don't understand how to do that by myself, but could probably extrapolate from an example that's already done. Do you know of this already being done for any existing functions?

Also, there isn't a way to get this generated automatically like `load_icon_async`, which has an  automatically-implemented callback type.

**Comment by EPashkin** [comment]
@Susurrus Yes usage `ClipboardTextReceivedFunc` need some manual code, almost same as any signal with trampoline or new async function, at minimum until we think up way to generate this for any `xxFunc`.

**Comment by Susurrus** [comment]
All the `request_*()` function have been implemented, so closing this.
