### ISSUE TITLE
ListStore missing functions, such as the remove

### ISSUE THREAD

**Issue by wyq756543431** [gtk-rs/gtk#482]
ListStore missing functions,such as the remove

**Comment by EPashkin** [comment]
http://gtk-rs.org/docs/gtk/struct.ListStore.html#method.remove
https://github.com/gtk-rs/gtk/blob/master/src/auto/list_store.rs#L99
May be you using old package?

**Comment by wyq756543431** [comment]
I am using  the 0.1.2 version. i know, lastest version  hasn't push.

**Comment by EPashkin** [comment]
Then it have `remove`.
Can you show code and error it produced?

**Comment by wyq756543431** [comment]
There is no error, I'm going to use the remove function.
Thank you!
