### ISSUE TITLE
how to make multiwindow program

### ISSUE THREAD

**Issue by wyq756543431** [gtk-rs/gtk#484]
Can you give an example？thank you.

**Comment by GuillaumeGomez** [comment]
Sure, give us a few days (eventually weeks if you're really unlucky).

**Comment by wyq756543431** [comment]
ok，I wish I was lucky，thank you.

**Comment by EPashkin** [comment]
@wyq756543431 Example good for you?

**Comment by wyq756543431** [comment]
very good!!
