### ISSUE TITLE
Add gtk::Switch.connect_state_notify()

### ISSUE THREAD

**Issue by sanpii** [gtk-rs/gtk#491]
Hello,

According to the documentation is the right way to be notified of state change: https://developer.gnome.org/gtk3/stable/GtkSwitch.html#GtkSwitch-activate

**Comment by EPashkin** [comment]
It already added: http://gtk-rs.org/docs/gtk/struct.Switch.html#method.connect_activate

**Comment by EPashkin** [comment]
Sorry, was wrong.
You meant replace `connect_activate` to connection to [notify signal](https://developer.gnome.org/gobject/stable/gobject-The-Base-Object-Type.html#GObject-notify) or something other?

**Comment by sanpii** [comment]
> You meant replace connect_activate to connection to notify signal or something other?

Not replacing, just adding a solution to be notified.

> Applications should never connect to this signal, but use the notify::active signal.

**Comment by EPashkin** [comment]
How to you mean to add it?

**Comment by sanpii** [comment]
> How to you mean to add it?

Do you have a possibility to add custom code to create a safe method, like [`connect_grab_notify`](https://github.com/gtk-rs/gtk/blob/master/src/auto/widget.rs#L2541)? Or a versatile `ObjectExt::connect_notify` method?
