### ISSUE TITLE
TextTag's style property is wrapped around as if it is a bool

### ISSUE THREAD

**Issue by TomBebb** [gtk-rs/gtk#497]
It should be an enum, and means you can't tag text as italic

**Comment by EPashkin** [comment]
http://gtk-rs.org/docs/gtk/struct.TextTag.html#method.set_property_style_set only shows that style set.
Actual function named `set_property_style` and currently not implemented.

**Comment by EPashkin** [comment]
Thanks for pointing this. I will add functions that depends on pango.
