### ISSUE TITLE
Improving travis builds

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/gtk#50]
As I understand it, travis builds currently use the stock `libgtk-3` from `precise` so don't need the external repo and packages. If so, we can make use of the [containers feature](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) to speed up the builds. The `gtk` packages can be added [in this manner](http://docs.travis-ci.com/user/apt/).

**Comment by GuillaumeGomez** [comment]
Nice found ! I'm just wondering which version of gtk will be used but that's not a big deal I think. Just make the pr, like that we'll be able to test ! =D

**Comment by gkoz** [comment]
Trying this out in #51...
