### ISSUE TITLE
Problem with optional parameters

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gtk#501]
@GuillaumeGomez There runtime problem with https://github.com/gtk-rs/gir/pull/321: this example shows label with emply or bad text
```rust
fn main() {
    if gtk::init().is_err() {
        println!("Failed to initialize GTK.");
        return;
    }

    let label = gtk::Label::new(Some("test text"));
    let window = gtk::Window::new(gtk::WindowType::Toplevel);
    window.set_title("Example");
    window.add(&label);
    window.show_all();

    // GTK & main window boilerplate
    window.connect_delete_event(|_, _| {
                                    gtk::main_quit();
                                    Inhibit(false)
                                });
    gtk::main();
}
```
IMHO this due don't assigning stash to temporary variable

**Comment by GuillaumeGomez** [comment]
I'll look into this issue as soon as possible.

**Comment by EPashkin** [comment]
@GuillaumeGomez CIs passed for all linked PRs.

**Comment by GuillaumeGomez** [comment]
All merged, thanks! :D

**Comment by EPashkin** [comment]
Seems its time to publish next version.
Only https://github.com/gtk-rs/gtk/issues/488 from my list still unsolved.

**Comment by GuillaumeGomez** [comment]
Do you want to wait for it or not?

**Comment by EPashkin** [comment]
IMHO waiting uneeded.

**Comment by GuillaumeGomez** [comment]
Ok, I'll start the release in the next hours. Can you prepare the merged PRs list in this release please? :)

**Comment by EPashkin** [comment]
For all: Option conversion by you

Sys:
https://github.com/gtk-rs/sys/pull/45 Use FFI types for constants, string ends with '/0', bitflags update.  By sdroege
https://github.com/gtk-rs/sys/pull/45 Make all struct fields public, etc. By sdroege
GLib:
https://github.com/gtk-rs/glib/pull/153 Fix array of string full transfer
https://github.com/gtk-rs/glib/pull/154 Fix FromGlibPtrContainer implementations
https://github.com/gtk-rs/glib/pull/155 Convert string constants from FFI
https://github.com/gtk-rs/glib/pull/156 Directly access the GType in the GValue instead of doing raw pointer casting By sdroege
https://github.com/gtk-rs/glib/pull/162 Add support for getting a &str from a GValue without copying
By sdroege

**Comment by GuillaumeGomez** [comment]
@EPashkin: Ok, all PRs ready for the first round. Once I have your approval, I merge and publish.

**Comment by GuillaumeGomez** [comment]
(oh and thanks for the PRs list!)

**Comment by EPashkin** [comment]
Gio:
https://github.com/gtk-rs/gio/pull/20 Generate interface functions
Cairo:
https://github.com/gtk-rs/cairo/pull/118 Scaled font By johncf
https://github.com/gtk-rs/cairo/pull/120, https://github.com/gtk-rs/cairo/pull/122 Proper glib bindings for font types. By johncf
https://github.com/gtk-rs/cairo/pull/127 Make glib dependency optional. By rtsuk
Pango:
https://github.com/gtk-rs/pango/pull/65 Generate more enums and objects.

**Comment by EPashkin** [comment]
For all: remove properties that duplicate direct functions

For glib#162. Add lifetime to FromValue, FromValueOptional

Gdk:
https://github.com/gtk-rs/gdk/pull/140 Fix RGBA. By Bryant Mairs aka Susurrus
https://github.com/gtk-rs/gdk/pull/144 Generate Gdk classes
https://github.com/gtk-rs/gdk/pull/145, https://github.com/gtk-rs/gdk/pull/148 GdkAtom By Susurrus

Gtk:
https://github.com/gtk-rs/gtk/pull/481 Child properties for Box. By antoyo
https://github.com/gtk-rs/gtk/pull/472 Basic drag&drop support. By Susurrus
https://github.com/gtk-rs/gtk/pull/496 Child properties for Notebook. By antoyo

**Comment by GuillaumeGomez** [comment]
Can you run `cargo doc --features=embed-lgpl-docs --all-features` on the gtk crate and then run `cp -r target/doc/* ../docs` (where docs is the gtk/docs repo) please? I don't have a recent enough version of gtk to be able to run it. :-/

**Comment by EPashkin** [comment]
On it

**Comment by GuillaumeGomez** [comment]
Thanks a lot! :)

**Comment by EPashkin** [comment]
Seems I have problem too: on windows gdk/enums/key/constant.A.html and gdk/enums/key/constant.a.html is same file and it different :(

**Comment by EPashkin** [comment]
And I have 685 of those so my docs will be bad

**Comment by EPashkin** [comment]
@GuillaumeGomez you get error on generate or just generated docs is bad ?

**Comment by GuillaumeGomez** [comment]
My version of gdk is 3.20 where we need a higher one.

**Comment by EPashkin** [comment]
Installing zesty on virtual machine, it take some time.
