### ISSUE TITLE
Using ComboBoxExt::set_model() doesn't accept None

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#508]
This results in a compilation error like:
```
   Compiling gattii v0.9.0 (file:///home/susurrus/Projects/gattii)
error[E0282]: type annotations needed
    --> src/bin/gattii.rs:1168:47
     |
1168 |                             ui.ports_dropdown.set_model(None);
     |                                               ^^^^^^^^^ cannot infer type for `P`

error: aborting due to previous error

error: Could not compile `gattii`.

To learn more, run the command again with --verbose.
```

I'm not actually sure how to fix the syntax such that this will compile. Is there anyway to make this more ergonomic? For the C API, just passing `NULL` is sufficient, which is nice and clear.

**Comment by EPashkin** [comment]
Seems rust allow only using something like `None::<&TreeModel>` or separate typed variable

**Comment by Susurrus** [comment]
Yeah, `None::<&gtk::TreeModel>` worked. Thanks!

What do you think about adding a `ComboBoxExt::clear_model()` function so that this syntax can be avoided? I know it's not part of GTK+, but it might make sense for `gtk-rs`.

**Comment by EPashkin** [comment]
Not sure that clearing model needed often, IMHO in most cases it will be replaced with other model

**Comment by Susurrus** [comment]
Alright, then let's go ahead and close this issue.
