### ISSUE TITLE
Support for GtkSourceView

### ISSUE THREAD

**Issue by Palmitoxico** [gtk-rs/gtk#514]
First many thanks to the developers of this neat crate!

I'm developing an application that needs the GtkSourceView widget, but it seems that gtk-rs does not support it right now. This widget is exposed through the GObject Introspection, so I think it must not be hard to add experimental support for it.

Saddly I do not have enough experience in rust and gtk to make it happen right now. Is this feature planned? Someone can show me the necessary steps to implement it?

Thanks,
Augusto Fraga Giachero.

**Comment by GuillaumeGomez** [comment]
Normally, you would just have to add the structs' name into the `Gir.toml` file and then run `make gir`. However, in this case, it seems these functions aren't available in the sys part. I opened the PR [here](https://github.com/gtk-rs/gtk/pull/515) so you can see.

**Comment by Palmitoxico** [comment]
Ok, I've looked your's PR and the @EPashkin reply.
So if the GtkSourceView is an separated library makes more sense to create a new crate for it?

Thanks!

**Comment by GuillaumeGomez** [comment]
You'll need to yes (a sys one and the "normal" one). Take a look at gir to see how to do it. Also, if you want, we can help. Once done, we can also integrate the sourceview crate into gtk-rs, but it's to you.

**Comment by GuillaumeGomez** [comment]
I added it. You can take a look on [crates.io](https://crates.io/crates/sourceview).

**Comment by Palmitoxico** [comment]
Thank you very much!
