### ISSUE TITLE
Make gtk::Application::new more ergonomic

### ISSUE THREAD

**Issue by jeandudey** [gtk-rs/gtk#524]
Currently an application is created like this:

```rust
let app = gtk::Application::new(Some("org.gnome.example"), gio::APPLICATION_FLAGS_NONE);
```

However the signature of `new` could be changed a little bit to accept a `Into<Option<&str>>` allowing us to do this:

```rust
let app = gtk::Application::new("org.gnome.example", gio::APPLICATION_FLAGS_NONE);
```

Or this:

```rust
let app = gtk::Application::new(None, gio::APPLICATION_FLAGS_NONE);
```

**Comment by GuillaumeGomez** [comment]
Ah right. We did it for every generated functions but not for manual ones. Want to do it?

**Comment by jeandudey** [comment]
Yes :D, can you point me what files to change?

**Comment by GuillaumeGomez** [comment]
Here: https://github.com/gtk-rs/gtk/blob/master/src/application.rs#L12-L20

**Comment by mattico** [comment]
This looks to be resolved, at least for feature v3_6. Is there a reason it can't be implemented for the previous versions? The signature looks identical, just need an into().

**Comment by EPashkin** [comment]
Before v3_6 `gtk_application_new` don't allow null as `application_id`
