### ISSUE TITLE
gtk_shortcuts_window_get_type, gdk_window_fullscreen_on_monitor not available on gtk < 3.18

### ISSUE THREAD

**Issue by pgkos** [gtk-rs/gtk#532]
`gtk_shortcuts_window_get_type` is available since gtk+ 3.20
`gdk_window_fullscreen_on_monitor` is available since gtk+ 3.18

When I compile a project using gtk+ 3.16 and `features = ["v3_16"]` I get undefined references to these two symbols.

**Comment by EPashkin** [comment]
Strange, don't see any version for https://developer.gnome.org/gtk3/stable/GtkShortcutsWindow.html.
Second also don't have version but [doc's](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-fullscreen-on-monitor) says `UNRELEASED`

You use git version's? Can you test changes with local copy?

**Comment by EPashkin** [comment]
And where you get starting versions?

**Comment by EPashkin** [comment]
Possible fixed versions
https://github.com/EPashkin/gtk/tree/shorcutwindows_version
https://github.com/EPashkin/gdk/tree/version_of_gdk_window_fullscreen_on_monitor

**Comment by EPashkin** [comment]
@GuillaumeGomez Seems this can be closed, all PRs merged, no resonse from @pgkos  for 2 week.

**Comment by GuillaumeGomez** [comment]
Ok!
