### ISSUE TITLE
get_current_event_device() does not exist

### ISSUE THREAD

**Issue by hasufell** [gtk-rs/gtk#534]
Under http://gtk-rs.org/docs/gtk/fn.get_minor_version.html?search=event_device there are 3 functions:

```rust
gtk::get_current_event_device
gtk::functions::get_current_event_device
gtk_sys::gtk_get_current_event_device
```

Only the one from `gtk_sys` works (for the rest, I get "cannot find function" errors), which is not usable, since it returns types I cannot use.

I am using the latest __gtk-0.1.3__.

**Comment by EPashkin** [comment]
This functions still not published and only present in git version

**Comment by hasufell** [comment]
I don't really know how to use the git version, it causes weird compile errors if I do `gtk = { git = 'https://github.com/gtk-rs/gtk.git' }` like
```
error: native library `gio` is being linked to by more than one package, and can only be linked to by one package

  gio-sys v0.3.4
  gio-sys v0.3.4 (https://github.com/gtk-rs/sys#11344439)
```

When I try to build everything from git it propagates up to a gtk error and I am stuck with gdk-sys and gtk-sys, because they don't seem like they can be built from git directly, since they are subdirectories of a repository.

Very annoying.

**Comment by EPashkin** [comment]
Currently git and package versions for gtk-rs can't be mixed.
You need use other crates from git too,
or just implement function manually as https://github.com/gtk-rs/gtk/blob/master/src/auto/functions.rs#L197-L202

**Comment by hasufell** [comment]
That doesn't really work, I don't have the ffi module. Looks like I have to copy paste half of the project files.

**Comment by EPashkin** [comment]
Strange. 
You just need add `gtk-sys = "^0.3.4"` to `Cargo.toml` and use it in `lib.rs` `extern crate gtk_sys as ffi;`
Instead `ffi` can be any name

**Comment by hasufell** [comment]
Oh, that works, I didn't see it here https://github.com/gtk-rs/gtk/blob/master/src/auto/functions.rs#L22

**Comment by hasufell** [comment]
There's a lot more missing, including in gdk, like `pointer_grab`. Trying to reimplement that yields another ton of errors. I don't really want to go there, is there no other way?

**Comment by EPashkin** [comment]
Other way: don't use crate from `gtk-rs` but `gir` versions.

**Comment by EPashkin** [comment]
*git

**Comment by EPashkin** [comment]
Or you can just wait some time until we publish next versions.

**Comment by hasufell** [comment]
I already tried that and I don't know how to use git versions of `gtk-sys` and `gdk-sys` (need them for some enums), since they are not repositories, but subdirectories in a repository https://github.com/gtk-rs/sys

**Comment by EPashkin** [comment]
Replace dependencies like `gdk = "^0.5.3"` with `gdk = { git = "https://github.com/gtk-rs/gdk" }`
for all used crates from http://gtk-rs.org.
For syses it `gdk-sys = {git = "https://github.com/gtk-rs/sys"}`

**Comment by hasufell** [comment]
Thanks, that works.

Since I expect this will be fixed by the next release, closing.
