### ISSUE TITLE
Wrong function signature or documentation for RadioButton

### ISSUE THREAD

**Issue by RndFooBar** [gtk-rs/gtk#540]
In the documentation of several functions of `gtk::RadioButton`, it is claimed that as an argument, either a fellow 'radio group member' can be given, or `None`. This implies that the argument is meant to be of type `Option<&RadioButton>`. However, the type of the argument is `&[RadioButton]`. 

List of those functions:
* `RadioButton::new`
* `RadioButton::new_with_label`
* `RadioButton::new_with_mnemonic`
* `RadioButton::set_group`

**Comment by EPashkin** [comment]
Can you link these documentation?
Old http://gtk-rs.org/docs/gtk/struct.RadioButton.html#method.new says that argument is group.
Now this API changed in https://github.com/gtk-rs/gtk/pull/529 but still not published.

**Comment by RndFooBar** [comment]
It is from the link you provided:

> Creates a new RadioButton. To be of any practical value, a widget should then be packed into the radio button.
>
> group
>
> __an existing radio button group, or None__ if you are creating a new group.

Same for:

* `RadioButton::new_with_label`: 
>group
>
>an existing radio button group, or None if you are creating a new group.

* `RadioButton::new_with_mnemonic`
>group
>
>the radio button group, or None

* `RadioButton::set_group`
>group
>
>an existing radio button group, such as one returned from RadioButton::get_group, or None.

**Comment by EPashkin** [comment]
"Radio button group" is list of radio buttons (see https://developer.gnome.org/gtk3/stable/GtkRadioButton.html#gtk-radio-button-new), analog in rust was array.

**Comment by RndFooBar** [comment]
Well yes. But the problem is that those functions require a `&[RadioButton]` not a `Option<&RadioButton>` as claimed in the documentation (`an existing radio button group, or None` implies that the argument is an `Option` type). As you said the API changed in #529, but the documentation seems to not have been updated with this change.

**Comment by EPashkin** [comment]
"Radio button GROUP" : array or empty array.
Agree that doc need change when next version published,
until this only mistake is using word "None" instead "empty group".

**Comment by sdroege** [comment]
This seems to be no problem anymore?
