### ISSUE TITLE
#[must_use] for gtk::init?

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk#554]
`#[must_use]` for functions [has been added](https://github.com/rust-lang/rust/pull/43728). Should we add it for `gtk::init`?

**Comment by EPashkin** [comment]
Interesting, 👍 for using it after it go to stable.

**Comment by GuillaumeGomez** [comment]
I'll add a `must_use=true` parameter for `gir` then.

**Comment by EPashkin** [comment]
`gtk::init` is manual function.

**Comment by GuillaumeGomez** [comment]
Then no need for it (less work! \o/).

**Comment by sdroege** [comment]
What should the attribute do here? :)

**Comment by EPashkin** [comment]
As `Result` already have `must_use` IMHO this attribute add nothing to [`gtk::init`](https://github.com/gtk-rs/gtk/blob/master/src/rt.rs#L89)

**Comment by GuillaumeGomez** [comment]
It made sense to me at the time. Not much now. :p
