### ISSUE TITLE
gtk_init() shouldn't need to be explicit on app side

### ISSUE THREAD

**Issue by philn** [gtk-rs/gtk#555]
Dixit @sdroege  :)

**Comment by sdroege** [comment]
This is only for applications using GtkApplication, which is automatically calling gtk_init(). Currently these applications still have to call gtk_init() manually because gtk-rs is doing some custom initialization (mostly remembering on which thread it was initialized, nothing actually useful...).

**Comment by Susurrus** [comment]
Is this problem solved at this point? None of the examples call this function anymore using the newer `gtk::ApplicationWindow::new()` way of initializing things.

**Comment by sdroege** [comment]
Solved, yes
