### ISSUE TITLE
Add WindowExt to the prelude

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#561]
I just upgraded to 0.2 from 0.1.3 and `set_title` was no longer found for me calling it on a `Window`. i therefore had to import `WindowExt` as part of the upgrade. I was surprised this wasn't included in the prelude. Was this intentional or would it be reasonable to get this included in the prelude as well?

**Comment by EPashkin** [comment]
It same as https://github.com/gtk-rs/glib/issues/211, we missed this trait name duplicate.
IMHO this need be GtkWindowExt by same [reason](https://github.com/gtk-rs/pango/pull/89#issuecomment-320460704).
See https://github.com/gtk-rs/gtk/pull/551 as fix example
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
@EPashkin: You mean reexporting it as `GtkWindowExt` or declaring it as `GtkWindowExt`?

**Comment by EPashkin** [comment]
I meant use `trait_name="GtkWindowExt"` to gtk's trait to rename it.
Or we can do same in Gdk

**Comment by GuillaumeGomez** [comment]
As you prefer.

**Comment by EPashkin** [comment]
Ok, I will do it on Gtk this evening and update lgpl-docs too.

**Comment by GuillaumeGomez** [comment]
Thanks! :)
