### ISSUE TITLE
Docs: gtk::Revealer is missing gtk::RevealerExt trait

### ISSUE THREAD

**Issue by treenix** [gtk-rs/gtk#563]
The [gtk::RevealerExt](http://gtk-rs.org/docs/gtk/trait.RevealerExt.html) trait is not listed under [implements](http://gtk-rs.org/docs/gtk/struct.Revealer.html#implements).

**Comment by nt8r** [comment]
This no longer seems to be the case. Can someone close this bug? cc @GuillaumeGomez

**Comment by sdroege** [comment]
Thanks for checking!
