### ISSUE TITLE
Segfault on Fixed get_child_x

### ISSUE THREAD

**Issue by serpilliere** [gtk-rs/gtk#565]
Hi!

The `gtk::Fixed` `get_child_x` segfaults if the user provides a widget which does not belong to the `Fixed` widget. Here is an example code:

```rust

extern crate gtk;
use gtk::prelude::*;

fn main() {
    if gtk::init().is_err() {
        println!("Failed to initialize GTK.");
        return;
    }

    let window = gtk::Window::new(gtk::WindowType::Toplevel);
    let container = gtk::Fixed::new();

    let button1 = gtk::Button::new_with_label("Button 1");
    let button2 = gtk::Button::new_with_label("Button 2");
    container.add(&button1);

    // Segfault Here
    let _ = container.get_child_y(&button2);

    window.set_title("Test program");

    window.connect_delete_event(|_, _| {
        gtk::main_quit();
        Inhibit(false)
    });

    window.add(&container);
    window.show_all();

    gtk::main();
}
```

Maybe a panic should be done if the native gtk returns null pointer ?

**Comment by EPashkin** [comment]
Thanks for noticing this, I try fix it later.
Not sure that it gtk-rs error as for box it just return default value
```
let vbox = gtk::Box::new(Vertical, 0);
let button = Button::new();
assert_eq!(0, vbox.get_child_padding(&button));
```

**Comment by GuillaumeGomez** [comment]
I have an idea on how to check this. It's almost done but we won't be able to generate it automatically I think. :-/

**Comment by EPashkin** [comment]
Upstream bug filled https://bugzilla.gnome.org/show_bug.cgi?id=787028, but I don't know how to fix it with minimal change.

**Comment by GuillaumeGomez** [comment]
Thanks for doing it!

**Comment by EPashkin** [comment]
Upstream bug closed with status NOTABUG:
```
Matthias Clasen [gtk+ developer]  2017-09-01 23:26:06 UTC
Asking for child properties of non-children is a programming error. Don't do it. 
```

**Comment by GuillaumeGomez** [comment]
That's... stupid? They can just check like they do it `Box`...

**Comment by serpilliere** [comment]
Erf. 
I agree with the "dont do it" part, but as he said, "it's a programming error" so deal with the error.

I my opinion, it's not consistent with others GTK choices: for example If you add a widget to a layout, and add the same widget to another layout, GTK will display an error message at run time.
It does not *segfault*.
But the same argument could have been answered here: don't do it.

Quite strange answer here.
