### ISSUE TITLE
no function or associated item named `load_from_resource` found for type `gtk::CssProviderExt` in the current scope

### ISSUE THREAD

**Issue by bram209** [gtk-rs/gtk#567]
Hi, Im trying to load a gresource file, so I can use a precompiled gtk theme in my application.
According to the docs, the `load_from_resource` function should be there. What am I missing here?

p.s. new to both rust & gtk, sorry for my ignorance.

My code:
```rust
    let css_provider = CssProvider::new();
    gtk::CssProviderExt::load_from_resource(&css_provider, format!("{}/gtk.gresource", theme_path).as_ref());
    
     if css_provider.load_from_path(format!("{}/gtk-dark.css", theme_path).as_ref()).is_err() {
           //...
```

Error:
```bash
no function or associated item named `load_from_resource` found for type `gtk::CssProviderExt` in the current scope
```

**Comment by EPashkin** [comment]
Sorry, [docs](http://gtk-rs.org/docs/gtk/trait.CssProviderExt.html#tymethod.load_from_resource) still don't shows that it need enable feature "v3_16" for gtk crate.

**Comment by GuillaumeGomez** [comment]
Might be worth I add it!

**Comment by EPashkin** [comment]
This need adding manual docs for functions (at minimum to all that have features) or fix rustdoc to show features to functions without doc comment

**Comment by bram209** [comment]
tanks
