### ISSUE TITLE
Build failure on linux

### ISSUE THREAD

**Issue by pwil3058** [gtk-rs/gtk#573]
I get the following error on linux:

~/SRC/LearnRust/gtktest $ cargo build
   Compiling gio v0.2.0
   Compiling c_vec v1.2.1
   Compiling gtk v0.2.0
   Compiling gdk-pixbuf v0.2.0
   Compiling libc v0.2.30
   Compiling pkg-config v0.3.9
   Compiling gdk v0.6.0
   Compiling bitflags v0.9.1
   Compiling lazy_static v0.2.8
   Compiling cairo-rs v0.2.0
   Compiling gtk-sys v0.4.0
   Compiling cairo-sys-rs v0.4.0
   Compiling glib-sys v0.4.0
   Compiling gobject-sys v0.4.0
   Compiling gdk-pixbuf-sys v0.4.0
   Compiling atk-sys v0.4.0
   Compiling gdk-sys v0.4.0
   Compiling pango-sys v0.4.0
   Compiling gio-sys v0.4.0
error: failed to run custom build command for `glib-sys v0.4.0`
process didn't exit successfully: `/home/peter/SRC/LearnRust/gtktest/target/debug/build/glib-sys-f3e9083a12e9d477/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "glib-2.0 >= 2.32"` did not exit successfully: exit code: 1
--- stderr
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'glib-2.0', required by 'virtual:world', not found

warning: build failed, waiting for other jobs to finish...
error: build failed

My toml file contains:

[package]
name = "gtktest"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]

[dependencies.gtk]
version = "0.2.0"
features = ["v3_10"]

**Comment by EPashkin** [comment]
What version of glib package installed?
What return these commands?
```
pkg-config glib-2.0 --modversion
pkg-config glib-2.0 --libs --cflags
```

**Comment by pwil3058** [comment]
pkg-config doesn't seem to know anything about glib-2.0 or anything else as it returns nothing when I do:

pkg-config list-all

I have Fedora-26 installed and both the x86_64 and i686 versions of glib-2.52.3 are installed.

**Comment by EPashkin** [comment]
Seems you don't have developer packages installes, see http://gtk-rs.org/docs-src/requirements.html
Or try set environment variable `GTK_LIB_DIR` to path of dynamic libraries.

**Comment by pwil3058** [comment]
You were correct.  They weren't installed.  I use the Python3 bindings for my GTK programming (much easier to use than the C API and no discernible performance penalty) and they aren't needed there.

Anyway, build without error now.

Thanks for your help,
Peter
