### ISSUE TITLE
ResponseType enum should impl PartialEq<i32>

### ISSUE THREAD

**Issue by Redrield** [gtk-rs/gtk#578]
At the moment, the return type of `Dialog::run()` is an `i32`, though it can be compared against built in button type responses via the `ResponseType` enum. The problem is that there isn't a direct `Eq` relationship between the two, so the only option is to compare with `ResponseType::into()` like so

```Rust
let dialog = MessageDialog::new(None::<&Window>, DialogFlags::empty(), MessageType::Info, ButtonsType::YesNo, "Click a button");
let res = dialog.run();

if res == ResponseType::Yes.into() {
    println!("Something here");
} else {
    println!("Something else here");
}
```

A solution would be to add an impl of PartialEq<i32> to ResponseType, so that `into()` could be omitted (I also believe this would make it possible to compare using ResponseType in `match` statements.

**Comment by GuillaumeGomez** [comment]
Or to make the function directly return the expected type. From the gitter discussion, it seems that the value returned can be a custom one so I think we'll need to wrap the enum with another enum which has a `Custom(i32)` variant.

**Comment by sdroege** [comment]
This is solved now, there are even `From`/`Into` impls to go from/to `i32` now.
