### ISSUE TITLE
Custom icon does not appear in the launch bar when starting a gtk-rs application

### ISSUE THREAD

**Issue by hadrien-psydk** [gtk-rs/gtk#579]
Hello,

I'm using Ubuntu 17.10 which is based on Gnome and I have a problem with the application icon displayed in the launch bar when I start a gtk-rs based program.

I wrote the smallest possible program in Rust with gtk-rs to display a window. I wrote the exact same program in C++.

I also created an icon and a .desktop file that references that icon and the executable produced either in Rust or C++. I copied the executable, the .desktop and the icon to suitable locations in order to create a registered application in my system.

When I launch the program, the launch bar should show the icon specified by the .desktop file. It works with the C++ version, but not with the Rust version. Instead, I get the default icon when an application does not provide a custom one.

The test case I wrote is available there: https://github.com/hadrien-psydk/gtk-icon-bug

I've been investigating that problem for a long time now and hopefully you will help me understand why there are these different behaviors between Rust and C++. I apologize in case it appears the problem is not related to gtk-rs. I verified another program (not written by me) that uses gtk-rs and it exposes the same behavior.

**Comment by GuillaumeGomez** [comment]
That's actually a good question. Maybe there's an environment variable provided on the C++ side which isn't on the rust one? It's hard to say... Maybe you have more idea about this @sdroege?

**Comment by sdroege** [comment]
I'll take a look in the next days. Can't think of anything obvious causing this

**Comment by tmiasko** [comment]
It looks like this part of pre_init breaks the program name: https://github.com/gtk-rs/gtk/blob/697488688e64797e3f445b7947c6f033eab2c2dc/src/rt.rs#L140-L143

One possible workaround is to initialize gtk manually:

```rust
extern crate glib;
extern crate gtk;
extern crate gtk_sys as gtk_ffi;
extern crate libc;

use gtk::prelude::*;
use gtk::{Window, WindowType};
use glib::translate::from_glib;
use glib::translate::ToGlibPtr;

fn main() {
    let argv = std::env::args().collect::<Vec<String>>();
    let mut argc = argv.len() as libc::c_int;
    let mut argv_stash = argv.to_glib_none();
    let success: bool = from_glib(unsafe { gtk_ffi::gtk_init_check(&mut argc, &mut argv_stash.0) });
    if !success {
        println!("Failed to initialize GTK.");
        return;
    }

    unsafe { gtk::set_initialized(); }

    let window = Window::new(WindowType::Toplevel);
    window.set_title("tinygtkrs");

    window.connect_delete_event(|_, _| {
        gtk::main_quit();
        Inhibit(false)
    });
    window.show_all();
    gtk::main();
}
```

**Comment by sdroege** [comment]
Why don't we either pass the correct argv/argc to `gtk_init`, or at least carry over `argv[0]`? Both would trivially solve this problem.
I assume we don't pass the correct arguments so that GTK does not do things based on them but we want to leave this for the application to decide? But then OTOH we must do that for `GApplication` anyway.

So maybe there should be a) a new initialization function that takes a `&[str]` for the arguments and b) the current one should pass through `argv[0]`. Agreed?

@GuillaumeGomez ?

**Comment by GuillaumeGomez** [comment]
We had issues over this in the past so I was sure we did this change in order to let users provide `&[&str]`... (ah no, it has only be done `ApplicationWindow::run`). So yes, we should definitely allow users to pass `argv` themselves!

**Comment by sdroege** [comment]
Ok, so someone can prepare a PR to a) Pass `argv[0]` correctly in the current function and b) add a new init function that consumes a user-provided slice of strings for the arguments.

**Comment by GuillaumeGomez** [comment]
If no one does, I have the next week fully focused on gtk-rs so I'll. :)

**Comment by Barugon** [comment]
I get no icon or app name in Fedora 29 and no app name (icon works though) in Ubuntu 18.10. Here how I'm initializing gtk:
```rust
fn main() {
  let app = gtk::Application::new("org.barugon.cota", gio::ApplicationFlags::empty())
    .expect("Initialization failed!");

  app.connect_startup(|app| ui::layout(app));
  app.connect_activate(|_| {});
  app.run(&env::args().collect::<Vec<_>>());
}
```
And here's how I'm setting up the main window and icon:
```rust
  // Initialize the application window.
  let window = gtk::ApplicationWindow::new(app);
  window.set_title(DESCRIPTION);
  window.set_resizable(false);
  window.set_default_size(WIN_WIDTH, WIN_HEIGHT);
  window.connect_delete_event(|win, _| {
    win.destroy();
    Inhibit(false)
  });

  // Set the window's icon.
  let icon_data = include_bytes!("../res/icon.png");
  let pixbuf_loader = PixbufLoader::new();
  if pixbuf_loader.write(icon_data).is_ok() {
    if let Some(icon) = pixbuf_loader.get_pixbuf() {
      window.set_icon(&icon);
    }
  }
  pixbuf_loader.close().is_ok();
```
The full project is here:
https://github.com/Barugon/CotA

**Comment by sdroege** [comment]
Still a problem, we should pass things to `gtk::init()`.

**Comment by sdroege** [comment]
Should be fixed by https://github.com/gtk-rs/gtk/pull/1056
