### ISSUE TITLE
handle-local-options and command-line signals not available

### ISSUE THREAD

**Issue by russel** [gtk-rs/gtk#580]
It seems that gtk-rs does not expose the `handle-local-options` and `command-line` signals to applications. gtkmm and gtkd both expose these signals, as does gtk itself, to allow command line parameter handling. gtk-rs should allow:
```
application.connect_handle_local_options(|app|{
…
});
application.connect_command_line(|app|{
…
});
```

**Comment by EPashkin** [comment]
Yes, it don't generated https://github.com/gtk-rs/gio/blob/master/src/auto/application.rs#L156-L159
First due `GLib.VariantDict` that have some problem with generation due `VariantType/VariantTy` difference,
Second due ignored `ApplicationCommandLine`, that can deignored.

**Comment by sdroege** [comment]
Fixed in gio long ago
