### ISSUE TITLE
Create bindings for GDL

### ISSUE THREAD

**Issue by Miridyan** [gtk-rs/gtk#586]
Gtk is still lacking a the ability to create dockable toolbars and dialogs.

https://developer.gnome.org/gdl/3.22/

**Comment by GuillaumeGomez** [comment]
I'll check if it can be generated with gir as soon as I can.

**Comment by LaylConway** [comment]
Is there any update on this? I've got a use case where GDL would come in handy as well.

**Comment by sdroege** [comment]
I'm not aware of anyone working on this, so feel free to take it up! https://gtk-rs.org/docs-src/tutorial/gir_tutorial might be helpful.

**Comment by sdroege** [comment]
New bindings for non-platform GNOME libraries would be better placed in https://gitlab.gnome.org/World/Rust
