### ISSUE TITLE
Install procedure GTK.rs on windows, is linking to global installed gtk libraries optimal?

### ISSUE THREAD

**Issue by saolof** [gtk-rs/gtk#587]
The install procedure for GTK.rs on windows seems to be a major source of difficulty, with many issues popping up here from people stuck at various points in the install process, with very different fixes being the solution for different users despite identical error messages.

By comparison, GTK.jl which does the same thing for Julia as GTK.rs does for Rust is extremely easy to get running, the install procedure over there is just typing >>Pkg.add("Gtk") into the Julia repl and everything works out of the box, which is a major difference in terms of usability.

Are there any alternatives to the current state of affairs where the user is supposed to download the binaries himself using a complicated MSYS process, setting up the path, and praying that the windows install won't set up any barriers? Afaik, GTK.jl does a similar thing behind the scenes, but has winrpm ( https://github.com/JuliaPackaging/WinRPM.jl ) do all the hard work for you. The final location of the GTK binaries installed by that process is in a dependencies folder inside the WinRPM folder in the Julia dependencies folder, which ends up being consistent and reproducible in every Julia install so that one doesn't need to fiddle around with the path.

**Comment by anderejd** [comment]
I'm keeping my eye on this project but I'm hesitant to try it because of this very reason, the unusual dependency handling (on windows). When building for windows I would like to get all non-system DLLs in the rust target/release directory when building to allow running and distributing without installing any libraries system-wide.

**Comment by GuillaumeGomez** [comment]
The main problem is that most of `gtk-rs` developers don't use windows... (or maybe @EPashkin is?) If anyone some day develops something to allow making this is easy, we'll all be very happy.

**Comment by Miridyan** [comment]
Unfortunately, I haven't had much luck with just copying libraries into the build directory on windows. The best method I've found for building `gtk-rs` is installing `gtk` with MSYS2 and then adding the included `lib`, `bin`, and `include` directories to my system path.

**Comment by anderejd** [comment]
Anyone here got some experience with GTK+ in combination with the msvc toolchain? Either with C/C++ or Rust? If yes, in which combination did you end up distributing your application and GTK+-DLLs? Sorry for the noise if this is too off-topic.

**Comment by zoumi** [comment]
http://www.tarnyko.net/dl/
Here are runtimes and develop files.

**Comment by sdroege** [comment]
As this is a general GTK question and not even a bug report  or feature request, this is best discussed at https://discourse.gnome.org/
