### ISSUE TITLE
Lots of `Clipboard` functionality missing.

### ISSUE THREAD

**Issue by Binero** [gtk-rs/gtk#591]
Most of the functionality for `Clipboard` is missing.

Examples:

- `ClipboardExt::set_with_data`
- `ClipboardExt::set_with_owner`
- `ClipboardExt::request_contents`
- `ClipboardExt::request_text`

**Comment by GuillaumeGomez** [comment]
We're not very good with callbacks autogeneration for the moment... You can add them if you need them though! :)

**Comment by Binero** [comment]
How would this typically be done? Change the transpiler or hard-code them?

**Comment by GuillaumeGomez** [comment]
Hard-code them. We actually have both. You can take a look in the `src` directory. Everything in there is "manual implementation". The "generated" files are in `src/auto`.

**Comment by Susurrus** [comment]
Looks like the other 3 functions have been implemented, so `set_with_owner()` is the only part of this still missing.

**Comment by YaLTeR** [comment]
Looks like `request_uris()` is missing; how do I go about adding that?

**Comment by sdroege** [comment]
> Looks like `request_uris()` is missing; how do I go about adding that?

You'd add a manual implementation for it in `src/clipboard.rs`. Looks relatively straightforward, just ask here if you run into problems @YaLTeR

**Comment by YaLTeR** [comment]
Oh, but I did, 16 days ago 🙃 https://github.com/gtk-rs/gtk/pull/1061

**Comment by sdroege** [comment]
Oh, even better :rofl: Thanks!
