### ISSUE TITLE
Add NativeDialog, FileChooserNative

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/gtk#592]
Currently we don't bind NativeDialog nor FileChooserNative.  This is needed for flatpak apps in general, and for better integration with the native file dialog in other platforms.

**Comment by federicomenaquintero** [comment]
I'm implementing this, BTW.

**Comment by Phrohdoh** [comment]
@federicomenaquintero Hey, has there been any progress on this?

I'm looking forward to using `FileChooserNative`! :)

**Comment by federicomenaquintero** [comment]
Sorry, nothing yet!  I dropped the ball on this.  Here is my branch.  I don't remember what state it was in; I think it just adds FileChooserNative and NativeDialog to Gir.toml.

https://github.com/federicomenaquintero/gtk/tree/native-dialog

**Comment by GuillaumeGomez** [comment]
They're actually both there (and generated). I'll close this PR then.

**Comment by federicomenaquintero** [comment]
Yay!

**Comment by Phrohdoh** [comment]
Are the intentionally hidden from rustdoc?

https://docs.rs/gtk/0.3.0/gtk/?search=FileChooserNative

**Comment by GuillaumeGomez** [comment]
They're not in the current released version. It'll be in the next one. You can have them by targetting `master` directly though if you want.
