### ISSUE TITLE
On windows gtk::init() fails with entry point not found errors

### ISSUE THREAD

**Issue by madmaxio** [gtk-rs/gtk#593]
On windows gtk::init() fails with entry point not found errors:

cairo_win32_surface_create_with_format not found in DLL C:\msys64\mingw64\bin\libgdk-3-0.dll

g_getenv not found in DLL C:\msys64\mingw64\bin\libatk-1.0.-0.dll

**Comment by GuillaumeGomez** [comment]
cc @EPashkin (since you have a windows :stuck_out_tongue: )

**Comment by EPashkin** [comment]
Don't see `cairo_win32_surface_create_with_format` in `cairo`, `gdk`.  Where you get that name?
Windows version of `g_getenv` named `g_getenv_utf8` and it in `libglib-2.0-0.dll` (with just `g_getenv`).

**Comment by EPashkin** [comment]
Oh, forgot read issue title :(
This very strange

**Comment by madmaxio** [comment]
Well i googled cairo issue, https://bugs.freedesktop.org/show_bug.cgi?id=92771
Somehow it looks like i habe older version of it installed, but I have no idea how to fix, because i used pacman to install gtk

**Comment by EPashkin** [comment]
@madmaxio This error repeated on https://github.com/gtk-rs/examples/blob/master/src/bin/basic.rs ?

**Comment by madmaxio** [comment]
Yes, behavior is exactly same.

**Comment by EPashkin** [comment]
What says `https://github.com/gtk-rs/examples/blob/master/src/bin/basic.rs` in mingw64 prompt ?

**Comment by EPashkin** [comment]
Sorry, was wrong copy.

**Comment by EPashkin** [comment]
Also what pathes return `where libgtk-3-0.dll` in windows command prompt.

**Comment by madmaxio** [comment]
It is C:\msys64\mingw64\bin\libgtk-3-0.dll

**Comment by EPashkin** [comment]
Seems your messages missleading, `cairo_win32_surface_create_with_format` present in cairo and used in `gdk`.

**Comment by EPashkin** [comment]
And what says pkg-config? It can be run from windows command-line too.

**Comment by EPashkin** [comment]
`where libgtk-3-0.dll` seems normal, try run it from place where you run `cargo`,
also with libcairo-2.dll, libgdk-3-0.dll, libglib-2.0-0.dll, libatk-1.0-0.dll it all must point to same directory.

**Comment by madmaxio** [comment]
pkg-config --libs libgtk-3-0.dll

Package libgtk-3-0.dll was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgtk-3-0.dll.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgtk-3-0.dll' found

**Comment by madmaxio** [comment]
where libcairo-2.dll

C:\gstreamer\1.0\x86_64\bin\libcairo-2.dll
C:\msys64\mingw64\bin\libcairo-2.dll

where libgdk-3-0.dll

C:\msys64\mingw64\bin\libgdk-3-0.dll

where libglib-2.0-0.dll

C:\gstreamer\1.0\x86_64\bin\libglib-2.0-0.dll
C:\msys64\mingw64\bin\libglib-2.0-0.dll

where libatk-1.0-0.dll

C:\msys64\mingw64\bin\libatk-1.0-0.dll

I did some gstreamer stuff earlier, looks like this is the problem (two places for libcairo-2.dll)?

**Comment by EPashkin** [comment]
Yes, seems `gstreamer` has old cairo and atk.

**Comment by EPashkin** [comment]
Check `pkg-config --modversion cairo gtk+-3.0 gdk-3.0` just in case
But IMHO better way change your %PATH% variable that gstreamer will be after mingw64

**Comment by madmaxio** [comment]
Wow, it worked! Thx a lot!

**Comment by GuillaumeGomez** [comment]
@EPashkin: We should maybe add a "troubleshot" section for windows on gtk-rs.org, don't you think?

**Comment by EPashkin** [comment]
Not sure about it, there too many way to broke windows installation.
