### ISSUE TITLE
gtk::PrintOperation:  I can't find bindings for this struct

### ISSUE THREAD

**Issue by pwil3058** [gtk-rs/gtk#595]
I can find gtk::PrintContext and gtk::PrintSettings but I can't find gtk::PrintOperation.  Is there something else that provides that functionality?

**Comment by EPashkin** [comment]
@pwil3058  Now PrintOperation even on crates: http://gtk-rs.org/docs/gtk/struct.PrintOperation.html

**Comment by pwil3058** [comment]
I'd like to report that I've just implemented the printing of Pango markup text in my application using this interface.  So, thanks and well done.
