### ISSUE TITLE
Advice : Mutable shared state with gtk

### ISSUE THREAD

**Issue by gbip** [gtk-rs/gtk#605]
Hello,
I hope this is the good place to ask such a question.
I am in the process of porting a simple C++ application to Rust, and I am struggling.
Here is my problem :
> There is a variable of type Option<TcpStream> that depends of some user action (clicking on a button for example).
> This variable needs to be passed to a gtk::idle_add closure when a callback for an other button is called. 
> Moreover this variable is also used in some other buttons_callback.

So I started wrapping it in `Rc` and `RefCell` but I couldn't figure out if I should do :
`Rc<RefCell<Option<TcpStream>>>>` or `Option<Rc<TcpStream>>`.

Also, the TcpStream is never mutated, only the option is.

Do you have tips to make this feel more *rustic* ?

**Comment by antoyo** [comment]
Using `Rc<RefCell<T>>` is the way to go with `gtk-rs`.
However, you might be interested in using [`relm`](https://github.com/antoyo/relm), an idiomatic GUI library based on `gtk-rs` that [I created mostly because of this issue](http://relm.ml/relm-intro).

**Comment by gbip** [comment]
I will take a look, thanks !
