### ISSUE TITLE
Change connect_* to FnMut

### ISSUE THREAD

**Issue by spacekookie** [gtk-rs/gtk#606]
I have the following piece of code

```rust
let mut draw_pass = 0;
draw_area.connect_draw(move |_self, ctx| {
    // ... 

    draw_pass += 1;
    // whatever
}
```

But that's throwing an error: `cannot assign to captured outer variable in an 'Fn' closure`.

From what I could gather this shouldn't happen if the closure I pass into `connect_draw` were a FnMut which is why I'm opening this ticket 😉 

Not sure if there is a more elegant way of doing this. If so, please let me know

**Comment by EPashkin** [comment]
Try use [Cell](https://doc.rust-lang.org/std/cell/struct.Cell.html) or [one of atomic](https://doc.rust-lang.org/std/sync/atomic/index.html).

**Comment by spacekookie** [comment]
Ah damn, thanks. I tried a Box but that didn't work. I guess that kinda solves that issue, so I guess I'll close it again. 

Maybe someone else finds it useful 😅

**Comment by quadrupleslap** [comment]
Note for anyone else who has this issue:

For anything that isn't `Copy`, you should use `RefCell`, but make sure your event handler doesn't trigger itself while the contents of the `RefCell` are being borrowed - as long as you ensure that doesn't happen, you won't get a borrowing error.
