### ISSUE TITLE
CellRendererText is missing its "alignment" property

### ISSUE THREAD

**Issue by genodeftest** [gtk-rs/gtk#608]
Setting text alignment for a Gtk.CellRenderer is not possible right now because gtk-rs's `gtk::CellRendererTextExt` misses support for `set_property_alignment`. This seems to affect all properties with GObject.ParamFlags.EXPLICIT_NOTIFY set.

Compare, for example, these documents:
* [GtkCellRendererText on official docs](https://developer.gnome.org/gtk3/stable/GtkCellRendererText.html#GtkCellRendererText.properties) (only shows Read/Write flags on properties)
* [gtk::CellRendererTextExt](http://gtk-rs.org/docs/gtk/trait.CellRendererTextExt.html) misses some properties
* [Gtk.CellRendererText on Python GI docs](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/CellRendererText.html#properties) shows all properties.

Since those flags are available in Python, I guess this is not a bug in GIR.

This first came up in GuillaumeGomez/process-viewer#62.

**Comment by genodeftest** [comment]
> This seems to affect all properties with GObject.ParamFlags.EXPLICIT_NOTIFY set.

That explanation looks too simple, as gtk::Window's `attached_to` is fine.

**Comment by EPashkin** [comment]
It because `CellRenderer` have `get_alignment/set_alignment` so gir think that it don't need in descendants.

**Comment by EPashkin** [comment]
I will try fix this

**Comment by genodeftest** [comment]
Is it possible that this property is now being ignored? When running the following code, the table column is rendered in monospaced font, but it is not aligned right:

    let renderer = gtk::CellRendererText::new();
    renderer.set_property_alignment(Alignment::Right);
    renderer.set_property_family(Some("Monospace"));

**Comment by genodeftest** [comment]
Oh, sorry, I was wrong. The issue is somewhere else.
