### ISSUE TITLE
Path to complete implementation of TreeSortableExt?

### ISSUE THREAD

**Issue by Phrohdoh** [gtk-rs/gtk#612]
I see that both `set_default_sort_func` and `set_sort_func` of [TreeSortableExt](https://github.com/gtk-rs/gtk/blob/1efdfd8d9a9bafcd0c4f5c87816bbecc3930a1eb/src/auto/tree_sortable.rs) are unimplemented.

Are there technical reasons for this or is it "because no one has written them yet?"

If the latter would a gtk-rs member be available for mentoring the implementation of these functions?

**Comment by GuillaumeGomez** [comment]
NO, it's a bit complicated to implement and isn't a priority for the moment. The problem being the `FundamentalPointer` type.

**Comment by cdepillabout** [comment]
`set_default_sort_func` and `set_sort_func` appear to be implemented in `TreeSortableExtManual` now, so I think this issue can be closed:

https://gtk-rs.org/docs/gtk/prelude/trait.TreeSortableExtManual.html

**Comment by sdroege** [comment]
Indeed, thanks for noticing. @GuillaumeGomez this can be closed :)
