### ISSUE TITLE
Create window in thread that's not the main-thread on Mac OSX?

### ISSUE THREAD

**Issue by michael-p** [gtk-rs/gtk#614]
Dear all,

I would like to run all GTK-related stuff in a thread that's not the applications main thread (i.e. the thread that runs `main()`) but although I do not get any error messages the created window simply does not show up. Example:
```rust
extern crate gio;
extern crate gtk;

use gtk::prelude::*;

use gtk::{Window, WindowType};

fn app_main() {
    if gtk::init().is_err() {
        println!("Failed to initialize GTK.");
        return;
    }

    let window = Window::new(WindowType::Toplevel);
    window.set_title("First GTK+ Program");
    window.set_default_size(350, 70);

    window.show_all();

    window.connect_delete_event(|_, _| {
        gtk::main_quit();
        Inhibit(false)
    });

    gtk::main();
}

fn main() {
    // This does not show any window at all:
    std::thread::spawn(|| app_main()).join().unwrap();

    // If uncommented, this works fine:
    // app_main();
}
```

I remember reading somewhere that on Mac OS X GUI related things in general have to happen on the main-thread so this cannot work. Is this correct and applies to GTK as well? Is there a work-around?

Thanks!
Michael

**Comment by GuillaumeGomez** [comment]
It's recommended to use `ApplicationWindow` instead. Maybe it'll solve your problem? (didn't take a deeper look, I'll if your problem persists)

**Comment by michael-p** [comment]
Does not seem like it does, sadly. Here is the same example rewritten with `ApplicationWindow`, same behavior as above:
```rust
extern crate gio;
extern crate gtk;

use gtk::prelude::*;
use gio::prelude::*;

fn build_ui(application: &gtk::Application) {
    let window = gtk::ApplicationWindow::new(application);

    window.set_title("First GTK+ Program");
    window.set_border_width(10);
    window.set_position(gtk::WindowPosition::Center);
    window.set_default_size(350, 70);

    let window_clone = window.clone();
    window.connect_delete_event(move |_, _| {
        window_clone.destroy();
        Inhibit(false)
    });

    window.show_all();
}

fn app_main() {
    let application = gtk::Application::new("com.github.basic", gio::ApplicationFlags::empty())
        .expect("Initialization failed...");

    application.connect_startup(|app| {
        build_ui(app);
    });
    application.connect_activate(|_| {});

    application.run(&std::env::args().collect::<Vec<_>>());
}

fn main() {
    std::thread::spawn(|| app_main()).join().unwrap(); // does not work

    // This works:
    // app_main();
}
```

**Comment by quadrupleslap** [comment]
> Is this correct and applies to GTK as well?

Yes, you need to do GUI work on the main thread. In this case, can't you just run the main application logic on another thread instead?

**Comment by michael-p** [comment]
It would be more difficult. But ok, I was already expecting this to be a GTK problem about which you can't do anything, so closing this for now.

**Comment by quadrupleslap** [comment]
I'm being a bit pedantic, but it's more of a Cocoa problem, not a GTK problem.
