### ISSUE TITLE
Linking errror on Windows

### ISSUE THREAD

**Issue by madmaxio** [gtk-rs/gtk#624]
I succeded before with building gtk apps, perhaps some deps changed since that time?

 = note: gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\crt2.o: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\rsbegin.o: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libtest-8696d5fea1e20e35.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libterm-4712430afdea17f6.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libgetopts-70120a77570a215f.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libstd-f6e2104a2af2f679.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libpanic_unwind-ddddbd65a00d6fe1.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libunwind-bdcc8e731f44c218.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\liblibc-7e5071f576265b08.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\liballoc_system-1bab1d66346bd0c0.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\liballoc-932667b3dd70d77d.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libstd_unicode-9feb59e5b3a1de14.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libcore-aced3c4b55c3c2e7.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libcompiler_builtins-f85525d700589ebd.rlib: No such file or directory
          gcc.exe: error: C:\Users\Максим\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\rsend.o: No such file or directory

**Comment by GuillaumeGomez** [comment]
cc @EPashkin

**Comment by EPashkin** [comment]
It almost clear that some rustup error: `Максим.rustup` instead of `Максим\.rustup`
For me with english user name `rustc 1.25.0-nightly (45fba43b3 2018-02-10)` works normally.
Maybe it because user name in russian?
You tried `cargo clean` before build ?

**Comment by madmaxio** [comment]
Yeah, seems like it is not related to GTK, and files do exist on disk, Thx for help.
