### ISSUE TITLE
Compiling on windows

### ISSUE THREAD

**Issue by madmaxio** [gtk-rs/gtk#625]
So I fixed the issue with russian user name, GTK_LIB_DIR is set. Now getting this on compiling:

ld: cannot find -lgtk-3
          ld: cannot find -lgdk-3
          ld: cannot find -latk-1.0
          ld: cannot find -lgdk-3
          ld: cannot find -lcairo
          ld: cannot find -lpango-1.0
          ld: cannot find -lgdk_pixbuf-2.0
          ld: cannot find -lgio-2.0
          ld: cannot find -lgobject-2.0
          ld: cannot find -lglib-2.0
          ld: cannot find -lgobject-2.0

**Comment by yvz5** [comment]
i just had the same problem.  i solved it by deleting gcc and ld files from the active toolchain.

first make sure you installed everything in this page : https://www.gtk.org/download/windows.php

find out your active toolchain by typing `rustup show` into the cmd. then go to that folder and delete or rename gcc.exe and ld.exe files.

**Comment by madmaxio** [comment]
Omg this worked, deleted those from .rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\bin

How did you figure this out?

**Comment by madmaxio** [comment]
Amazing, thx a lot.
