### ISSUE TITLE
cairo puts a border around pixbufs

### ISSUE THREAD

**Issue by pwil3058** [gtk-rs/gtk#626]
I'm converting a GTK+ program written in Python into Rust and have experienced a bewildering phenomenon where when I add Pixbus to a cairo context in Rust (using, as close as possible, the same process that I use in Python) whereby it puts a narrow black border around the Pixbuf which it doesn't do in Python.  I've been doing extensive searches of the code to try to find out where this arising without any luck.  Any help on how to kill this phenomenon would be a great help.

**Comment by GuillaumeGomez** [comment]
We'd need more information in order to be able to help you.

**Comment by pwil3058** [comment]
I have two versions (one written in Python and one written in Rust) of a program for mixing/matching paint colours that both use GTK-3 for generating the GUI.  One part of this program allows "screen samples" (as PixBufs) to be dropped/pasted into a Drawing Area for comparison with the Drawing Area's background colour.  In the Python version of the program the sample appears exactly as it did/does on the screen but in the Rust version of the program it has a narrow (probably only one pixel) black frame around it.  As far as I can tell the Python code and Rust code are using the same Cairo function which is why I'm mystified.

The program is called mcmmtk and is publicly available on github (although the rust parts may not be up to date as they're experimental) as are the Python libraries that it uses via git sub modules.  Two rust crates that it uses (rs_pw_gix and rs_epaint) are currently in private repositories (because interfacses are still in flux) on github.  Is there a way I can give you access without making them public?  If not I'll make them public.

I should add that my intention is to retire the Python version of this program as I think that distributing the Rust version will be less complicated but the effect of this problem on the program's usability (it's hard to compare colours with a black line separating them) is delaying that action.

PS when I do the tests I'm dropping exactly the same "screen sample" into the two versions of the program from the system clipboard.

**Comment by pwil3058** [comment]
All of the code for the programs where I see this behaviour are now public.

pwil3058/pcatk and pwil3058/mcmmtk are applications that were originally implemented in Python3 and are now also implemented in Rust.  Basic behaviour is the same for both Rust and Python3 versions but the GUIs differ slightly due to slightly easier programming GTK in Python3 (basically some things that could be done in Python3 couldn't be done exactly the same in Rust).

To use the Python3 versions you need to tell git to load submodules.  The Rust version should find the appropriate crates during the build process.  There are 3 crates written by me:

pwil3058/rs_pw_gix (pw_gix): which contains high level convenience functions for GTK
pwil3058/rs_pw_pathux (pw_pathux): some functions for handling non Unicode paths consistently.
pwil3058/rs_epaint (epaint): which contains code for dealing with paint colour that is used by both programs.

**Comment by pwil3058** [comment]
I have just successfully built this code on Windows and the problem does not occur there.  The system where it is seen is Linux Mint Cinnamon.

**Comment by nt8r** [comment]
I couldn't reproduce this behavior with Arch Linux, though I did see slightly blurred borders which are maybe related?

![no-black-border](https://user-images.githubusercontent.com/65555601/92822859-24802300-f3bc-11ea-8f9c-a7de5f5b30b6.png)

At any rate, I doubt this is an issue with the `gtk` crate.

**Comment by pwil3058** [comment]
I will update my dependencies to the latest versions and see if I still see the problem.

**Comment by sdroege** [comment]
This wouldn't be anything in the bindings though, everything's more or less directly translating to the C functions. So the best place to ask about this would be at https://discourse.gnome.org , with a runnable testcase to reproduce the behaviour in question so people can actually help you with the problem :)

**Comment by pwil3058** [comment]
I've always thought of this as a problem that would go away on its own without anybody doing anything specific to fix it. Since both Rust and Python are using the same C code it's a bit of a mystery. Not really a serious enough problem to lose sleep over though. PS my last check of the code (without updating dependencies) only has the black line on the right and bottom sides and the bottom one is almost invisible. Importantly, it's usable.
![Screenshot from 2020-09-12 09-10-48](https://user-images.githubusercontent.com/204985/92980047-fe4fa580-f4d7-11ea-8156-5520920ff994.png)
.
