### ISSUE TITLE
GLArea segfaults when dropped

### ISSUE THREAD

**Issue by anniryynanen** [gtk-rs/gtk#637]
GLAreas don't seem to be getting dropped cleanly, this example segfaults when the window is closed:

```
extern crate gtk;

use gtk::prelude::*;
use gtk::{GLArea, Window, WindowType};

fn main() {
    if gtk::init().is_err() {
        println!("Failed to initialize GTK.");
        return;
    }

    let window = Window::new(WindowType::Toplevel);
    let gl_area = GLArea::new();
    window.add(&gl_area);
    window.show_all();

    window.connect_delete_event(|_, _| {
        gtk::main_quit();
        Inhibit(false)
    });

    gtk::main();
}
```

**Comment by EPashkin** [comment]
For me it not segfaults but writes:
```
GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```
can be solved `std::mem::forget(gl_area);` after `gtk::main();` but this sure wrong way to fix.

**Comment by tmiasko** [comment]
We don't assume ownership of GLArea returned gtk_gl_area_new, because gir says
that we are supposed to own it, which is not true as it returns floating
reference.

**Comment by GuillaumeGomez** [comment]
Fixed so closing it.
