### ISSUE TITLE
TextBuffer: connect_insert_text closure should take `&mut Iter`

### ISSUE THREAD

**Issue by jpathy** [gtk-rs/gtk#646]
From the docs:
> Note that if your handler runs before the default handler it must not invalidate the location iter (or has to revalidate it). The default signal handler revalidates it to point to the end of the inserted text.

So we may want to revalidate the iter, if we do some mutation on the buffer. Currently not possible without `unsafe`.

**Comment by GuillaumeGomez** [comment]
I suppose we can close this issue now.
