### ISSUE TITLE
Add glib::signal::connect_after

### ISSUE THREAD

**Issue by jpathy** [gtk-rs/gtk#650]
Completely trivial(only change flags to `gobject_sys::GConnectFlags::AFTER`), but i think it should be in the lib.

**Comment by sdroege** [comment]
This is already possible via `ObjectExt::connect()`. https://github.com/gtk-rs/glib/blob/master/src/object.rs#L779

Not sure how we should support this generically for all signals with explicit connectors. Adding a boolean to each, or having two connector functions. @GuillaumeGomez @EPashkin, opinions?

**Comment by GuillaumeGomez** [comment]
We basically have the choice between an extra argument or an extra function. I would have a preference for the later though but no hard feelings here...

**Comment by sdroege** [comment]
Same, extra function seems nicer

**Comment by EPashkin** [comment]
I also vote for extra function to not break current API,
this function can be controlled separately in future if needed.

**Comment by sdroege** [comment]
`glib::ObjectExt::connect()` has an `after` parameter since a while.
