### ISSUE TITLE
Cross Compilation issues

### ISSUE THREAD

**Issue by foo-jin** [gtk-rs/gtk#653]
I'm in a similar predicament to #600, trying to cross compile from Ubuntu to Windows. I followed the same steps as the author of #600 did, made sure that my glade file used the same version of gtk as specified in the `gtk` crate's `version` feature flag (I'm using `v3.10`). The error I end up with is `gtk-0.4.1/src/auto/enums.rs:5432: undefined reference to 'gtk_text_view_layer_get_type'`. It could imagine that this error is fixable in a similar way as the issues in #600, but I don't know where to start looking. Could someone help me out with this? It feels like I've gotten to the last step of working through the cross-compilation issues, so I'd love to get it working completely.

**Comment by EPashkin** [comment]
Seems GtkTextViewLayer only added in 3.14 as `GtkTextViewClass.draw_layer` is only function that use it.
So you only need do same as in #603 (also look at https://github.com/gtk-rs/gtk/issues/600#issuecomment-348775765)

**Comment by foo-jin** [comment]
Although compilation succeeds now, I get the following error when running it on windows:
```
Error: "(packt-gui.exe:372) Gtk-ERROR **: failed to add UI:
<input>:21:1 <object> requires attribute "id""'
```

**Comment by EPashkin** [comment]
Check your glade file

**Comment by sdroege** [comment]
The issue with the `get_type()` function for enums should be solved since a while.
