### ISSUE TITLE
how to draw arabic RTL glyph with pango & cairo? any example?

### ISSUE THREAD

**Issue by adals** [gtk-rs/gtk#657]
as above
thanks

**Comment by GuillaumeGomez** [comment]
Not for the moment at least. However, there is certainly such an example with official pango/cairo docs. If you happen to write one, we'd love you to send us a PR on gtk-rs/examples.

**Comment by sdroege** [comment]
This is a general GTK problem and not related to the bindings, so best discussed at https://discourse.gnome.org
