### ISSUE TITLE
Closures With Copy And Clone

### ISSUE THREAD

**Issue by TheDarkula** [gtk-rs/gtk#661]
Now that closures implement [Copy and Clone](https://github.com/rust-lang/rust/pull/49299)
Does this mean we should be able to get rid of `builder.clone()` calls?
Would it be as simple as adding `#[derive(Clone, Copy)]` to the Builder struct?

**Comment by sdroege** [comment]
can you give a code example what exactly you mean?

**Comment by TheDarkula** [comment]
I didn't have one exactly. What I was wanting to do was be able to have the `Builder` struct implement the `Clone` trait, so we don't have to use a `clone!` macro or do `.clone()` calls on it.

I couldn't track down exactly where the `Builder` struct was in the gtk-rs source code, but the pseudo-code would look something like this:

```
#[derive(Clone, Copy)]
struct Builder {
// fields omitted
}

**Comment by sdroege** [comment]
`gtk::Builder` is already implementing `Clone`. It can't possibly implement `Copy` as that is only possible to derive and is limited to basic types and combinations of them.
