### ISSUE TITLE
ListBoxRow should be gtk::ActionableExt

### ISSUE THREAD

**Issue by ZanderBrown** [gtk-rs/gtk#663]
ListBoxRow should support `gtk::ActionableExt` giving access to `set_action_name`
![](https://valadoc.org/gtk+-3.0/img/Gtk.ListBoxRow.svg)
[Source: Valadoc](https://valadoc.org/gtk+-3.0/Gtk.ListBoxRow.html)

**Comment by EPashkin** [comment]
It already 😉 
https://github.com/gtk-rs/gtk/blob/master/src/auto/list_box_row.rs#L29

**Comment by EPashkin** [comment]
It just not published https://github.com/gtk-rs/gtk/blob/crate/src/auto/list_box_row.rs

**Comment by EPashkin** [comment]
We don't have any release plan so it can take long time.

**Comment by sdroege** [comment]
@GuillaumeGomez this can be closed
