### ISSUE TITLE
No method `emit_insert_emoji` found for `sourceview::View`

### ISSUE THREAD

**Issue by Kagamihime** [gtk-rs/gtk#677]
Hello!

I may have found a problem, cargo tells me this:
```
error[E0599]: no method named `emit_insert_emoji` found for type `appop::room::sourceview::View` in the current scope
  --> fractal-gtk/src/app/connect/emoji.rs:22:23
   |
22 |             msg_entry.emit_insert_emoji();
   |                       ^^^^^^^^^^^^^^^^^
```
with `msg_entry` being of the type `sourceview::View`. However there are other similar methods from the trait `gtk::TextViewExt` are found at this same place of the code (e.g. `emit_backspace`, `emit_insert_at_cursor`). `emit_insert_emoji` is listed here http://gtk-rs.org/docs/gtk/trait.TextViewExt.html#tymethod.emit_insert_emoji

I've found a work around: `msg_entry.emit("insert-emoji", &[]);`. But I've thought that telling you about this may be useful :)

**Comment by GuillaumeGomez** [comment]
This is weird... I suppose you have import `TextViewExt` so I don't really know where the problem could be... Can you post your code so we can take a look please?

**Comment by Kagamihime** [comment]
Sure! Here is the link to my branch https://gitlab.gnome.org/Kagamihime/fractal/tree/multiline-message-input

**Comment by nt8r** [comment]
This was likely due to not enabling the `v3_22_26` feature, which is necessary for this method to be available: https://github.com/gtk-rs/gtk/blob/7b9a60d0b422b6ab9a0797c8ac0daa02c5757980/src/auto/text_view.rs#L880

It would be nice to have a more straightforward error; I've been similarly confused by this situation for other API functions.

**Comment by sdroege** [comment]
> It would be nice to have a more straightforward error

This would be something to add to `rustc`. It could check if a similarly named function exists behind a feature flag and suggest enabling it. Want to create an issue there: https://github.com/rust-lang/rust/ ?
