### ISSUE TITLE
No updates on crates.io

### ISSUE THREAD

**Issue by berkus** [gtk-rs/gtk#682]
Hi,

latest package on crates.io is 0.4.1 from 3 months ago, but i see there is a steady stream of changes and fixes.

Where can I see the release plan, if available, and when do you plan to make next release? Some kind of roadmap would be nice to see.

Thanks!

**Comment by GuillaumeGomez** [comment]
No roadmap: things get released when the team assumes it's ready.

Next release is planned within the two next weeks if everything goes smoothly.

**Comment by GuillaumeGomez** [comment]
My answer might have been a bit harsh, sorry about that. We just have things getting discussed, new issues appearing or new rust features coming up and that makes most of new releases. Making a roadmap is very complicated at the time but I don't exclude the possibility of having one in the future.

**Comment by berkus** [comment]
No no, no problems about that; thank you for the update :)
