### ISSUE TITLE
EntryCompletion missing set_match_func

### ISSUE THREAD

**Issue by dbeckwith** [gtk-rs/gtk#685]
[GTK docs](https://developer.gnome.org/gtk3/stable/GtkEntryCompletion.html#gtk-entry-completion-set-match-func)
Might be tricky to Rustify since you have to pass it a function pointer, but I need access to this to customize the completion behavior.

**Comment by sdroege** [comment]
Related https://github.com/gtk-rs/gir/issues/618. Will try to get to that soon so we get all these functions for free
