### ISSUE TITLE
Bind Model to gtkListBox

### ISSUE THREAD

**Issue by jsparber** [gtk-rs/gtk#696]
Is there any blocker for having gtk_list_box_bind_model() implemented?

https://github.com/gtk-rs/gtk/blob/732ea2b385b6c2f3f8fa6b04c724a3532bb7429b/src/auto/list_box.rs#L58

**Comment by GuillaumeGomez** [comment]
We don't **yet** generate callbacks. This is ongoing though.

**Comment by happycoder97** [comment]
@jsparber, I have written a temporary solution: https://gitlab.com/happycoder97/gtk-rs-list-box-model

**Comment by sdroege** [comment]
I implemented this a while ago: https://github.com/gtk-rs/gtk/commit/24c4c8305c235592c49bf2018d0f6e0afdeeb4d7

There's an example in https://github.com/gtk-rs/examples/blob/master/src/bin/listbox_model.rs

**Comment by sdroege** [comment]
@GuillaumeGomez you can close this :)

**Comment by GuillaumeGomez** [comment]
Indeed!

**Comment by jsparber** [comment]
Oh, i didn't check gtk::ListBoxExtManual. Anywhay awesome
