### ISSUE TITLE
Change GLArea create_context handler to return Option<GLContext> instead of GLContext

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [gtk-rs/gtk#703]
Right now, the signal handler for `create_context` on the `GLArea` widget must return a `GLContext` object. However, creating a context is not guaranteed to work, as `window.create_gl_context` returns a `Result`. This essentially requires the code implementing the signal to panic if context creation fails, instead of possibly implementing a more graceful error mechanism.

The documentation and the source code of GLArea suggest that the `create_context` signal is allowed to return a null pointer, so the `connect_create_context` function should take a function that returns `Option<GLContext>` instead of `GLContext`.

**Comment by EPashkin** [comment]
Can you point to docs or comment in code?
both https://developer.gnome.org/gtk3/stable/GtkGLArea.html#GtkGLArea-create-context
and my source seems don't allow null
```
static void
gtk_gl_area_realize (GtkWidget *widget)
{
  GtkGLArea *area = GTK_GL_AREA (widget);
  GtkGLAreaPrivate *priv = gtk_gl_area_get_instance_private (area);

  GTK_WIDGET_CLASS (gtk_gl_area_parent_class)->realize (widget);

  g_clear_error (&priv->error);
  priv->context = NULL;
  g_signal_emit (area, area_signals[CREATE_CONTEXT], 0, &priv->context);

  /* In case the signal failed, but did not set an error */
  if (priv->context == NULL && priv->error == NULL)
    g_set_error_literal (&priv->error, GDK_GL_ERROR,
                         GDK_GL_ERROR_NOT_AVAILABLE,
                         _("OpenGL context creation failed"));

  priv->needs_resize = TRUE;
}
```

**Comment by EPashkin** [comment]
Seems it really allow null, but error happened if all return null
```
static gboolean
create_context_accumulator (GSignalInvocationHint *ihint,
                            GValue *return_accu,
                            const GValue *handler_return,
                            gpointer data)
{
  g_value_copy (handler_return, return_accu);

  /* stop after the first handler returning a valid object */
  return g_value_get_object (handler_return) == NULL;
}
```

**Comment by EPashkin** [comment]
Can you test this addition for Gir.toml with signal, returning `None`?
```
    [[object.signal]]
    name = "create-context"
        [object.signal.return]
        nullable = true
```

**Comment by ColonelThirtyTwo** [comment]
Well the documentation for `set_error` mentions it can be used if the `create_context` signal fails, but that's at odds with the current return type of the `create_context`, which requires the function to return a valid `GLContext`.

The `if (priv->context == NULL && priv->error == NULL)` branch sets a default error, in case the signal didn't return a context but also didn't set it's own error.

I can't test the changes at the moment, sorry. I just wanted to point it out.
