### ISSUE TITLE
Please, implement set_filter_func method for ListBox

### ISSUE THREAD

**Issue by ivmazurenko** [gtk-rs/gtk#706]
https://github.com/gtk-rs/gtk/blob/45a12ecb2137cea645ebc82883d872125f90c20b/src/auto/list_box.rs#L118

Did I understand correctly,  with this method i can filtering my list easy? Thanks a lot for any answer.

**Comment by sdroege** [comment]
At this point this would need a manual implementation like: https://github.com/gtk-rs/gtk/blob/master/src/list_box.rs#L76

Would be relatively easy to write. An automatic solution would require me to finish https://github.com/gtk-rs/gir/issues/618

**Comment by paulfariello** [comment]
What is the recommended way to workaround this limitation?

**Comment by GuillaumeGomez** [comment]
It's being implemented currently in https://github.com/gtk-rs/gir/pull/667 .

**Comment by mmstick** [comment]
Ran across the missing `set_header_func` as well, for ListBox.

**Comment by nt8r** [comment]
This looks to be solved, including `set_header_func`. Can someone close this?

**Comment by sdroege** [comment]
Thanks for checking!
