### ISSUE TITLE
get_style_context() shouldn't return an Option<>

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk#709]
gtk::WidgetExt::get_style_context() returns an Option<>, but I don't see any reason why

**Comment by GuillaumeGomez** [comment]
https://code.woboq.org/gtk/gtk/gtk/gtkwidget.c.html#16541

**Comment by sophie-h** [comment]
Which means, it should never return None as long as no unsafe code is involved?

**Comment by EPashkin** [comment]
IMHO @sophie-h is right and we need make this non-optional.

**Comment by GuillaumeGomez** [comment]
Indeed. Good catch @sophie-h! Wanna send the PR?
