### ISSUE TITLE
Segfaults on exit

### ISSUE THREAD

**Issue by donaldcallen** [gtk-rs/gtk#713]
I have written a personal finance application in Rust, using the gtk crate (and rusqlite for data storage). This is a re-write of a functionally identical application I originally wrote in C and have been using to manage my finances since 2013. I've been using the Rust version for about 6 months.

The problem I report here is that I am occasionally experiencing segfaults when I exit the application. Exiting the application occurs when the main window, which displays the tree of my accounts, is closed via the window manager. Here is the callback that handles that event:

    // Set up callback to handle deletion of the accounts window
    let globals_delete_event = globals.clone();
    globals.accounts_window.connect_delete_event(move |_, _| {
        let mut non_zero_balance=false;
        let stmt:&mut Statement = cache_statement_locally!(UNBALANCED_TRANSACTIONS_SQL);
        for transaction_register in globals_delete_event.transaction_registers.borrow().values() {
            if stmt.query_row(&[&(*transaction_register.guid)], get_result!(f64)).unwrap() > EPSILON {
                non_zero_balance=true;
                break;
            }
        };
        if non_zero_balance {
            utilities::display_message_dialog("You have at least one open transaction register with a non-zero balance.
    Please properly balance the transaction(s) before attempting to quit from Newcash", &globals_delete_event);
            Inhibit(true)
        } else {
            println!("Exiting Newcash");
            gtk::main_quit();
            // Let the default handler destroy the window.
            Inhibit(false)
        }
    });
In the vast majority of the attempts to exit the application, non_zero_balance will be false and the block beginning with 

println!("Exiting Newcash");

is executed. This is the case I'm concerned about. When the segfaults occur, "Exiting Newcash" gets printed prior to the crash. So I'm very suspicious that the issue is occurring in main_quit. I am happy to help debug this if you will make suggestions as to how to do so.

I should add that my C version of this application does not exhibit this behavior. It has a similar callback to handle closing of the main window.

**Comment by EPashkin** [comment]
Not sure why it crashes while C is not,
but if `globals.accounts_window` is main window then better do `win.destroy()`  instead `gtk::main_quit()`, see https://github.com/gtk-rs/examples/blob/master/src/bin/basic.rs#L24

**Comment by EPashkin** [comment]
Hm, I missed that we use `gtk::ApplicationWindow` in examples, so it may not work with normal window

**Comment by EPashkin** [comment]
As I know for debugging you can use usual `gdb`, only problem I see is need `rbreak` instead `break` due mangling.

**Comment by donaldcallen** [comment]
I *think* I've found the culprit and it was me (although I would suggest that you document this if it turns out I'm right). Here's the theory: 

For each of the windows my application creates, I create a struct, which I call a descriptor, that holds information about the window. In each case, I record the window (as returned from Window::new) and other related gtk objects, such as the view and the store. In some cases, I also use a scrolled_window.

But suppose, when I close the application using the window-manager close operation, the windows get deleted in the X world and the gtk world *before* those descriptors get released by Rust's memory management. If so, there are now pointers in those descriptors to gtk objects that have been deleted (which I believe will be followed by Rust memory management when the struct is de-allocated), because I provided no insurance that things would happen in the proper order.

What I've done is store those pointers in RefCelled Options (the structs can't be mutable because they are Rc-ed), e.g.,

    pub struct RegisterCore {
        pub view:RefCell<Option<TreeView>>,
        pub window:RefCell<Option<Window>>,
    }

and provided callbacks to handle the delete event for every window I create, which sets all these struct fields to None, thus causing any cleanup of the gtk objects pointed to to happen before the window actually goes away.

I just completed this modification to my application, so I don't have much experience with it yet (I tried a few different configurations of windows and then closed the application and got no seg-faults, which doesn't prove much, since the seg-faults did not happen deterministically in the first place). I will let you know as I continue to use my application whether I encounter seg-faults or, after what I consider a long enough test period, I do not.

**Comment by EPashkin** [comment]
Strange, [Example](https://mmstick.github.io/gtkrs-tutorials/chapter_02/ui.html) with many structs by @mmstick use same idea as you previously and seems works without seg-faults.

**Comment by donaldcallen** [comment]
Whatever is going on here, whether I've diagnosed the cause correctly or not, is definitely a race, because it did not happen every time with the un-modified version of my application. The timing of the example may be such that the probability of seg-faulting is lower than in my case. Obviously guesswork at this point.

**Comment by sdroege** [comment]
Can you provide a complete testcase for reproducing the crash, and can you get a backtrace of the crash?

**Comment by donaldcallen** [comment]
On Tue, 9 Oct 2018 at 14:04, Sebastian Dröge <notifications@github.com>
wrote:

> Can you provide a complete testcase for reproducing the crash, and can you
> get a backtrace of the crash?
>

I appreciate your trying to help, but it appears that you haven't read my
posts carefully enough.

First of all, as I've said before, the crash is intermittent; it does not
happen every time I exit my application. So I can't reproduce the problem
at will. Given that, I'm hardly in a position to provide you with a
"complete test-case".

Secondly, I described a fix to my code that would insure that all pointers
into gtk would be removed from the descriptor structs before allow gtk to
destroy windows. I have applied that change to my code and I mentioned in
my last post that some time needs to elapse without a crash to gain
confidence in the fix. Thus far, I've seen only one crash since my fix. And
that was after fixing an unrelated bug in my code, recompiling and
reinstalling, forgetting that I had an instance of the application running.
When I closed that instance, I got a seg-fault. I have no idea whether
re-installing the running executable caused the crash, but I can report
that overall, the seg-fault frequency is down dramatically. More time needs
to elapse to start to reach any conclusions as to whether I've solved the
problem.

**Comment by GuillaumeGomez** [comment]
I'll close this issue until we have more context. Don't hesitate to send it to us once you have more information!

**Comment by donaldcallen** [comment]
On Tue, 9 Oct 2018 at 16:26, Sebastian Dröge <notifications@github.com>
wrote:

> What you're describing above does not make much sense though. The objects
> are all refcounted and your Rust structs own a reference to them. Even if
> GTK is shutting down and the e.g. X11 resources behind the objects are
> destroyed, the references to them would still be valid and it would be a
> bug if a segfault would be caused by this.
>

The above is very helpful. Please clarify for me though -- obviously when
gtk is asked to create, say, a window, the object has a refcount of 1. When
gtk-rs returns that window as a result of a Window::new call, are you
saying the refcount is now 2, one for the pointer gtk handed to you and one
for the pointer you handed to me? If so, then I get your point  -- my "fix"
should not have been necessary and should have no effect.

> So either there's something going wrong with the reference handling in the
> bindings, or something goes wrong on the GTK side. In either case there's a
> real bug to be solved here. Without a testcase for the crash (even if it
> only happens once every 1000 times, let's just run it in a loop, or in
> valgrind or with ASAN) or at least a backtrace of the crash there's not
> much else I could help with then and you'd have to debug it yourself.
>
In any case, the "fix" you mention is more a workaround.
>
If the answer to my question above is 'yes', then I agree. In other words,
if the way I originally wrote the code, without trying to insure that the
descriptor structs held no references to gtk objects associated with
windows that were being destroyed, should have worked and that it doesn't
is the bug you are referring to above. One step I can try to take is to
revert my code to the way it was before I applied this fix and try to get a
backtrace in gdb.

**Comment by sdroege** [comment]
Not exactly as you describe it, but the idea behind it, yes.

When you create some GTK object from Rust, it will have a reference count of 1 on the C side and that single reference is what is passed to you and owned by you on the Rust side. If you `clone()` the object, the reference count will be increased, if you `drop()` it it will be decreased (basically the same as with `Rc` and `Arc`). Creating a button and adding it to some container, for example, would cause a reference count of 2 at the moment you add it to the container. The container increases the reference count to 2 because it keeps another reference around that is independent of the one you have, so the button stays around even if you get rid of your reference.

GTK might also keep more references to your objects around for other reasons, but that's all irrelevant. If you have e.g. a `gtk::Window` in Rust, then *you* own a strong reference to the object and it must be usable without segfaults until you get rid of that reference, independent of what GTK or other code is doing with that same object (unless of course that other code is buggy).

**Comment by sdroege** [comment]
Thanks, let us know once you find something. That would be a really bad bug indeed and I'd like to see it fixed :)

> But, ironically, the version written in memory-safe Rust segfaults; the C version does not. I completely understand that 'unsafe' means 'unsafe'. But there's a bug somewhere in gtk-rs + gtk that's causing this.

Well there are always bugs. The difference here is that for the Rust bindings (if it's indeed a bug there and not in GTK, which you simply might not hit in C because e.g. you drop the last references earlier already) we would have to fix this bug once, while in C every application again runs into the risk of this bug and any other kind of problem caused by manual memory management.

**Comment by donaldcallen** [comment]
On Thu, 11 Oct 2018 at 02:46, Sebastian Dröge <notifications@github.com>
wrote:

> Thanks, let us know once you find something. That would be a really bad
> bug indeed and I'd like to see it fixed :)
>
> But, ironically, the version written in memory-safe Rust segfaults; the C
> version does not. I completely understand that 'unsafe' means 'unsafe'. But
> there's a bug somewhere in gtk-rs + gtk that's causing this.
>
> Well there are always bugs. The difference here is that for the Rust
> bindings (if it's indeed a bug there and not in GTK, which you simply might
> not hit in C because e.g. you drop the last references earlier already)
>
Your description of what I do in the C version is not quite right. But
let's talk about the Rust problem. My theory is that I have a struct that
contains a handle to a window returned from Window::new. The window gets
destroyed by the user and I am guessing that the destruction of the window
invalidates that handle. But in my original code, the struct and the handle
in it could outlive the window and therefore the invalidation of the
handle. So when Rust finally de-allocates the struct, I believe it also
de-allocates anything the struct owns, which would include the window
handle, which is now invalid, possibly leading to a seg-fault, depending on
the timing of things I don't know about. This is all supposition on my
part. Based on that supposition, I made all entries in the struct obtained
from gtk-rs calls Options, e.g., Option<Window>. In the callback for the
window destruction event, I set those slots in the struct to None before
exiting the callback with Inhibit(false). I believe that guarantees that
those slots are set to None *before* the actual destruction of the window
within gtk-rs and gtk. This has clearly improved the situation. In many
uses of the application, I have seen only one seg-fault, and that was in an
unusual situation, where I fixed a bug, rebuilt and reinstalled the
application, forgetting to first close the running instance of the
application where I noticed the bug. When I closed it, it seg-faulted. I
have no idea whether my pulling the table cloth out from under the dishes
was the cause of this or not. But it's the only seg-fault I've seen since
making the Option change. Before that change, they were much more frequent.

Moving on, you wrote that when I obtain a window handle from Window::new,
its refcount will be 1. In the original code, without the use of Option,
when a window gets destroyed, you seem to be arguing that because the
refcount is still one after the destroy has been fully processed, the
handle in the struct should still be valid, which invalidates my theory. So
I downloaded the latest stable copy of gtk and grepped (with find) all .c
files for the regexp "gdk_object_unref.*window". There were a lot of hits,
but I found one that really interests me. It's in gdk/gdk_window.c:

/**
 * gdk_window_destroy:
 * @window: a #GdkWindow
 *
 * Destroys the window system resources associated with @window and
decrements @window's
 * reference count. The window system resources for all children of @window
are also
 * destroyed, but the children’s reference counts are not decremented.
 *
 * Note that a window will not be destroyed automatically when its
reference count
 * reaches zero. You must call this function yourself before that happens.
 *
 **/
void
gdk_window_destroy (GdkWindow *window)
{
  _gdk_window_destroy_hierarchy (window, FALSE, FALSE, FALSE);
  g_object_unref (window);
}

Now I don't even know enough about the innards of gtk/gdk to be dangerous,
but this sure looks to me like it might get called when a window gets
destroyed. If so, it's decrementing the refcount. Based on our discussion,
that should result in a refcount of zero and deallocation of the internal
gtk/gdk data structure representing the window. I'm guessing that that is
precisely the data structure to which the handle in my Rust structure
points.

So I still think my theory is plausible and my experience with my fix based
on it seems to support it, though I have, as noted, seen one seg-fault
since applying the fix. I also do not have any idea why the original
problem was probabilistic. My Rust application is single-threaded and I
believe the application, gtk-rs and gtk/gdk are all running in that single
thread. But there's the window manager and the X server, both running in
separate processes. But I can't stitch together even a guess as to where
the race is.

/Don Allen

**Comment by sdroege** [comment]
See example below (no difference between calling `window.destroy()` explicitly or not: `Inhibit(false)` will cause it to be called directly anyway.

This is valgrind clean on wayland and X11, and the actual reference to the window is only dropped at the very end after the window is "destroyed". The function you mention about is called when the window is unrealized, which happens as part of that.

So you're right that it decreases the reference count and what I wrote about was a simplification. The GTK window will internally hold reference to the GDK window (not GTK window) for keeping track of the window and being able to handle X11/etc events on it. It will drop this reference once the GTK window is unrealized (which happens when it's closed/destroyed). GTK might also hold other references to the GTK (not GDK) window internally for keeping track of things, but that's all something that does not really concern us. The important part for us is that we own a reference to the GTK window, and we release that reference once we're done with it and will never use it again (which might be after the GDK window is destroyed, etc.). But even if we would hold an additional reference to the GDK window, there is no problem (try it, store `window.get_window()` somewhere and drop it at the very end). That's the whole point of reference counting after all, as long as you own a reference it is not gone :)

```rust
extern crate gtk;

use gtk::prelude::*;

fn main() {
    gtk::init().unwrap();

    // strong reference to the window here
    let window = gtk::Window::new(gtk::WindowType::Toplevel);

    window.connect_delete_event(|window, _ev| {
        println!("delete event");
        //window.destroy();
        gtk::main_quit();
        gtk::Inhibit(false)
    });

    window.connect_destroy(|_window| {
        println!("destroy");
    });

    window.show_all();

    gtk::main();

    // reference to the window is being dropped after
    // it was closed/destroyed
    println!("dropping window reference");
    drop(window);
}
```

**Comment by donaldcallen** [comment]
A couple more comments, below.

On Thu, 11 Oct 2018 at 02:46, Sebastian Dröge <notifications@github.com>
wrote:

> Thanks, let us know once you find something. That would be a really bad
> bug indeed and I'd like to see it fixed :)
>
> But, ironically, the version written in memory-safe Rust segfaults; the C
> version does not. I completely understand that 'unsafe' means 'unsafe'. But
> there's a bug somewhere in gtk-rs + gtk that's causing this.
>
> Well there are always bugs. The difference here is that for the Rust
> bindings (if it's indeed a bug there and not in GTK, which you simply might
> not hit in C because e.g. you drop the last references earlier already)
>
 If my main theory is right, in the C version, the pointers in the
descriptor struct will also outlive the structs they point to. The
difference is that in C, when the descriptor struct eventually gets
deallocated, there's nothing chasing those bad pointers over a cliff in a
futile attempt to de-allocate what they point to.

> we would have to fix this bug once, while in C every application again
> runs into the risk of this bug and any other kind of problem caused by
> manual memory management.
>
I certainly accept the contention that over a universe of applications
written in Rust vs  the same applications written in C, all by a bunch of
random programmers, the Rust versions will have fewer bugs. But just as
it's possible for someone to smoke two packs of Lucky Strikes every day and
die from old age at 100, it's possible for a particular C application to be
more stable than the same application written in Rust. That is exactly the
situation here. I started work on the C version in 2012 and have been
managing my finances with it since early 2013. Sure, there were bugs early
on (and after adding new features), but they weren't difficult to find and
fix. I've also run it under Valgrind to check for memory leaks periodically
and have not found any. The thing is rock solid now.

But the Rust version is so much more readable and less cluttered (e.g.,
with casts between C's 14 different varieties of strings and the Rust
compiler telling you about unused things). So I'd really like to make this
work with Rust.

/Don

**Comment by donaldcallen** [comment]
On Thu, 11 Oct 2018 at 10:07, Sebastian Dröge <notifications@github.com>
wrote:

> See example below (no difference between calling window.destroy()
> explicitly or not: Inhibit(false) will cause it to be called directly
> anyway.
>
> This is valgrind clean on wayland and X11, and the actual reference to the
> window is only dropped at the very end after the window is "destroyed". The
> function you mention about is called when the window is unrealized, which
> happens as part of that.
>
> So you're right that it decreases the reference count and what I wrote
> about was a simplification. The GTK window will internally hold reference
> to the GDK window (not GTK window) for keeping track of the window and
> being able to handle X11/etc events on it. It will drop this reference once
> the GTK window is unrealized (which happens when it's closed/destroyed).
> GTK might also hold other references to the GTK (not GDK) window internally
> for keeping track of things, but that's all something that does not really
> concern us. The important part for us is that we own a reference to the GTK
> window, and we release that reference once we're done with it and will
> never use it again (which might be after the GDK window is destroyed,
> etc.). But even if we would hold an additional reference to the GDK window,
> there is no problem (try it, store window.get_window() somewhere and drop
> it at the very end). That's the whole point of reference counting after
> all, as long as you own a reference it is not gone :)
>
Yes, I do understand what reference counting is about:-) My guess about
what's happening with my application is based on the supposition that the
reference count on one of the objects obtained from gtk-rs is going to zero
prematurely.

Your example below certainly works as one would hope, at least the small
number of times I ran it. But I would mention two things:

1. My experience with the seg-faults in my application is not
deterministic. They happen (with the original) only some fraction of the
time, < .5. So there's a timing issue here. The timing of your example may
be different, and more favorable, than my application.
2. I am dealing with multiple objects -- windows, views, scrolled windows,
stores, etc. that are pointed to by my descriptor struct and so each one is
vulnerable to a reference counting error. So my situation is somewhat more
complex than the example below.

**Comment by sdroege** [comment]
> If my main theory is right, in the C version, the pointers in the descriptor struct will also outlive the structs they point to. The difference is that in C, when the descriptor struct eventually gets deallocated, there's nothing chasing those bad pointers over a cliff in a futile attempt to de-allocate what they point to.

There's no difference between C and Rust in that regard, apart from Rust calling `g_object_ref()` and `g_object_unref()` for you. You might have only (pseudo-)borrowed reference to your widgets in the C version though (or maybe you leak them?): e.g. in the following code

```c
button = gtk_button_new();
gtk_container_add(container, button);
// the button reference is now owned by the container and
// the container will unref it at the end: see floating references
// that's what I mean with a (pseudo-) borrowed reference here.
```

The same in Rust would be equivalent to the following C code (if you look at the assembly output of an optimized Rust build, it's basically indistinguishable from this C code)

```c
button = gtk_button_new();
g_object_ref_sink(button); // this is new
gtk_container_add(container, button);
// we now have a reference and the container, the reference
// count is at least 2 and we have to unref ours in the end
g_object_unref(button);
```

> Yes, I do understand what reference counting is about:-) My guess about what's happening with my application is based on the supposition that the reference count on one of the objects obtained from gtk-rs is going to zero prematurely.

That's exactly my guess too. Either on the Rust binding side or in GTK, we'll see :)

Can you run your application (the sometimes crashing version) in valgrind with `G_SLICE=always-malloc` in the environment and `--track-origins=yes --leak-check=no`? Maybe that gives us an invalid read/write of already freed memory, for example. These don't always cause crashes but valgrind would at least complain about it. And running in valgrind also changes timing a lot, which might help.

> 2. I am dealing with multiple objects -- windows, views, scrolled windows, stores, etc. that are pointed to by my descriptor struct and so each one is vulnerable to a reference counting error. So my situation is somewhat more complex than the example below.

Ack, the example was only to make my point clear that there is no conceptual problem here and it's not a problem generally to have a reference to GTK objects as long as you want. There might just be a bug somewhere.

**Comment by donaldcallen** [comment]
On Thu, 11 Oct 2018 at 11:50, Sebastian Dröge <notifications@github.com>
wrote:

> If my main theory is right, in the C version, the pointers in the
> descriptor struct will also outlive the structs they point to. The
> difference is that in C, when the descriptor struct eventually gets
> deallocated, there's nothing chasing those bad pointers over a cliff in a
> futile attempt to de-allocate what they point to.
>
> There's no difference between C and Rust in that regard, apart from Rust
> calling g_object_ref() and g_object_unref() for you. You might have only
> (pseudo-)borrowed reference to your widgets in the C version though (or
> maybe you leak them?): e.g. in the following code
>
> button = gtk_button_new();gtk_container_add(container, button);// the button reference is now owned by the container and// the container will unref it at the end: see floating references// that's what I mean with a (pseudo-) borrowed reference here.
>
> The same in Rust would be equivalent to the following C code (if you look
> at the assembly output of an optimized Rust build, it's basically
> indistinguishable from this C code)
>
> button = gtk_button_new();g_object_ref_sink(button); // this is newgtk_container_add(container, button);// we now have a reference and the container, the reference// count is at least 2 and we have to unref ours in the endg_object_unref(button);
>
> Yes, I do understand what reference counting is about:-) My guess about
> what's happening with my application is based on the supposition that the
> reference count on one of the objects obtained from gtk-rs is going to zero
> prematurely.
>
> That's exactly my guess too. Either on the Rust binding side or in GTK,
> we'll see :)
>
> Can you run your application (the sometimes crashing version) in valgrind
> with G_SLICE=always-malloc in the environment and --track-origins=yes
> --leak-check=no? Maybe that gives us an invalid read/write of already
> freed memory, for example. These don't always cause crashes but valgrind
> would at least complain about it. And running in valgrind also changes
> timing a lot, which might help.
>
>
>    1. I am dealing with multiple objects -- windows, views, scrolled
>    windows, stores, etc. that are pointed to by my descriptor struct and so
>    each one is vulnerable to a reference counting error. So my situation is
>    somewhat more complex than the example below.
>
> Ack, the example was only to make my point clear that there is no
> conceptual problem here and it's not a problem generally to have a
> reference to GTK objects as long as you want. There might just be a bug
> somewhere.
>
I've backed out my workaround and have made many attempts to provoke a
seg-fault and have not been able to do so. I am doing this on up-to-date
Arch Linux systems and this led me to check when the last update to gtk3
occurred. It's dated 2018-10-05, so very recently and pretty much
coinciding with the disappearance of the segfaults in normal use, which I
thought were due to my "fix". Maybe they fixed a bug? At this point, I
think the best strategy is for me to just use the application (without the
workaround) as I usually do and see if the problem recurs.

/Don

**Comment by sdroege** [comment]
Maybe there was a bug between those gtk releases, yes. Can you check which version you were running with the segfaults and which now?
