### ISSUE TITLE
Combination of connect_key_press_event and connect_key_release_event

### ISSUE THREAD

**Issue by thebitstick** [gtk-rs/gtk#715]
I'm currently working on a big project and I'm trying to reduce duplication and I need both key_press and key_release to do the exact same things, is there any way I could reduce the two into one function?

Code in question is https://github.com/ShareXin/ShareXin/blob/7286e2f5566fd565ebb952e300fec7a19729a835/src/dialog.rs#L157 (currently it only uses key_release)

**Comment by EPashkin** [comment]
You can't make function from https://github.com/ShareXin/ShareXin/blob/7286e2f5566fd565ebb952e300fec7a19729a835/src/dialog.rs#L160-L211 with many parameters as needed and call it in closures for both cases?
This may be required creating more clones beforehand.

**Comment by thebitstick** [comment]
That seems to have worked, thank you.

**Comment by thebitstick** [comment]
For reference this is what I did
https://github.com/ShareXin/ShareXin/commit/a63e517b7955a6450f4c113a1e853015110faf4e?diff=split

**Comment by EPashkin** [comment]
Note: cloning unneeded in closures as it already own clone.
