### ISSUE TITLE
Remove "brew unlink python" .travis.yml

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gtk#717]
Some time ago I tried removing it on gtk, glib and CI was passed.
Now I add PRs for all crates gtk-rs and check, if any failed,
then we can decide if it really needed.

**Comment by GuillaumeGomez** [comment]
Sounds good to me as long as it doesn't fail.

**Comment by EPashkin** [comment]
Travis finished for all 8 PRs, there was 2 network failures but all other jobs finished successfully.
So seems uninstalling python for Mac not needed anymore.

**Comment by GuillaumeGomez** [comment]
I suppose it can be closed now.
