### ISSUE TITLE
gtk-rs in Windows dll doesn't work

### ISSUE THREAD

**Issue by BIMSOMS** [gtk-rs/gtk#719]
I compiled a dylib with gtk dependency to be called from a C# solution.
It compiles and runs but the dell returns crapp. E.g. add_numbers( 2, 3 ) returns 2.
 
https://github.com/BIMSOMS/csharp_calling_gtk-rs_issue/blob/b91972a25e198b87576292028fa1edc602381ea7/cmdline/Program.cs#L20

I created a repository with a Visual Studio solution that compiles the rust code and the C# code:
https://github.com/BIMSOMS/csharp_calling_gtk-rs_issue

**Comment by EPashkin** [comment]
It really strange.
It not works even if called from rust code (return 1871689512)
Just adding `extern crate gtk;` is enough for non-gtk function fail.
All other crates don't have this effect.
@BIMSOMS Can you add other crate `test_run` to test project?
```
[dependencies]
test_basic = { path = "../test_basic" }
```
```
extern crate test_basic;

fn main() {
    println!("3+4={}", test_basic::add_numbers(3,4));
}
```

**Comment by EPashkin** [comment]
UPD: Changed `main` code for better debugging

**Comment by BIMSOMS** [comment]
Hi @EPashkin ,

@oli-obk solved it.
he replaced 
    crate-type = ["dylib"]
with
    crate-type = ["cdylib"]
in cargo.toml
