### ISSUE TITLE
gtk::Image::new_from_icon_name() should take a gtk::IconSize instead of i32

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk#722]
See title. The C API reference and the .gir file list that enum, but the generated code has an i32. Not sure why :) @EPashkin do you know?

**Comment by EPashkin** [comment]
See #439, seems it time to fix this Gtk-3.0.gir, 
as https://github.com/gtk-rs/gir/issues/264 still in progress

**Comment by sdroege** [comment]
Ah, duplicate of that one then. Thanks
