### ISSUE TITLE
`DialogExt::connect_response` should be `ResponseType` and not `i32`

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk#724]
http://gtk-rs.org/docs/gtk/trait.DialogExt.html#tymethod.connect_response

**Comment by EPashkin** [comment]
Agree

**Comment by GuillaumeGomez** [comment]
Should I update the xml file or just implement it manually?

**Comment by GuillaumeGomez** [comment]
Problem is a bit more general than what I originally thought as you can see [here](http://gtk-rs.org/docs/gtk/trait.InfoBarExt.html#method.add_button) for example. I'll update the xml files.

**Comment by EPashkin** [comment]
You right, with that many functions better fix xml
