### ISSUE TITLE
Add other variant into ResponseType

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk#725]
Shouldn't we add an `Other(i32)` variant into the [`ResponseType`](http://gtk-rs.org/docs/gtk/enum.ResponseType.html) enum? Docs says that gtk response types are below 0 but that users can provide custom ones. Shouldn't it be wrapped as well?

**Comment by sdroege** [comment]
Yes

**Comment by EPashkin** [comment]
Don't we already have `#[doc(hidden)]__Unknown(i32),` ?

**Comment by EPashkin** [comment]
If it need be in doc, IMHO better don't copy `ResponseType`
but change gir to allow enable docs for it or, better, change it name.

**Comment by sdroege** [comment]
Yes, the `Unknown` here should be just made public... and maybe renamed into `Other` and we might want to add a check that the value given does not overlap with any of the others.

**Comment by EPashkin** [comment]
Not sure how to do check normally,
maybe just add `fn normalize(self)->ResponseType{ from_glib(self.to_glib()) }` is enough?

**Comment by GuillaumeGomez** [comment]
We could just implement `TryFrom` and do the check at this point? Not really sure how we could enforce the check before even creating the variant...

**Comment by sdroege** [comment]
`TryFrom` is not stable yet. But yes, you'd need some kind of function.

Maybe just add a `ResponseType::other(type_: i32)` function that panics on invalid inputs?

**Comment by EPashkin** [comment]
I meant case when one user create `ReponseType::Other(-4)` instead `ResponseType::DeleteEvent` and use it.
It not problem in C part but if other user get this value in rust (not from C) and attempt to `match` can gone wrong.

**Comment by EPashkin** [comment]
Adding constructor `other` can solve problem, if `Unknown` not made public

**Comment by GuillaumeGomez** [comment]
That would work but I find it a bit counter-intuitive... But if no better solution, that would do it.

**Comment by sdroege** [comment]
We still need to make the other, unknown variant "public" (not hidden) though, otherwise users can't easily match on their custom response types.

**Comment by EPashkin** [comment]
Then how we can solve problem https://github.com/gtk-rs/gtk/issues/725#issuecomment-428837751 ?

**Comment by sdroege** [comment]
> Then how we can solve problem [#725 (comment)](https://github.com/gtk-rs/gtk/issues/725#issuecomment-428837751) ?

Add a panic in `to_glib()` for an invalid value for "other" responses and document this

**Comment by sdroege** [comment]
Or only allow `u16` for "other" types :)

**Comment by EPashkin** [comment]
Last idea maybe good, but need full copy generated code to manual.

**Comment by GuillaumeGomez** [comment]
> > Then how we can solve problem #725 (comment) ?
> Add a panic in to_glib() for an invalid value for "other" responses and document this

But then it'd panic and I'm not a big fan of this... And if we allow only `u16` types, it means you won't be able to instantiate a "known" kind from `i32` directly.

**Comment by GuillaumeGomez** [comment]
I'm having in mind cases where a defined `ResponseType` isn't available on all platforms but maybe I'm being too careful here...

**Comment by sdroege** [comment]
The people can still use the hidden `__Unknown` variant as a workaround
