### ISSUE TITLE
Accessibility?

### ISSUE THREAD

**Issue by SoniEx2** [gtk-rs/gtk#737]
Uh, is there any way to use accessibility with gtk-rs?

**Comment by sdroege** [comment]
Do you know what is required for that, I don't know how accessibility in GTK works. I would've assumed that it works by default unless you write custom widgets.

In any case, there are no ATK bindings yet (only the -sys part), which is the accessility library used by GTK. In case any specific API from there is required.

**Comment by GuillaumeGomez** [comment]
We added the [gtk-rs/atk](https://github.com/gtk-rs/atk/) repository.

**Comment by sdroege** [comment]
Unclear how it is used or if anything else is missing. At least an example app would be useful to have

**Comment by GuillaumeGomez** [comment]
Noted.

**Comment by sdroege** [comment]
I meant it would be good if the original reporter checks now if everything is in place, reports back and ideally sends an example :) none of us two know anything about how the accessibility stuff is working

**Comment by GuillaumeGomez** [comment]
I forgot to generate it for gtk. The PR is on its way (and so is the example hehe).
