### ISSUE TITLE
Adding string containing only null character to TextBuffer crashes

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#743]
Test example:

```rust
extern crate gtk;
use gtk::prelude::*;

fn main() {
    if gtk::init().is_err() {
        return;
    }
    
    let text_buffer = gtk::TextBuffer::new(None);
    let mark = text_buffer.get_insert().unwrap();
    let mut iter = text_buffer.get_iter_at_mark(&mark);
    text_buffer.create_mark("end", &iter, false);
    
    // Create our null-character string
    let null_byte = vec![0];
    let null_string = String::from_utf8_lossy(&null_byte);
    text_buffer.insert(&mut iter, &null_string);

    // Start our GUI main loop
    gtk::main();
}
```

It'll crash immediately at runtime. It's not clear to me that this isn't a bug in gtk-rs. In Rust it's valid to have a String with null-bytes. From reading [the docs for `gtk_text_buffer_insert`](https://developer.gnome.org/gtk3/stable/GtkTextBuffer.html#gtk-text-buffer-insert), it's not clear to me that it's valid. Would it make sense to have some checks in the gtk-rs wrapper to catch this situation? Maybe use a type that guarantees no null bytes (if there is such a thing).

**Comment by sdroege** [comment]
Why would this crash though? We would send `b"\0\0"` to the C function and specify `1` as length. The C function would then handle it as a string of 1 character, and would actually not do anything because the string is terminated at the beginning.

This should really not crash unless we actually pass a NULL pointer to the C function :)

Can someone get a backtrace with debug packages for GTK installed?

**Comment by sdroege** [comment]
Ah it doesn't actually crash, it only panics. Problem in our translation code.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(0, [0])', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at libcore/result.rs:808
  10: <str as glib::translate::ToGlibPtr<'a, *const i8>>::to_glib_none
             at /home/slomo/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.6.0/src/translate.rs:332
  11: <O as gtk::auto::text_buffer::TextBufferExt>::insert
             at /home/slomo/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.5.0/src/auto/text_buffer.rs:535
  12: testnig::main
             at src/main.rs:17
  13: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  17: std::rt::lang_start
             at libstd/rt.rs:74
  18: main
  19: __libc_start_main
  20: _start
```

**Comment by sdroege** [comment]
See https://doc.rust-lang.org/std/ffi/struct.CString.html#method.new

```
This function will consume the provided data and use the underlying bytes to construct a new string, ensuring that there is a trailing 0 byte. This trailing 0 byte will be appended by this function; the provided data should not contain any 0 bytes in it.
```

0 bytes are not a problem for GLib based APIs (they just pre-maturely terminate the string), so we should do things a bit different I guess.

**Comment by GuillaumeGomez** [comment]
Is it really a problem? The issue is on user's side after all... Is there a case where a '\0' is required.

**Comment by sdroege** [comment]
I'd say it's not a problem, we safely panic on wrong input here and it's likely not what the programmer intended.

**Comment by GuillaumeGomez** [comment]
Maybe we should use `.expect` instead of `.unwrap` (I just assumed we were using `unwrap`, which is bad) to provide some help for users?

**Comment by sdroege** [comment]
Sure why not :)

**Comment by GuillaumeGomez** [comment]
Then I'll let you do it. :p (If you don't have time or don't want to do it, I'll do it this evening, don't worry :wink: )

**Comment by Susurrus** [comment]
I think that's a great addition, adding that extra help text.

I am wondering if there's anything else to be done here. I was surprised that passing a valid UTF-8 string, like I do in this example, causes these kinds of problems, since the datatype for this function is `String`. I'm wondering if that's not the datatype that should be used here, rather `CString`. I think that'd make it more clear what accepted values are. Would that make sense?

**Comment by sdroege** [comment]
CString is not very user-friendly to use unfortunately. People generally work with String or &str, and that's what all APIs work with.

You'll get similar errors from this one when using any of the libstd functions that internally use CString on user-provided data to call into C APIs.

I think it's arguable if a `\0` somewhere should be considered an error or not. It's probably never what you actually want, so an error for this seems fine (do you have a valid use-case?). But on the other hand it's not going to do harm in *most* cases apart from the string being cut earlier.
