### ISSUE TITLE
Mutating .connect()'d Signal Args

### ISSUE THREAD

**Issue by jupart** [gtk-rs/gtk#744]
I'm working with gtk-rs, trying to connect to the "get-child-position" signal for a gtk::Overlay. It passes &[glib::Value], where the third element is the gtk::Rectangle for size. This being &[glib::Value], I can't mutatte any of the elements, so it seems like I can't set the size as it's stated in the doc here (http://gtk-rs.org/docs/gtk/struct.Overlay.html). Am I missing something? How can I set child positions this way?

```
    overlay.connect("get-child-position", false, |data: &[glib::Value]| {
        let rect = gtk::Rectangle { x: 10, y: 10, width: 10, height: 10 };
        data[2].downcast::<gtk::Rectangle>().unwrap().set(Some(&rect));
        Some(true.to_value())
    }).unwrap();

```

**Comment by EPashkin** [comment]
@jupart http://gtk-rs.org/docs/gtk/trait.OverlaySignals.html#tymethod.connect_get_child_position not works?

**Comment by sdroege** [comment]
Alternatively you can also do this with unsafe code in the generic signal connector. The problem here is that this violates the generic API contract of signals, you are generally not supposed to change arguments... so it needs a special solution for this specific case.

**Comment by jupart** [comment]
Wow, y'all are quick, thank you. I'll try both solutions, it seems like this is more my issue than this project's :)
