### ISSUE TITLE
Foo/FooExt distinction is really unfortunate -- UX suffers

### ISSUE THREAD

**Issue by osa1** [gtk-rs/gtk#763]
The whole Foo/FooExt distinction us really unfortunate. As far as I understand the reason why this exists is because `Foo` is auto-generated but `FooExt` is hand written. Ideally stuff in `FooExt` would be in `Foo`. Currently given a callback like

```
fn drag_begin(w: &impl WidgetExt, ctx: &DragContext) { ... }
```

I can't see type of `w` or use the `Debug` impl for `Widget` in the method because as far as I can see there's no way to get a `Widget` from a `WidgetExt`, even though `Widget` is the only implementor of `WidgetExt`.

I'm wondering how hard it is to fix this. I think we should just get rid of all `FooExt` traits and modules and just move everything into structs. Any ideas /opinions?

**Comment by osa1** [comment]
OK more thoughts. Maybe `FooExt` makes sense for some types (when there are multiple implementations). However the type

```
fn(&impl WidgetExt)
```

is much more restrictive than

```
fn(&Widget)
```

The problem is the actual GTK callback takes a widget argument, so I don't understand in `gtk-rs` we have a `&impl WidgetExt` argument and not a much more flexible `&Widget` argument. Ideas

**Comment by sdroege** [comment]
The `Ext` traits are not for that reason but to be able to call any of the methods of those traits on the type itself **and** any of its subclasses. E.g. you can call `gtk::WidgetExt::activate()` on a `&gtk::Widget` but also on a `&gtk::Button` without having to manually upcast.

Usually what you do in generic functions is to make use of the `IsA<_>` trait for that (which is unfortunately not object-safe and I didn't figure out yet how to make it object-safe under all the requirements). So in your case you would do

```rust
fn drag_begin<W: IsA<Widget>>(w: &W, ctx: &DragContext) { ... }
```

The `Ext` and `ExtManual` (the latter are the ones that are not autogenerated, the former are autogenerated in 99% of the cases) are usually never directly used.

**Comment by osa1** [comment]
> The rules for object-safety are in the book somewhere :)

Which book?

Is there a IRC/discord/whatever channel for gtk-rs development?

**Comment by sdroege** [comment]
Let's close this then? If you have any suggestions for how to improve the documentation, please let us know :)

**Comment by osa1** [comment]
Thanks for the help on IRC. This can be closed.
