### ISSUE TITLE
Essential ListStore functions missing?

### ISSUE THREAD

**Issue by osa1** [gtk-rs/gtk#765]
Looking at the GtkListStoreExt API I think there's currently no way to insert data. We need [`gtk_list_store_set()`](https://developer.gnome.org/gtk3/stable/GtkListStore.html#gtk-list-store-set) to make use of it.

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/gtk/blob/master/src/list_store.rs#L94

**Comment by sdroege** [comment]
They're not in the autogenerated trait because they can't be autogenerated unfortunately :) That's why they're in the `ExtManual` trait instead.

**Comment by osa1** [comment]
It'd be good if `ListStore`/`ListStoreExt` documentation mentioned this as this is otherwise pretty hard to discover .

**Comment by sdroege** [comment]
I agree, so let's keep this one open? This probably needs some rustdoc related fix though. @GuillaumeGomez what is needed for not only listing the normal `Ext` traits automatically in the docs of all the types but also the `ExtManual` (and potential platform specific ones)?

**Comment by sdroege** [comment]
@GuillaumeGomez rustdoc-stripper then :) It could mention all these traits in the docs at the top like it currently already does for the autogenerated ones

**Comment by GuillaumeGomez** [comment]
We only list non-manual ones. gir cannot know (at the time) about manual traits.

**Comment by EPashkin** [comment]
See https://github.com/gtk-rs/gir/issues/683, I don't start do it because still don't see good solution defining manual traits defined in parent crates.
Note: second approach solves all problem but code templates IMHO less understandable

**Comment by sdroege** [comment]
>  Note: second approach solves all problem but code templates IMHO less understandable

We need code templates for subclass code generation later anyway

**Comment by sdroege** [comment]
Manual traits are listed in the docs now
