### ISSUE TITLE
Test failure on 32bit apveyor

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gtk#783]
Test just not started https://ci.appveyor.com/project/GuillaumeGomez/gtk/builds/22365104/job/is1p7mr7tvvcfydq#L263
Error code https://answers.microsoft.com/en-us/windows/forum/all/stop-error-code-c0000139-entry-point-not-found/f37133d1-c1ba-407e-9e5d-fe429cdb7ef3
It repeats for me locally, I currently have no idea why, and what I can check yet
Gdk tests fine run locally,
Gtk test executable also run fine.

cc @GuillaumeGomez, @sdroege 

No idea what ??? meant, `depends` tool show much more dlls
```
eap@EAPCOMP3 MINGW32 /d/eap/rust/0/target/debug
$ ldd gtk-ed70585190e9fe22.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fffd5fb0000)
        ??? => ??? (0x77c00000)
        wow64.dll => /c/WINDOWS/System32/wow64.dll (0x7fffd31e0000)
        wow64win.dll => /c/WINDOWS/System32/wow64win.dll (0x7fffd38b0000)

eap@EAPCOMP3 MINGW32 /d/eap/rust/0/target/debug
$ ldd gdk-2d48edbfc5975191.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fffd5fb0000)
        ??? => ??? (0x77c00000)
        wow64.dll => /c/WINDOWS/System32/wow64.dll (0x7fffd31e0000)
        wow64win.dll => /c/WINDOWS/System32/wow64win.dll (0x7fffd38b0000)
```

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/gtk/pull/784 shows that something changed in environment,
previously tests succeeds

**Comment by sdroege** [comment]
What do you mean with the environment changed? When did it work before?

**Comment by EPashkin** [comment]
Oops, I forgot that no test was here on gtk before,
So maybe tests on gtk was broken long ago, at minimum for me locally.

For info: this PR based on #766, apveyor 32 passed here https://ci.appveyor.com/project/GuillaumeGomez/gtk/builds/22038642/job/vyhqw71dd3cwdxhw

**Comment by sdroege** [comment]
> For info: this PR based on #766, apveyor 32 passed here https://ci.appveyor.com/project/GuillaumeGomez/gtk/builds/22038642/job/vyhqw71dd3cwdxhw

But that does not run tests

I think this is a case of wrong DLLs in the PATH.

**Comment by EPashkin** [comment]
It repeated for me locally with my path not point to mingw64/bin but to mingw32/bin only,
and all command run from "mingw32 command prompt"
`cargo test` fails on gtk without running actual test,
on gdk it passed,
executables for gtk runs fine, so entry points IMHO normal.
ldd shows something wrong for gtk and gdk test executables, but results same.
No idea what I can check next.

**Comment by sdroege** [comment]
Maybe we just disable the gtk tests on 32 bit then for now until someone figures that out? It's not like 32 bit Windows is such an important target anyway...

**Comment by EPashkin** [comment]
Update: on my machine `cargo test` nags about libcairo-2.dll can't find entry point __divmoddi4 in libgcc_s_dw2-1.dll,
seems rust have old version so removing it will helps.
Alternative test with --release
