### ISSUE TITLE
Allow GL rendering

### ISSUE THREAD

**Issue by Binero** [gtk-rs/gtk#79]
It would be nice to have bindings to [GtkGLArea](https://developer.gnome.org/gtk3/stable/GtkGLArea.html), and perhaps integrate this with [glium](https://github.com/tomaka/glium).

**Comment by GuillaumeGomez** [comment]
I'll try to add it in the week then ! Or maybe you wanna do it ? :-)

**Comment by gkoz** [comment]
I guess we'd have to add cargo features for GTK/GDK 3.16 :)
@Binero does that functionality depend on any additional libraries or is that handled dynamically by GDK?

**Comment by Binero** [comment]
@gkoz What functionality? The one of GtkGlArea? If so, I'm not too familiar with the inner workings of GTK, sorry.

**Comment by gkoz** [comment]
I'd expect GL features to rely on some additional libs. That might require some handling in the build script.

**Comment by Binero** [comment]
Going from IRC, all it requires is libGL to be on your system.

**Comment by Binero** [comment]
Any update on this?

**Comment by GuillaumeGomez** [comment]
Not at all but it's nice you asked about it since I totally forgot. I'll take a look at it in the week-end.

**Comment by yggie** [comment]
+1, would be nice to have this

**Comment by GuillaumeGomez** [comment]
Great news : [#75](https://github.com/gtk-rs/gdk/pull/75) and #166. However I'll need someone to test them for me (my gdk and gtk versions are too low...).

**Comment by gkoz** [comment]
Those PRs have been merged, so so we have a `GLArea` (in `master` for now).

The suggestions for how exactly this should be integrated with `glium` are welcome.

**Comment by gkoz** [comment]
The `GLArea` bindings have been implemented in the aforementioned PRs.

> The suggestions for how exactly this should be integrated with glium are welcome.

The integration discussion is at https://github.com/gtk-rs/gdk/issues/81
