### ISSUE TITLE
EntryBufferExt does not exist

### ISSUE THREAD

**Issue by BrainBlasted** [gtk-rs/gtk#802]
With the latest version of gtk-rs, EntryBufferExt is missing. This means there's no way to connect to its signals.

**Comment by GuillaumeGomez** [comment]
Since it's a "manual" object, the issue might come from there. That remains surprising though... Taking a look.

**Comment by EPashkin** [comment]
No `EntryBufferExt` was in 0.5.0 too, and IMHO, newer was.
@BrainBlasted Can you tell what version you used and which function you needed?

**Comment by BrainBlasted** [comment]
Made a mistake, it's not the latest version but 0.5.0 I'm using. However, the [`gtk::EntryBuffer` docs](https://gtk-rs.org/docs/gtk/struct.EntryBuffer) indicate it should be there for 0.6.0, but the link is a 404.

>  which function you needed?

I need access to the signals, specifically inserted-text.

**Comment by okias** [comment]
https://gtk-rs.org/docs/gtk/struct.EntryBuffer.html#method.get_text Implements -> EntryBufferExt

**Comment by sdroege** [comment]
@GuillaumeGomez Needs some documentation fixes, dead links :)

**Comment by GuillaumeGomez** [comment]
There is no `BufferEntryExt` trait. However, we seem to generate it into the [vendor.md](https://github.com/gtk-rs/lgpl-docs/blob/master/gtk/vendor.md) file. I guess that the issue is on gir side.

**Comment by GuillaumeGomez** [comment]
I confirmed that the bug came from gir. I'll open an issue there.

**Comment by sdroege** [comment]
Let's track it there then
