### ISSUE TITLE
Cannot download gtk-rs dependencies

### ISSUE THREAD

**Issue by remontees** [gtk-rs/gtk#803]
Hi!

I've tried to add gtk-rs to my cargo.toml including the following declaration (the same as the one in the doc) :

```
[dependencies.gtk]
version = "0.6.0"
features = ["v3_10"]
```

And Cargo gave me the following error message :

```
cargo build
    Updating crates.io index
error: failed to select a version for `gtk`.
    ... required by package `...`
versions that meet the requirements `^0.6.0` are: 0.6.0

the package depends on `gtk`, with features: `v3_10` but `gtk` does not have these features.


failed to select a version for `gtk` which could resolve this conflict
```

Am I just a little bit stupid or is this a real error when somebody is trying to include gtk-rs to its project?

**Comment by fengalin** [comment]
Hi @remontees. In `gtk-rs/gtk-0.6.0`, the earliest GTK version you can depend on is `v3_16`. See in: https://github.com/gtk-rs/gtk/blob/20af60a54bdc12132611112128866c280dfea9c3/Cargo.toml

**Comment by remontees** [comment]
Hi @fengalin 
I saw it after. But that's not what is written here https://gtk-rs.org/ (and obviously new users will follow these wrong instructions!!).

**Comment by fengalin** [comment]
Oh, I see. Do you want to send a PR to https://github.com/gtk-rs/gtk-rs.github.io?

**Comment by remontees** [comment]
@fengalin Done, thank you for your answers.
