### ISSUE TITLE
run() for gtk::Assistant?

### ISSUE THREAD

**Issue by mpipo** [gtk-rs/gtk#806]
Hello,

Is there a way to emulate Dialog's ```run()``` for Assistant? I want to wait before returning a value from a function.

Here's an example of what I'm trying to do:

```rust
pub fn first_setup() -> Option<String> {
    let builder = Builder::new_from_string(include_str!("setup.glade"));
    let assistant = builder.get_object::<Assistant>("setup").unwrap();
    let input_field = builder.get_object::<Entry>("setup_input_field").unwrap();
    match assistant.run() {
        -5 => { // "Finish" selected
            let result = input_field.get_text().unwrap().as_str().to_string();
            assistant.destroy();
            return Some(result);
        },
        _ => { // "Cancel"
            assistant.destroy();
            return None;
        }
    }
}
```

**Comment by sdroege** [comment]
No, it's not a subclass of `Dialog` and also doesn't have its own `run()` function. The API works differently.

**Comment by mpipo** [comment]
Thanks for the reply.

Do you have any ideas how I'd go about it though?

I know there's ```assistant.show_all()``` but it doesn't seem to wait and values would be returned immediately, which is not what I want.

**Comment by sdroege** [comment]
It works like any other window, so you would have to emulate that. How depends on the structure of your application
