### ISSUE TITLE
No icons & broken FileChooserDialog

### ISSUE THREAD

**Issue by Timmmm** [gtk-rs/gtk#820]
Creating a directory FileChooserDialog looks like this by default on OSX:

![image](https://user-images.githubusercontent.com/376842/58803951-8f16b080-8608-11e9-931f-6b07c7ca9f08.png)

The icons are all broken and the open/cancel buttons are missing. Maybe there is something extra you need to do to set up the theme, but I didn't see it mentioned anywhere in the tutorial and this is quite a bad out-of-the-box experience. :-/

**Comment by GuillaumeGomez** [comment]
You seem to be using OSX. I *think* the problem is simply that GTK doesn't embed its icons (it does now but in a recent version). Windows has the same issue. I don't really know how to fix it though (except by providing the icons yourself).

An idea maybe @sdroege @EPashkin ?

**Comment by Timmmm** [comment]
Ah, the icons seem to be in `/usr/local/Cellar/gtk+3/3.24.8/share/icons`. Presumably I need to call [`GtkIconThemeExt::append_search_path()`](https://gtk-rs.org/docs/gtk/trait.IconThemeExt.html?search=#tymethod.append_search_path) (`set_search_path()` doesn't seem to be exposed for some reason).

I tried this in my `startup` signal handler:

	IconTheme::get_default().unwrap().append_search_path("/usr/local/Cellar/gtk+3/3.24.8/share");

Also `share/icons` and `share/icons/hicolor`, but none had any effect.

**Comment by Timmmm** [comment]
> Ah, the icons seem to be in /usr/local/Cellar/gtk+3/3.24.8/share/icons.

Actually scratch that, there are only a couple of random demo app icons in there. Where are the icons supposed to be?

**Comment by GuillaumeGomez** [comment]
What tutorial were you referring to btw? It'd be interesting to add those dependencies into it.

**Comment by fengalin** [comment]
@Timmmm I don't have a Mac to test this, could you try with:

```
brew install adwaita-icon-theme
```

**Comment by Timmmm** [comment]
@GuillaumeGomez I would add them [here](https://gtk-rs.org/docs-src/requirements.html) - where it says `brew install gtk+3`, change it to `brew install gtk+3 gnome-icon-theme`.

@fengalin Installing `gnome-icon-theme` installs `adwaita-icon-theme` as a dependency.

I suspect the missing icons are related to the fact that on Gnome the buttons are in the title bar (as discussed [here](https://elementaryos.stackexchange.com/questions/1638/buttons-are-missing-in-the-file-chooser-dialog-what-should-i-do)). I'm not sure how to change that setting though, given that we're not using `gsettings`.

**Comment by Timmmm** [comment]
Well it can't be the `DialogsUseHeader` setting because

	gtk::Settings::get_default().expect("Couldn't get settings").set_property_gtk_dialogs_use_header(false);

Has no effect, and setting it to `true` makes it look a bit different (but still no ok/cancel buttons).

**Comment by sdroege** [comment]
Best to discuss this at https://discourse.gnome.org as this is a general GTK problem and unrelated to the bindings.
