### ISSUE TITLE
[Bug] - 'libgtk-3 was configured with `--enable-debug=no`

### ISSUE THREAD

**Issue by Edu4rdSHL** [gtk-rs/gtk#821]
I'm facing an issue with my project, it was working fine but stopped running with the following message:

```
thread 'main' panicked at 'libgtk-3 was configured with `--enable-debug=no`. See https://github.com/gtk-rs/gtk/issues/270 for details', /home/sechacklabs/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.6.0/src/rt.rs:141:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
I was seeing the code of the gtk crate and seems that it looks in the system library for get the debug flag https://github.com/gtk-rs/gtk/blob/master/src/rt.rs#L139, I'm using ArchLinux and doesn't see the  --enable-debug=no flag in the [PKGBUILD for gtk3](https://git.archlinux.org/svntogit/packages.git/tree/repos/testing-x86_64/PKGBUILD?h=packages/gtk3#n42).

What can be the cause?

JFYI: new gtk projects are facing the same issue.

EDIT:

I tried `cargo clean` already, removed the cached crates and recompile again.

**Comment by Edu4rdSHL** [comment]
Downgrading from [testing] fix the issue.

**Comment by sdroege** [comment]
> Downgrading from [testing] fix the issue.

What was the actual problem?

**Comment by heftig** [comment]
GTK3 was built using meson with `--buildtype=release`, which is equivalent to the old `--enable-debug=no`.

**Comment by sdroege** [comment]
That seems like a bug in the meson build, see the old documentation and also https://github.com/gtk-rs/gtk/issues/270

> Thus --enable-debug=no should not be used for stable releases of GLib.

**Comment by heftig** [comment]
That said, buildtypes `plain` and `minsize` (anything but `debug` and `debugoptimized`) are also broken.

You check for `G_ENABLE_DEBUG` being enabled, which it isn't. However, what you actually care about is `G_DISABLE_CHECKS` being disabled, which it is.

**Comment by sdroege** [comment]
Indeed. There's no way to check for that a runtime though :)

Maybe the check should just be removed from `rt.rs`, and people running builds with `G_DISABLE_CHECKS` will just have to live with the consequences.

**Comment by sdroege** [comment]
So, this should be reopened @GuillaumeGomez .

With latest GTK the assumptions that were the reasons for adding this assertion are not true anymore, and we can't detect this anymore at runtime reliably.

The rationale for adding this assertion was that we don't want to allow running gtk-rs with a gtk that is built with assertions disabled (as that will easily cause memory unsafety, etc.). The way to detect that was to check for a `--enable-debug=no` build, but that was not actually the same thing. Assertions could be disabled independent of that too.

Nowadays a non-debug build has the assertions enabled, so we can run just fine with a non-debug build. And we have no way of detecting at runtime if assertions are enabled or not.

IMHO we should simply remove the assertion from our code. It's the user's problem if they build gtk without assertions and want stuff to crash on them, and it's something that can't really happen accidentally but the user would have to opt-in to that.

**Comment by sdroege** [comment]
So I'd suggest removing the assertion. Opinions @GuillaumeGomez @EPashkin ?

**Comment by GuillaumeGomez** [comment]
If it's useless, let's remove it.
