### ISSUE TITLE
Builder child / parent methods require explicit upcasting

### ISSUE THREAD

**Issue by mmstick** [gtk-rs/gtk#834]
When constructing a `gtk::Box`
```rust
let layout = gtk::BoxBuilder::new()
    .spacing(24)
    .halign(gtk::Align::Center)
    .margin_top(48)
    .build();

layout.set_orientation(gtk::Orientation::Vertical);
```

It is necessary to upcast it into a `gtk::Container`

```rust
let layout = layout.upcast::<gtk::Container>();
```

to use it as the parent value in another builder's `parent()` methods.

```rust
gtk::LabelBuilder::new()
    .label("<b>System Firmware</b>")
    .use_markup(true)
    .parent(&layout)
    .build();

let system_firmware = gtk::ListBoxBuilder::new()
    .parent(&layout)
    .build();
```

Similar is required of the `child()` method requiring the input value to be a `Widget` instead of a `&dyn IsA<Widget>`.

**Comment by sdroege** [comment]
>  instead of a `&dyn IsA<Widget>`

`IsA<_>` is unfortunately not object-safe, see https://github.com/gtk-rs/glib/issues/222.

For the other things, CC @antoyo

**Comment by antoyo** [comment]
I see what you're trying to do, but I don't think it works this way.
From the [documentation](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-set-parent), we can see that this property can only be used when implementing sub-classes of `gtk::Container`.
Which `child()` method do you mean? I can't find it.

**Comment by mmstick** [comment]
@antoyo https://gtk-rs.org/docs/gtk/struct.BoxBuilder.html#method.child

Calling it on a container, or the `parent()` method on a child to a container, seems to work the same way as using `add()`.

**Comment by antoyo** [comment]
Ok, for `child()`, that makes sense.
I guess the `gir` file is causing an issue here because the [setter](https://gtk-rs.org/docs/gtk/trait.ContainerExt.html#tymethod.set_property_child) also only takes `&Widget`.

**Comment by antoyo** [comment]
Should be fixed by [this](https://github.com/gtk-rs/gir/pull/853).

**Comment by antoyo** [comment]
@GuillaumeGomez: Can you close this issue?
