### ISSUE TITLE
TreeModelFilterExt::set_visible_func() takes only 2 parameters

### ISSUE THREAD

**Issue by jounathaen** [gtk-rs/gtk#840]
set_visible_func in gtk-rs takes only 2 parameters, self and a filter function. 

https://github.com/gtk-rs/gtk/blob/7828a063a223249f288c549f8def6773fcaa311d/src/auto/tree_model_filter.rs#L47

In C gtk you can also pass a generic data struct to the filter function:
https://developer.gnome.org/gtk3/stable/GtkTreeModelFilter.html#gtk-tree-model-filter-set-visible-func

Is this on purpose? I tried to get some data (from a search entry) into the filter function, to filter based on user input, but I don't know how to do it without the additional parameter.

Thx and regards!

**Comment by GuillaumeGomez** [comment]
A closure capture its environment when it's created. I recommend you to take a look at the examples (both rust ones and gtk-rs ones) to see how it works.

**Comment by jounathaen** [comment]
I'm sorry to further bother you, but could you provide me an exact pointer?
I didn't found an example which helped me.

**Comment by GuillaumeGomez** [comment]
Sure. I didn't find in the examples repository (don't have much time to look around) but here is an up-to-date example: https://github.com/GuillaumeGomez/process-viewer/blob/master/src/procs.rs#L125

**Comment by jounathaen** [comment]
Great, thanks a bunch :+1:
