### ISSUE TITLE
No StatusIcon widgets after updating 0.7+ version

### ISSUE THREAD

**Issue by gmg137** [gtk-rs/gtk#842]
I need to use the status bar icon, but after updating gtk-rs version 0.7 I found that StatusIcon has been deleted. What should I do?

**Comment by sdroege** [comment]
According to the GTK documentation:

> GtkStatusIcon has been deprecated in 3.14. You should consider using notifications or more modern platform-specific APIs instead. GLib provides the GNotification API which works well with GtkApplication on multiple platforms and environments, and should be the preferred mechanism to notify the users of transient status updates. See this [HowDoI](https://wiki.gnome.org/HowDoI/GNotification) for code examples.

**Comment by sdroege** [comment]
Basically, everything that was deprecated in a version lower than the minimum version we support is not part of the bindings anymore and the minimum version was bumped to 3.14 recently.

**Comment by gmg137** [comment]
thank you.
