### ISSUE TITLE
MenuExt::set_property_attach_widget() should take IsA<Widget> instead of Widget

### ISSUE THREAD

**Issue by Cogitri** [gtk-rs/gtk#846]

**Comment by sdroege** [comment]
Yes, do you want to provide a PR for this?

**Comment by Cogitri** [comment]
Would like to, but am on holidays, so I don't have a Laptop on me :)

**Comment by nt8r** [comment]
This has since been [fixed](https://gtk-rs.org/docs/gtk/trait.GtkMenuExt.html#tymethod.set_property_attach_widget). Close?

**Comment by sdroege** [comment]
Thanks for checking!
