### ISSUE TITLE
Missing methods from FileExt trait

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk#847]
In the gnome developer docs i found the method [enumerate_children](https://developer.gnome.org/pygobject/stable/class-giofile.html#method-giofile--enumerate-children) to list the files inside a directory. There is no such method inside the FileExt trait, so there is no way to list files in a directory using gio safely (the method gio_sys::g_file_enumerate_children is marked unsafe)

**Comment by sdroege** [comment]
That requires adding the `FileEnumerator` type. Looks like all that can be autogenerated then

**Comment by EPashkin** [comment]
Yes it generated just fine.
@GuillaumeGomez maybe you include "Gio.FileEnumerator" to https://github.com/gtk-rs/gio/pull/229?

**Comment by GuillaumeGomez** [comment]
Sure.

**Comment by GuillaumeGomez** [comment]
Done.

**Comment by sdroege** [comment]
This can be closed now, the PR was merged
