### ISSUE TITLE
GString is privade but some methodes return it.

### ISSUE THREAD

**Issue by theScrabi** [gtk-rs/gtk#850]
Either I didn't understand the lib yet or there is something weird going on.
GString which according to [Documentation](https://gtk-rs.org/docs/glib_sys/struct.GString.html) lies in `std::glib_sys::GString` is private:
```
error[E0603]: extern crate `glib_sys` is private
 --> src/main.rs:3:10
  |
3 | use gtk::glib_sys::GString;
  |
```

However some methods like [`EntryExt.get_text()`](https://gtk-rs.org/docs/gtk/trait.EntryExt.html#tymethod.get_text) do return it.
So I can write  
`let my_text = my_entry.get_text().unwrap()`  
but i can not write `let my_text:GString = my_entry.get_text().unwrap()`

What am I doing wrong?

**Comment by sdroege** [comment]
On 13 July 2019 16:32:52 EEST, Christian Schabesberger <notifications@github.com> wrote:
>Either I didn't understand the lib yet or there is something weird
>going on.
>GString which according to
>[Documentation](https://gtk-rs.org/docs/glib_sys/struct.GString.html)
>lies in `std::glib_sys::GString` is private:
>```
>error[E0603]: extern crate `glib_sys` is private
> --> src/main.rs:3:10
>  |
>3 | use gtk::glib_sys::GString;
>  |
>```
>
>However some methods like
>[`EntryExt.get_text()`](https://gtk-rs.org/docs/gtk/trait.EntryExt.html#tymethod.get_text)
>do return it.
>So I can write  
>`let my_text = my_entry.get_text().unwrap()`  
>but i can not write `let my_text:GString =
>my_entry.get_text().unwrap()`
>
>What am I doing wrong?

This is `glib::GString`, which is not the same as glib_sys::GString` (that's the FFI C struct and `glib::String` is the binding of that one, confusing yes). The latter is also not private though, but you have to add the right crate.


-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdroege** [comment]
Does this answer your question or is there still something missing?

**Comment by theScrabi** [comment]
I didn't try it yet. But the answer is what i was looking for, thanks :)
