### ISSUE TITLE
gtk::BoxBuilder is missing orientation() 

### ISSUE THREAD

**Issue by HossainAdnan** [gtk-rs/gtk#892]
Hi, if I'm not mistaken, Gtk-rs seems to provide builder patterns for building widgets. Hence I can't help but notice that the `gtk::BoxBuilder` is missing something similar to `orientation(&self, orientation: gtk::Orientation) -> Self` method. Is this intentional?

```rust
let hbox = gtk::BoxBuilder::new().orientation(gtk::Orientation::Horizontal).spacing(5).build();
// should be similar to
let hbox = gtk::Box::new(gtk::Orientation::Horizontal, 5);
```

It's not an issue, it's just a question. 
Also, on a **very** unrelated note, is there any persistent platform (forum, not a chat platform) where one can discuss Gtk-rs related topics?

**Comment by EPashkin** [comment]
@HossainAdnan Thanks for reporting, property "orientation" was in interface Orientable, seems builder generator not scan these.

**Comment by GuillaumeGomez** [comment]
@HossainAdnan: https://gtk-rs.org/docs-src/contact

**Comment by EPashkin** [comment]
All related PRs merged, so this can be closed
