### ISSUE TITLE
Please reexport FFI helper definitions

### ISSUE THREAD

**Issue by dcz-purism** [gtk-rs/gtk#897]
It would be great if there was a public interface to the FFI interfaces, e.g. the `glib::translate` traits, and `gtk_sys` pointer types used in those traits. It would allow an application to be converted to Rust piecewise instead of in one go.

The experimental code I tried to implement but had to give up after realizing that the required definitions aren't public: https://source.puri.sm/dorota.czaplejewicz/squeekboard/commit/e1eecc70c8fa94cf92efc9e2dc336503ec01391d

**Comment by sdroege** [comment]
Which parts exactly are missing and are not exported?

The raw C FFI types are available via the -sys crates, and with that, the types from the non-sys crates and glib::translate you should have everything needed.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dcz-purism** [comment]
I wasn't able to import the `glib::translate::FromGlibPtrNone` trait, and I couldn't import `gtk_sys::GtkWidget`. It's not to say that they are missing; of course they can be found in the respective crates.

What I'm saying is that if I try to import them for the purpose of passing to *gtk-rs*, e.g. pass `gtk_sys::GtkWidget` obtained from an `extern crate gtk_sys` to `gtk::PopoverMenu::set_relative_to`, then I might have 2 incompatible `GtkWidget` types on my hands.

The reason for that is that I'd have to import `gtk_sys` as a separate crate, and it may be mismatched with the `gtk_sys` version used by the `gtk` crate, duplicating their contents in an incompatible way.

That's why I mention *re*exporting - if `gtk` exposes `pub gtk_sys`, then I can safely use `gtk::gtk_sys::GtkWidget` in `gtk::PopoverMenu::set_relative_to`, without worrying about mismatched versions.

Same goes for traits from glib.

**Comment by EPashkin** [comment]
Function need `Widget` that "safe" proxy on `GtkWidget`
`fn set_relative_to<P: IsA<Widget>>(&self, relative_to: Option<&P>);`

Mismatched version will just not compile as rust allow link gtk3xx.sys only one time

**Comment by dcz-purism** [comment]
Wow, I thought that differing paths would prevent it, but it actually compiles: https://source.puri.sm/dorota.czaplejewicz/squeekboard/commit/5b680e69e3f16a71e4d78657a885ffe48cd5e6fe

The only surprise I had there is that `gtk::set_initialized()` is needed, but other than that, it seems to be working fine. Thanks!

**Comment by sdroege** [comment]
I'm still not sure what the problem was, or what you thought would be a problem :) But I'm glad that it's working fine now!

**Comment by dcz-purism** [comment]
Oh - I thought that after importing `extern_crate glib`, `glib::foo` would be a different and separate symbol than `gtk::glib::foo` and that the compiler would refuse to use one as another, basically making them incompatible.
