### ISSUE TITLE
Support unpacking more Variants

### ISSUE THREAD

**Issue by dcz-purism** [gtk-rs/gtk#898]
I hit a snag when trying to unpack a Variant with the signature `a(ss)`. I ended up making some custom parsing, but it would be nice to have that out of the box. For reference, this is how I unpacked it: https://source.puri.sm/dorota.czaplejewicz/squeekboard/blob/406b4fda80f53627670db1843f3e678817411585/src/popover.rs#L87

**Comment by sdroege** [comment]
Wrong repository :) This should've been reported against the glib repository, and there we already have https://github.com/gtk-rs/glib/issues/113

@GuillaumeGomez Can you close this one?
