### ISSUE TITLE
Remove custom_title from headerbar

### ISSUE THREAD

**Issue by timarques** [gtk-rs/gtk#906]
Hi, 
i'm trying to remove custom_title from headerbar.
When i try headerbar.set_custom_title(None) gives me this error "cannot resolve `_: glib::object::IsA<gtk::auto::widget::Widget>".
how can i do this??

**Comment by sdroege** [comment]
`set_custom_title(None::<gtk::Widget>)` or `set_custom_title(gtk::NONE_WIDGET)` should do the job

**Comment by sdroege** [comment]
@GuillaumeGomez This can probably be closed :)

**Comment by timarques** [comment]
None::<gtk::Widget> gives me error "expected reference, found struct `gtk::auto::widget::Widget`"
gtk::NONE_WIDGET works fine
thanks

**Comment by sdroege** [comment]
I meant `None::<&gtk::Widget>`, sorry :)
