### ISSUE TITLE
No way of setting GtkWindowType

### ISSUE THREAD

**Issue by CodingJonas** [gtk-rs/gtk#907]
I need to create a popup. In the original gtk in c this is done through [gtk_window_new ()](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-new).

While I found the `GtkWindowType` definition of [GTK_WINDOW_POPUP](https://gtk-rs.org/docs/gtk_sys/constant.GTK_WINDOW_POPUP.html), I couldn't figure out how to set it for an `ApplicationWindow`, neither in the documentation nor in the source code.

Did I miss something or is this not implemented yet? Or am I following a completely wrong approach?

**Comment by EPashkin** [comment]
You sure that you need create popup main window? 
Main window not need be applicationwindow, see old example: https://github.com/gtk-rs/examples/blob/3585ee57bb7ad11177355cd7919774e630aa2de4/src/bin/basic.rs

Also seems is not recommended use this flag http://blog.borovsak.si/2009/05/using-pop-up-windows.html

**Comment by sdroege** [comment]
http://gtk-rs.org/docs/gtk/struct.Window.html#method.new this should work? `gtk::Window::new(gtk::WindowType::Popup)`.

**Comment by CodingJonas** [comment]
@EPashkin, I think you are right, I shouldn't need to explicitly set GtkWindowType. I think I missunderstood its usecase.

@sdroege Yes, not sure how I missed this!
