### ISSUE TITLE
Setting `xalign` property with an `f64` on `CellRendererText` fails with an unhelpful error

### ISSUE THREAD

**Issue by marcianx** [gtk-rs/gtk#912]
To right-justify a column's cells in a `TreeView`, I tried to set the `xalign` property on the column's `CellRendererText`. However, that seems to fail with "property can't be set from the given type". I'm having a difficult time finding an example to follow, and I'm not finding the documentation helpful in resolving this.

Minimal reproducible program:
```rust
use gio::prelude::*;
use gtk::prelude::*;

use gtk::{Application, CellRendererText};

fn main() {
    let application = Application::new(Some("foo"), Default::default()).unwrap();
    application.connect_activate(|_| {
        let renderer = CellRendererText::new();
        renderer.set_property("xalign", &1.0).unwrap(); // panics
    });
    application.run(&[]);
}
```

**Comment by marcianx** [comment]
Wow, it just clicked right now as happen to glance at the [C library docs](https://developer.gnome.org/gtk3/stable/GtkCellRenderer.html). It needs to be `&1.0f32` since that's a `gfloat` in the docs.

Could this bug thus be changed to a feature request for a much more comprehensible error? E.g. value type doesn't match or some such?

**Comment by EPashkin** [comment]
IMHO https://github.com/gtk-rs/glib/pull/513 fixed this problem

**Comment by sdroege** [comment]
Yes that will give a nicer error message now when unwrapping. Or you use `renderer.set_property_xaling(1.0)` or `renderer.set_alignment(1.0, yalign)`.

@GuillaumeGomez this can be closed :)
