### ISSUE TITLE
Rename WidgetExt::set_name() and BuildableExt::set_name()

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk#914]
And also get_name(). Currently it's inconvenient that they have the same name because you have to call them by also specifying the trait.

I would suggest `set_widget_name()` and `set_buildable_name()`. We should probably do the same for other duplicated functions.

@GuillaumeGomez @EPashkin opinions?

**Comment by EPashkin** [comment]
Agree

**Comment by GuillaumeGomez** [comment]
I agree as well. I'll take a look.
