### ISSUE TITLE
Librem 5 Support?

### ISSUE THREAD

**Issue by mezeipetister** [gtk-rs/gtk#920]
Do you have any idea how to optimize gtk for librem 5 using gtk.rs?

**Comment by sdroege** [comment]
Thanks for your interest in gtk-rs but this is really something to bring up with Purism. If there's anything we can help here that can happen but for now this is something that you have to discuss with Purism to find out what is missing, how things can be done with their phone, etc.

@GuillaumeGomez please close this :)

**Comment by bilelmoussaoui** [comment]
If you want to create adaptive applications using GTK you probably need Libhandy; there are Rust bindings already here https://gitlab.gnome.org/World/Rust/libhandy-rs.

**Comment by Kekun** [comment]
@mezeipetister I know there are libhandy bindings for Rust, some Rust apps use it, but given I have never written Rust yet I don't know where to find them nor how to use them. :( Maybe @jsparber knows.
