### ISSUE TITLE
gtk::Arrow not implemented?

### ISSUE THREAD

**Issue by artonio** [gtk-rs/gtk#933]
example from python:
```
button = Gtk.Button()
button.add(Gtk.Arrow(Gtk.ArrowType.LEFT, Gtk.ShadowType.NONE))
```

I can see gtk::ArrowType in the docs, but not the Arrow object

**Comment by EPashkin** [comment]
It was deprecated: https://developer.gnome.org/gtk3/stable/GtkArrow.html#gtk-arrow-new
```
gtk_arrow_new has been deprecated since version 3.14 and should not be used in newly-written code.
Use a GtkImage with a suitable icon.
```

**Comment by sdroege** [comment]
Yeah we should also hide `gtk::ArrowType` though. Who wants to make a PR? :)

**Comment by gdesmott** [comment]
@sdroege : is this just a matter of removing `Gtk.ArrowType` from `Gir.toml`?

**Comment by sdroege** [comment]
Yes

**Comment by gdesmott** [comment]
What about `src/auto/menu_button.rs` using it to bind the direction APIs?

**Comment by sdroege** [comment]
Hrm then this is actually fine. Only `GtkArrow` is deprecated and `GtkArrowType` is used in random other API and not deprecated yet.

@GuillaumeGomez This can be closed
