### ISSUE TITLE
Help with dependencies and versions problem

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [gtk-rs/gtk#935]
I have a project with these Gtk/Glib dependencies in my Cargo.toml

```toml
gdk-pixbuf = "0.7.0"

[dependencies.gtk]
version = "0.7.0"
features = ["v3_16"]

[dependencies.gio]
version = "0.7.0"
features = ["v2_44"]
```

It compiles and runs fine in local (Mac OS X Catalina).

But it fails in my travis build (on the Mac OS X and Linux version in the same way) with a linker error:
```= note: /home/travis/build/andrewdavidmackenzie/flow/target/debug/deps/libgdk-6524693c692a49c3.rlib(gdk-6524693c692a49c3.gdk.egbilgm9-cgu.0.rcgu.o): In function `_$LT$gdk..auto..enums..DevicePadFeature$u20$as$u20$glib..types..StaticType$GT$::static_type::hd236474da68a3eab':```
```/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/gdk-0.11.0/src/auto/enums.rs:731: undefined reference to `gdk_device_pad_feature_get_type'
          collect2: error: ld returned 1 exit status```

Any ideas what could be the  cause of this, I've spent a fair bit of time googling and trying alternatives with no luck.

**Comment by sdroege** [comment]
This most likely means that the version of GDK you have installed is too old. From what I can see that symbol was added in version 3.21.5.

That it fails this way with an older version installed and you not opting in to a GTK/GDK version newer than that via e.g. the `v3_22` feature flag might be caused by https://github.com/gtk-rs/gir/issues/839

**Comment by andrewdavidmackenzie** [comment]
Thanks for quick comment.

I tried to force 3_22 by:
- changing feature in Cargo.toml
- setting env GTK=3.22 in my build script (without this it fails differently)

And now I'm getting a different error which kind of makes sense:
```
   Compiling gdk-sys v0.9.1
error: failed to run custom build command for `gdk-sys v0.9.1`
Caused by:
  process didn't exit successfully: `/home/travis/build/andrewdavidmackenzie/flow/target/debug/build/gdk-sys-f897808c0cace2e7/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gdk-3.0" "gdk-3.0 >= 3.22"` did not exit successfully: exit code: 1
--- stderr
Requested 'gdk-3.0 >= 3.22' but version of GDK is 3.18.9
```

(that's Linux - Ubuntu Xenial)

I request the dependency installs via .tavis.yml "addons":
```yaml
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - libgtk-3-dev
  homebrew:
    packages:
      - gtk+3
      - glib
      - cairo
```

So, now I need to figure out how to ask travis to install a newer (> 3.22) version of Gtk/Gdk I think?

**Comment by sdroege** [comment]
> So, now I need to figure out how to ask travis to install a newer (> 3.22) version of Gtk/Gdk I think?

Yeah, or the issue I linked needs to be fixed but that might be a bit more complicated.

**Comment by andrewdavidmackenzie** [comment]
I installed newer versions of the dependencies in the `before-install` stage of Travis for Linux build and that seems to have fixed it. Now I need to fix the issue on Mac....

thanks - I'll close this.

**Comment by andrewdavidmackenzie** [comment]
I'm still fighting this..... I have linux building, but Mac OS X still failing.

I have seen the .travis.xml file used here https://github.com/gtk-rs/gtk/blob/master/.travis.yml, which has quite a few things I don't understand why (but which I copy verbatim anyway)

and I'm trying to use the same settings to compile project which has gtk+3 as a dependency.

You can see fail logs in this travis job:
https://travis-ci.org/andrewdavidmackenzie/flow/jobs/641479660

**Comment by EPashkin** [comment]
Issue looks as duplicate of https://github.com/gtk-rs/gio/issues/272 for me

**Comment by EPashkin** [comment]
Hm, I missed that other functions missed too.
We missed it as we are testing only gtk3.14 for macos.
```
            "_gtk_plug_get_type", referenced from:

                _$LT$gtk..auto..plug..Plug$u20$as$u20$glib..types..StaticType$GT$::static_type::ha8520f43164a4b5d in libgtk-7b4c6bca9cb201dc.rlib(gtk-7b4c6bca9cb201dc.gtk.88t2fx7h-cgu.1.rcgu.o)

            "_gtk_plug_new", referenced from:

                gtk::auto::plug::Plug::new::h984db613d516edae in libgtk-7b4c6bca9cb201dc.rlib(gtk-7b4c6bca9cb201dc.gtk.88t2fx7h-cgu.1.rcgu.o)

            "_gtk_plug_new_for_display", referenced from:

                gtk::auto::plug::Plug::new_for_display::h6f228835b934f9fb in libgtk-7b4c6bca9cb201dc.rlib(gtk-7b4c6bca9cb201dc.gtk.88t2fx7h-cgu.1.rcgu.o)

            "_gtk_socket_get_type", referenced from:

                _$LT$gtk..auto..socket..Socket$u20$as$u20$glib..types..StaticType$GT$::static_type::h6247adbb899b808c in libgtk-7b4c6bca9cb201dc.rlib(gtk-7b4c6bca9cb201dc.gtk.88t2fx7h-cgu.4.rcgu.o)

            "_gtk_socket_new", referenced from:

                gtk::auto::socket::Socket::new::hb49aa27279cfa80a in libgtk-7b4c6bca9cb201dc.rlib(gtk-7b4c6bca9cb201dc.gtk.88t2fx7h-cgu.4.rcgu.o)
```

**Comment by EPashkin** [comment]
I also missed that failed job was for gtk 3.14, and gtk 3.22 passed.
@andrewdavidmackenzie  Maybe you just not needed 3.14 test as you clear state `features = ["v3_22"] ` for gtk?


Anyway it strange, seems macos versions of GDesktopAppInfo, GtkPlug, GtkSocket was added after gtk3.14

**Comment by andrewdavidmackenzie** [comment]
Ive tried with 3_14 and 3_22 - both fail

**Comment by EPashkin** [comment]
Sorry, I missed that passed is linux build :cry:

**Comment by andrewdavidmackenzie** [comment]
Maybe I just need to re-frame the question.

Can anyone point me at a rust project using gtk-rs, for Mac and Linux that has CI/CD build working in Travis?

I do not use any special features of any specific version of gtk-rs so don't really care which version it is.

**Comment by EPashkin** [comment]
At minimum this project has working travis with osx:
https://github.com/GuillaumeGomez/process-viewer/pull/131

You also can check other project from section "Projects using gtk-rs" in https://gtk-rs.org/

**Comment by andrewdavidmackenzie** [comment]
Thanks for the suggestion. 

I basically copied everything from that project (which doesn't specify features, or use ENV vars etc - is nice and simple) resulting in:

Cargo.toml:
```
[dependencies]
cairo-rs = "0.8"
gdk = "0.12"
gdk-pixbuf = "0.8"
gio = "0.8"
glib = "0.9"
gtk = "0.8"
pango = "0.8"
```

.travisyml:
```
matrix:
  include:
  - os: linux
    rust: stable
  - os: osx
    rust: stable

before_install:
  - make common-config
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python@2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libffi gtk+3 cairo atk; fi
```


But the build fails with same problem: https://travis-ci.org/andrewdavidmackenzie/flow/jobs/641847180
```
  = note: Undefined symbols for architecture x86_64:
            "_g_desktop_app_info_get_implementations", referenced from:
                gio::auto::desktop_app_info::DesktopAppInfo::get_implementations::h0e2516fc084a6c16 in libgio-6ee409984115552c.rlib(gio-6ee409984115552c.gio.4jbrs609-cgu.2.rcgu.o)
            "_g_desktop_app_info_get_type", referenced from:
                _$LT$gio..auto..desktop_app_info..DesktopAppInfo$u20$as$u20$glib..types..StaticType$GT$::static_type::h533621b4b6013a3c in libgio-6ee409984115552c.rlib(gio-6ee409984115552c.gio.4jbrs609-cgu.2.rcgu.o)
            "_g_desktop_app_info_new", referenced from:
                gio::auto::desktop_app_info::DesktopAppInfo::new::h8f0e7e84cc921fd6 in libgio-6ee409984115552c.rlib(gio-6ee409984115552c.gio.4jbrs609-cgu.2.rcgu.o)
            "_g_desktop_app_info_new_from_keyfile", referenced from:
                gio::auto::desktop_app_info::DesktopAppInfo::new_from_keyfile::he198e2c35fe2e3b6 in libgio-6ee409984115552c.rlib(gio-6ee409984115552c.gio.4jbrs609-cgu.2.rcgu.o)
            "_g_desktop_app_info_search", referenced from:
                gio::desktop_app_info::_$LT$impl$u20$gio..auto..desktop_app_info..DesktopAppInfo$GT$::search::h6185291c06de5dc1 in libgio-6ee409984115552c.rlib(gio-6ee409984115552c.gio.4jbrs609-cgu.2.rcgu.o)
            "_gtk_plug_get_type", referenced from:
                _$LT$gtk..auto..plug..Plug$u20$as$u20$glib..types..StaticType$GT$::static_type::h2bb4a65f1663e763 in libgtk-fd7a72fae35cc547.rlib(gtk-fd7a72fae35cc547.gtk.49rizfrv-cgu.7.rcgu.o)
            "_gtk_plug_new", referenced from:
                gtk::auto::plug::Plug::new::h9e7c1177c4f116ff in libgtk-fd7a72fae35cc547.rlib(gtk-fd7a72fae35cc547.gtk.49rizfrv-cgu.7.rcgu.o)
            "_gtk_plug_new_for_display", referenced from:
                gtk::auto::plug::Plug::new_for_display::ha9116adff8817c1a in libgtk-fd7a72fae35cc547.rlib(gtk-fd7a72fae35cc547.gtk.49rizfrv-cgu.7.rcgu.o)
            "_gtk_socket_get_type", referenced from:
                _$LT$gtk..auto..socket..Socket$u20$as$u20$glib..types..StaticType$GT$::static_type::hbe15472a8d8855fa in libgtk-fd7a72fae35cc547.rlib(gtk-fd7a72fae35cc547.gtk.49rizfrv-cgu.4.rcgu.o)
            "_gtk_socket_new", referenced from:
                gtk::auto::socket::Socket::new::h9d14a21696915e0d in libgtk-fd7a72fae35cc547.rlib(gtk-fd7a72fae35cc547.gtk.49rizfrv-cgu.4.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

On the positive side, I have a simpler build with less knobs being tweaked, and less combinations to play with and test.

**Comment by andrewdavidmackenzie** [comment]
OK, I have forked the process-viewer project.

It builds fine for me on my local Mac, but also fails on macosx on travis!
https://travis-ci.org/andrewdavidmackenzie/process-viewer/jobs/641869904

Which makes me pretty sure that build can't be passing.

In my build I had to unlink python2 because of that same problem, so I will make that change in process-viewer and try again (and if it works, send him a PR)

**Comment by sdroege** [comment]
> In my build I had to unlink python2 because of that same problem, so I will make that change in process-viewer and send him a PR.

That's also something we had to do in all the gtk-rs macOS jobs on Travis already, so that's expected :)

CC @GuillaumeGomez

**Comment by andrewdavidmackenzie** [comment]
PR sent last night https://github.com/GuillaumeGomez/process-viewer/pull/133
