### ISSUE TITLE
InfoBar get_content_area() should be a Gtk::Box

### ISSUE THREAD

**Issue by emmanueltouzery** [gtk-rs/gtk#947]
Currently `InfoBarEx::get_content_area()` returns an `Option<Widget>`, but I believe it should return a `Box`. If we look at the gtk apidoc:

>  To add widgets to the main content area of a InfoBar, use InfoBarExt::get_content_area and add your widgets to the container.

and:

```c
content_area = gtk_info_bar_get_content_area (bar);
gtk_container_add (GTK_CONTAINER (content_area),
                   message_label);
```

also, in the gtk source:
https://github.com/GNOME/gtk/blob/master/gtk/gtkinfobar.c#L490

```c
priv->content_area = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
```

So I think gtk-rs should update the type in the bindings from `Option<gtk::Widget>` to probably `gtk::Box`.

Assuming I'm correct, I have another question.. Is there a way for me to upcast the `gtk::Widget` that I get from gtk-rs to a `Box`, even through a hack, as a temporary measure until gtk-rs releases a new version with the change?

**Comment by EPashkin** [comment]
About upcasting: you can use https://gtk-rs.org/docs/glib/object/trait.Cast.html#method.downcast

**Comment by EPashkin** [comment]
Changing type is reasonable for me,
cc @sdroege, @GuillaumeGomez 

Code change can be done with adding to https://github.com/gtk-rs/gtk/blob/master/Gir.toml#L1213-L1218
```toml
    [[object.function]]
    name = "get_content_area"
        [object.function.return]
        nullable = false
        type = "Gtk.Box"
```
and run `make gir`

**Comment by emmanueltouzery** [comment]
@EPashkin thank you very much, `dynamic_cast::<gtk::Box>()` is what I was looking for and I can confirm the feature works, I can now add a label to the info bar, which I couldn't before :+1:

**Comment by sdroege** [comment]
@EPashkin Yes that should be changed, and also for the action area of the infobar.

See also https://gitlab.gnome.org/GNOME/gtk/merge_requests/1372

**Comment by EPashkin** [comment]
@emmanueltouzery Also your problem seems can solved in simpler way: https://gtk-rs.org/docs/gtk/trait.ContainerExt.html#tymethod.add, 
so just try `infobar.add(label)`

**Comment by emmanueltouzery** [comment]
@EPashkin infobar.add does compile, but does the wrong thing: the child is added outside of the main content area of the info bar.

**Comment by sdroege** [comment]
Yes, that's adding it to the action area, not to the content area.

**Comment by sdroege** [comment]
@EPashkin @emmanueltouzery One of you wants to send the PR for fixing the type in the bindings? Otherwise I can do that too
