### ISSUE TITLE
How to get the size of currently used font?

### ISSUE THREAD

**Issue by ArekPiekarz** [gtk-rs/gtk#949]
I've been trying to find a way to get the size of the currently used font in gtk::TextView. My use case is to dynamically increase or decrease the font size in reaction to a key press event.

It looks like pango::FontDescription::get_size() contains that information. It could be taken from gtk_sys::GtkStyle, but there is no function that returns it in Rust version of gtk. I found that an almost working workaround would be to use gtk::Widget::get_property("style"), but it returns a wrapped glib::Value and conversion from it is not implemented for GtkStyle.

It seems this issue - https://github.com/gtk-rs/gtk/issues/874 - may be a blocker for my case. Do you see any other way to solve it?

**Comment by EPashkin** [comment]
`GtkStyle` not included in current gtk crate at all.
Theoretically you can use https://gtk-rs.org/docs/gtk/trait.WidgetExt.html#tymethod.get_style_context to get current style context, but it don't have https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#gtk-style-context-get-font as it deprecated and https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#gtk-style-context-get as it use varargs,
so seems only solution is to call `gtk_style_context_get` manually to get font.

**Comment by ArekPiekarz** [comment]
Thanks, I was able to get the font size with a following workaround:
```rust
let styleContext = widget.get_style_context();
let fontDescriptionPtr = unsafe {gtk_sys::gtk_style_context_get_font(
    styleContext.as_ptr(), gtk_sys::GTK_STATE_FLAG_NORMAL)};
let fontPangoSize = unsafe {pango_sys::pango_font_description_get_size(
    fontDescriptionPtr)}; // gives 9216 Pango units
let fontPointSize = fontPangoSize / pango_sys::PANGO_SCALE; // gives 9 points
```

**Comment by EPashkin** [comment]
@ArekPiekarz It will be good if you can get working code with `gtk-style-context-get` instead of `gtk_style_context_get_font`, wrap it to `FontDescription` with `from_glib_none` and make PR with new manual function in StyleContext.

**Comment by ArekPiekarz** [comment]
After your comment I noticed `gtk_style_context_get_font` was deprecated, so here's the newer version using the variadic `gtk_style_context_get`:
```rust
let fontDesciptionPtr: *mut pango_sys::PangoFontDescription = std::ptr::null_mut();
let fontProperty = std::ffi::CString::new("font").unwrap();
unsafe {gtk_sys::gtk_style_context_get(
    styleContext.as_ptr(),
    gtk_sys::GTK_STATE_FLAG_NORMAL,
    fontProperty.as_ptr(),
    &fontDesciptionPtr,
    std::ptr::null::<std::ffi::c_void>())};
let fontDesciption : pango::FontDescription =
    unsafe {glib::translate::from_glib_none(fontDesciptionPtr)};
let fontSize = fontDesciption.get_size() / pango_sys::PANGO_SCALE;
```
For now I'm not making any promise to submit a PR with it.

**Comment by EPashkin** [comment]
@ArekPiekarz Thanks for snippet, I will add it on the weekend.
Can you check that snippet works with `b"font\0".as_ptr() as *const _` instead of `fontProperty.as_ptr()`?

**Comment by ArekPiekarz** [comment]
It does work, but even shorter version does too: `b"font\0"`

**Comment by EPashkin** [comment]
Thanks again.
Bad that in signal case short version not works, maybe it really "unsafe"

**Comment by ArekPiekarz** [comment]
What do you mean "in signal case"?

Also are you sure we should use `from_glib_none` and not `from_glib_full`? The documentation of `gtk_style_context_get` says this:
```
 * As with g_object_get(), a copy is made of the property contents for
 * pointer-valued properties, and the caller is responsible for freeing the
 * memory in the appropriate manner for the type. For example, by calling
 * g_free() or g_object_unref(). Non-pointer-valued properties, such as
 * integers, are returned by value and do not need to be freed.
```
See https://github.com/GNOME/gtk/commit/632fab0ca702b600fde492319ab0aa2d9d3bbd08#diff-a6b77f852eb73480d3960cdfaf3c28aaL735  (yes, I'm linking to a commit that removed that function, I guess for Gtk 4; yay for another deprecation).

**Comment by EPashkin** [comment]
"signal case": https://github.com/gtk-rs/gtk/blob/master/src/auto/about_dialog.rs#L1216

You right, it need be `from_glib_full` in this case.

**Comment by ArekPiekarz** [comment]
Are you sure it doesn't work in that signal case? Because that file is autogenerated, maybe that type annotation is added by a script to make sure it always compiles, even if it's not necessary.

**Comment by EPashkin** [comment]
In case of signals it need at minimum `.as_ptr()` or else I get this error even after changing parameter type to "*const u8":
```
error[E0308]: mismatched types
    --> D:/eap/rust/0/gtk\src\auto\about_dialog.rs:1194:17
     |
1194 |                 b"activate-link\0",
     |                 ^^^^^^^^^^^^^^^^^^ expected `u8`, found array `[u8; 14]`
     |
     = note: expected raw pointer `*const u8`
                  found reference `&'static [u8; 14]`
```

**Comment by ArekPiekarz** [comment]
I guess my version works with the short form because of the variadic list, which basically means there is no type checking. I know, because I've been battling with it before creating this issue and I didn't know why I kept getting garbage data out of it when passing a pointer to `pango_sys::PangoFontDescription`. It turned out I had to pass... a pointer to a pointer.

I have good news: it is possible to get font information without using `unsafe` or lower-level libs using a following code:
```rust
let fontDesciption = widget.get_pango_context()?.get_font_description()?;
let fontSize = fontDescription.get_size() / pango::SCALE;
```
Shoutout to Rust's Discord #gui-and-ui channel for providing this knowledge.

**Comment by sdroege** [comment]
The difference between passing `b"blabla\0"` and `b"blabla\0".as_ptr()` is that the former passes two pointer sized values (the pointer to the string itself and its length) while the latter only passes one pointer. As such better to use `as_ptr()`, that provides the values that C expects then.

**Comment by ArekPiekarz** [comment]
Thanks for all the work!
