### ISSUE TITLE
Build fails on clean checkout

### ISSUE THREAD

**Issue by cjgreenaway** [gtk-rs/gtk#95]
```
git clone https://github.com/rust-gnome/gtk
cd gtk
cargo build
```

gives

```
src/rt.rs:19:16: 19:35 error: unresolved name `ffi::gtk_init_check`
src/rt.rs:19 	match to_bool(ffi::gtk_init_check(ptr::null(), ptr::null())) {
             	              ^~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `gtk`.
```

I think this is because an updated version of gtk-sys needs pushing to crates.io (a version that has the gtk_init_check function declaration).

If I set ```paths``` in ```.cargo/config``` to point to another fresh checkout of gtk, then run ```cargo build``` the compilation error goes away, supporting the theory.

**Comment by GuillaumeGomez** [comment]
I am currently *trying* to have the master branch using only git repo instead of crates' ones. For the moment, I have an issue. However, if you use the "crates" branch, you shouldn't have any problem.

**Comment by gkoz** [comment]
@GuillaumeGomez what seems to be the problem? We used to have everything pulled from git, shouldn't the master branch simply use the old `Cargo.toml` versions?

**Comment by GuillaumeGomez** [comment]
The problem is when we have a multiple "unofficial" dependecies on ``glib-sys`` in ``gdk`` repo for example. Cargo doesn't want a double link and I'm trying to figure out how to get through that error since two days.

**Comment by gkoz** [comment]
Are you saying two crates using the `glib-sys` crate from git will get "different" incompatible instances of it?

**Comment by GuillaumeGomez** [comment]
I have the following error:

```Shell
> cargo build
native library `glib` is being linked to by more than one package, and can only be linked to by one package

  glib-sys v0.1.1
  glib-sys v0.1.1 (https://github.com/rust-gnome/glib#40f0161c)
```

**Comment by gkoz** [comment]
Does the first one come from crates.io (it doesn't have an url to the right of it)?

**Comment by GuillaumeGomez** [comment]
Hum... I'll just merge my PRs and see what happens next (for the current working ones).

**Comment by GuillaumeGomez** [comment]
It seems that it's still the same error. Really weird...

**Comment by gkoz** [comment]
I'm still not sure why you don't just try reverting the dependencies to before publishing to crates, e.g.
```
[dependencies.gtk-sys]
path = "gtk-sys"
version = "0.1.0"

[dependencies.cairo-sys]
git = "https://github.com/rust-gnome/cairo"

[dependencies.cairo]
git = "https://github.com/rust-gnome/cairo"
default-features = false

[dependencies.glib]
git = "https://github.com/rust-gnome/glib"

[dependencies.glib-sys]
git = "https://github.com/rust-gnome/glib"

[dependencies.gdk-sys]
git = "https://github.com/rust-gnome/gdk"

[dependencies.gdk]
git = "https://github.com/rust-gnome/gdk"
default-features = false

[dependencies.pango-sys]
git = "https://github.com/rust-gnome/pango"

[dependencies.pango]
git = "https://github.com/rust-gnome/pango"
```

**Comment by GuillaumeGomez** [comment]
I didn't test on gtk yet, I'm still on gdk. I wanted to make the sub dependencies work before starting upper ones.

**Comment by gkoz** [comment]
I believe it will keep producing that error until you get rid of every crates.io dependency in the build.

**Comment by GuillaumeGomez** [comment]
I did for all gdk dependencies, that's where I'm getting confused.

**Comment by gkoz** [comment]
At least cairo still takes glib from crates: https://github.com/rust-gnome/cairo/blob/master/Cargo.toml#L30

**Comment by GuillaumeGomez** [comment]
... You solved the problem... Well, congrats I guess ? Haha !
