### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [gtk-rs/gtk#954]
It's been a long while since I looked at gtk-rs and I just saw, that there is GTK TextView now, a widget, which is critical for one application I had in mind a while ago, but which did simply not exist in the bindings back then. So I went about trying to install gtk-rs.

On crates.io I can find the following information:

I am supposed to copy this into my Cargo.toml:

> gtk = "0.8.1"

Then there is a link to the "online documentation": http://gtk-rs.org/docs/

There is tells me to add:

    [dependencies.gtk]
    version = "0.1.0"
    features = ["v3_16"]

As well for enabling later GTK features (?). So I did that as well, but then my Cargo.toml does not parse anymore. I have to remove the gtk = "0.8.1" part under [dependencies] to make it run.

On https://gtk-rs.org/ we have the next variation:

    [dependencies.gtk]
    version = "0.8.0"
    features = ["v3_16"]

    [dependencies.gio]
    version = ""
    features = ["v2_44"]

That one does not work because:

    $ cargo run
    error: multiple packages link to native library `gio`, but a native library can be linked only once

    package `gio-sys v0.3.4`
        ... which is depended on by `gio v0.1.3`
        ... which is depended on by `tutorial v0.1.0 (/home/xiaolong/development/Rust/GTK/tutorial)`
    links to native library `gio`

    package `gio-sys v0.9.1`
        ... which is depended on by `gdk v0.12.1`
        ... which is depended on by `gtk v0.8.1`
        ... which is depended on by `tutorial v0.1.0 (/home/xiaolong/development/Rust/GTK/tutorial)`
    also links to native library `gio`

So now I am unsure, what the correct setting for my Cargo.toml is and which documentation is actually up-to-date and correct.

For now I will try with:

    [dependencies.gtk]
    version = "^0.8.1"
    features = ["v3_16"]

But I don't know, whether I really also need the gio block in the configuration.

What is the correct content of the Cargo.toml file?

**Comment by sdroege** [comment]
The correct versions are always the latest ones you can find on crates.io :)

@guillaumegomez can you fix the docs?

**Comment by GuillaumeGomez** [comment]
I'll modify them in order to not have to update them.

**Comment by ZelphirKaltstahl** [comment]
Thanks for your quick reply!

I have a question regarding finding the version on crates.io: How does one see all the "feature" versions and what they entail? Is there an official list somewhere? I could not find it on crates.io.

**Comment by sdroege** [comment]
They enable GTK (etc) API that is only available in newer versions of GTK. @GuillaumeGomez would it be possible to mark API in the docs accordingly, that they require a feature to be enabled?

**Comment by GuillaumeGomez** [comment]
I thought it was already the case? If not, it needs to be added into gir.

**Comment by sdroege** [comment]
Indeed: https://gtk-rs.org/docs/gio/trait.ResolverExt.html#tymethod.lookup_by_name_with_flags

**Comment by ZelphirKaltstahl** [comment]
Hm, now just imagine: You are starting a new project. Which feature version you can use is nowhere listed. You have no idea what versions even exist. You also do not know yet, what kind of components will be added to your application during the development, because you are starting out with a vague idea of something, that you have done in another programming language in another GUI library.

How will you know, what version you should write for the features in your Cargo.toml?

Can you explain the process of making that choice? It seems to me, that one simply chooses a feature version and hopes for everything one needs to be there. If it is not, you try to up that version. But to what string value? You cannot find it on crates.io, afaik.  Would you need to go through all the docs and already know what functions you're going to call and then read the feature versions of them all and find the maximum?

I don't do Rust projects every day, so I am sorry, if I overlooked something in broad daylight here. Even the concept of feature version is a bit new to me. I only know, that it already existed when gtk-rs was version 0.2.0, which is, when I started my project the first time. I am just trying to make an educated choice for the dependencies of my project. I know I will need TextView and a table with multiple columns and buttons and dialogs and more. A pretty complex GTK+3 app.

**Comment by sdroege** [comment]
> How will you know, what version you should write for the features in your Cargo.toml?

None, until you notice that some API you want to use is only available with newer versions of the library. Then you would add those features to `Cargo.toml`.

> But to what string value?

See https://gtk-rs.org/docs/gio/trait.ResolverExt.html#tymethod.lookup_by_name_with_flags for example. It lists the minimum feature version that is required for having access to that function.

**Comment by ZelphirKaltstahl** [comment]
Ah now I think I get it! Basically you leave it open, until you are really sure about that version and it will pick a default version (?) until that moment, when you set it?

**Comment by sdroege** [comment]
By default the minimum supported version by the bindings is used (GTK 3.14 currently). So you have access to all the APIs from GTK 3.14 without having to do anything special.

If you want to use APIs from newer GTK versions you'd notice that a) they have that listed in the documentation as linked above, b) if you don't configure anything the compiler will tell you that it can't find this API.

**Comment by sdroege** [comment]
I think there's some opportunity here to improve the documentation to make it more clear, but I'm not sure how that would look like exactly. Maybe @GuillaumeGomez ? :)

**Comment by GuillaumeGomez** [comment]
No clue either. It's the first time we came across this specific issue so it'd be difficult to generalize it in order to make a tutorial for it... In the meantime, I'll update the docs as I said. It could be part of the discussions in next hackfest as well...

**Comment by GuillaumeGomez** [comment]
How did you arrive on http://gtk-rs.org/docs/ btw? I can't find any link to it. It seems like an old version of https://gtk-rs.org/docs-rs/ ...

**Comment by ZelphirKaltstahl** [comment]
@GuillaumeGomez I am not sure how I got there. I think it might have been a search engine result. I had many tab related to gtk-rs open and anywhere on those must have been a link.

**Comment by coniurare** [comment]
> How did you arrive on http://gtk-rs.org/docs/ btw? I can't find any link to it. It seems like an old version of https://gtk-rs.org/docs-rs/ ...

http://gtk-rs.org/docs/gtk/ links to it:

> See also: Gtk-rs documentation overview

found in: https://github.com/gtk-rs/gtk/blob/master/src/lib.rs#L18
