### ISSUE TITLE
gtk::main_quit() panics

### ISSUE THREAD

**Issue by Dmitry-Borodin** [gtk-rs/gtk#964]
I want to close application by custom button click. 
Calling on click gtk::main_quit(); panics with error `thread 'main' panicked at 'Attempted to quit a GTK main loop when none is running.'`

Because gtk_sys::gtk_main_level() seems to be always 0, even when I see an app window.

[Sample](https://gist.github.com/Dmitry-Borodin/154a75473c2fcf6479c4578b2685b367) - slightly modified builder_basics gtk-rs sample, with just different action on click.

[Stacktrace](https://gist.github.com/Dmitry-Borodin/3372980b6fc6baad6c41df6d0b9300b1)

I'm running it under GNU/Linux

[Related Druid issue](https://github.com/xi-editor/druid/issues/505)

**Comment by Dmitry-Borodin** [comment]
Is there any documentation to check what and when gtk_sys::gtk_main_level() should return?

**Comment by sdroege** [comment]
That's because `gtk::Application` (and `gio::Application` where the actual implementation is) only run a main loop manually instead of calling `gtk_main()`. As such you can't use `gtk_main_quit()`.

What you're looking for is `gio::Application::quit()`.

**Comment by Dmitry-Borodin** [comment]
Thank you for a reply, application.quit() works fine

While in druid we initializing loop with gtk::init(), ([here](https://github.com/xi-editor/druid/blob/master/druid-shell/src/platform/gtk/application.rs)) and then creating gio::Application., 
then the question whether we need gtk::init() before creating application? 
It's just confusing, that gtk::init() followed by gtk::main_quit() panics.

**Comment by EPashkin** [comment]
@Dmitry-Borodin by source you create gtk::Application, not gio's, and it calls `gtk_init` itself: https://developer.gnome.org/gtk3/stable/GtkApplication.html#gtk-application-new.
Maybe this is source of your problem.

**Comment by Dmitry-Borodin** [comment]
Thank you, looks like we don't need to gtk::init() at all.
