### ISSUE TITLE
Set cursor position in Entry

### ISSUE THREAD

**Issue by MGlolenstine** [gtk-rs/gtk#965]
I found a way to get the cursor and I'm inserting the text at the cursor, but the problem is that the cursor doesn't move to the end of the inserted text.

How can I manually set the cursor position?

**Comment by sdroege** [comment]
This is not a bug but a support request, and also generally about GTK not specific for the bindings :) Please ask this on the GTK mailing list.

**Comment by MGlolenstine** [comment]
Oh, weird... I thought that it would be a feature, that the cursor would move with the inserted text, or that they would add the `set_cursor_pos` or something similar.
I'll ask on their mailing list!

Thanks!
