### ISSUE TITLE
How to connect to `events` that don't have the connect function

### ISSUE THREAD

**Issue by MGlolenstine** [gtk-rs/gtk#969]
I've followed #966 , but I'm having some problems.
In particular, there's seems to be no `connect_clicked` function for `EventBox`. This is a problem, as everywhere online people suggest to implement `clicked` on a label, is by using an `EventBox`.
I'm wondering if there's another way to achieve the same without having those functions.

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk/issues/966#issuecomment-597565387

**Comment by MGlolenstine** [comment]
Thanks!
