### ISSUE TITLE
Some structs are missing GObjectTrait implementations

### ISSUE THREAD

**Issue by gsingh93** [gtk-rs/gtk#97]
Currently, a struct only implements `GObjectTrait` if it is a `Widget`. In this case, `struct_Widget!` is called which ends up generating the impls. However, there many other objects that implement GObject that aren't widgets. In my case, I need to get a `ListStore` from a `Builder`, but I can't do that unless `ListStore` implements `GObjectTrait`.

I have a fork with this fix for `ListStore` ready to go, but I didn't want to submit a pull request just yet unless there's some more general issue to fix.

**Comment by gkoz** [comment]
This won't be an issue once the object reform is done. See #59

**Comment by GuillaumeGomez** [comment]
I'll close this issue once the object reform is done.

**Comment by gkoz** [comment]
Fixed in #221
