### ISSUE TITLE
gtk::Application  created by gtk::ApplicationBuilder doesn't initialize GTK

### ISSUE THREAD

**Issue by andy128k** [gtk-rs/gtk#984]
Here is a repository which reproduction of an error. 
https://github.com/andy128k/reproduce_error_gtk_rs_application_builder

**Comment by sdroege** [comment]
@antoyo This happens because the builder goes just via `glib::Object::new()` and does not mark things as initialized, like the `gtk::Application::new()` constructor does here: https://github.com/gtk-rs/gtk/blob/7f1b64496a290e1f93e5d459862755b7c6fd25be/src/application.rs#L14

**Comment by andy128k** [comment]
`glib::Object::new()` should not be an issue. Error is [thrown by Gtk-rs](https://github.com/gtk-rs/gtk/blob/7f1b64496a290e1f93e5d459862755b7c6fd25be/src/rt.rs#L32), not by Gtk. 

IMHO, Gtk-rs should not track initialization itself [here](https://github.com/gtk-rs/gtk/blob/7f1b64496a290e1f93e5d459862755b7c6fd25be/src/rt.rs#L23) but rely on Gtk using [this or similar API](https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gtk/gtkmain.h#L82).

**Comment by sdroege** [comment]
> `glib::Object::new()` should not be an issue. Error is [thrown by Gtk-rs](https://github.com/gtk-rs/gtk/blob/7f1b64496a290e1f93e5d459862755b7c6fd25be/src/rt.rs#L32), not by Gtk.

Yes, because of that line missing :)



> IMHO, Gtk-rs should not track initialization itself [here](https://github.com/gtk-rs/gtk/blob/7f1b64496a290e1f93e5d459862755b7c6fd25be/src/rt.rs#L23) but rely on Gtk using [this or similar API](https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gtk/gtkmain.h#L82).

That API only exists in GTK 4 unfortunately, otherwise I would agree with you.

**Comment by gdesmott** [comment]
What would be the proper way to fix this? Not sure how to override only `new()` while keeping the rest of the `builders` generation.

**Comment by sdroege** [comment]
I don't know, this case was not considered when adding the builders. It assumes that `g_object_new()` is sufficient (which is also not the case for a few other types btw).

**Comment by andy128k** [comment]
One of the options is to remove gtk::ApplicationBuilder.

Theoretically checking if Gtk is initialized in `new` or `build` is not correct. Application initializes Gtk in a `startup` handler, not in a constructor.

**Comment by kinnison** [comment]
Is the reason for calling this from `Application::new()` merely to simplify the examples to not include a call to `rt::init()` ?  If so then my vote would be to stop `Application::new()` from calling this and instead expect callers to initialise for themselves.  If that's too big of a leap, or if really there's a variety of builders which would benefit from it, then I propose adding to the `gir` tool a facility to add a pre-construction statement in `Gir.toml` which will be inserted before the `glib::Object::new()` invocation in the `build()` method.

**Comment by sdroege** [comment]
`rt::init()` is unsafe code and ideally we wouldn't require every GTK application to have unsafe code just for this :)

**Comment by kinnison** [comment]
In what way is it unsafe, `rt::init()` is *NOT* marked `unsafe` which means safety guarantees are meant to hold for anyone to call it.

**Comment by kinnison** [comment]
For clarity, while there is an `unsafe {}` block in `Application::new()` the call to `try!(rt::init())` is ouside the `unsafe {}` block.

**Comment by sdroege** [comment]
Ah even worse. We shouldn't initialize GTK separately but let `gtk::Application` do it and then call `rt::set_initialized()` (that's the unsafe one).

**Comment by kinnison** [comment]
Okay, so really what we should do is ensure that `gtk::Application` in gtk-rs has a startup handler which calls `rt::set_initialized()` and then it shouldn't call `rt::init()` itself in `Application::new()` meaning we can likely drop that special case from the `Gir.toml` ?

**Comment by kinnison** [comment]
My understanding of how the `gtk::Application` stuff comes into being was flawed, we still need the special case because it mustn't assert initialised.

We have three cases to consider, all of which need to ensure `rt::set_initialized()` is called at the start of the callback chain for the `startup` signal on the application:

1. `Application::new()` generated applications
2. `ApplicationBuilder::build()` generated applications
3. Instances of subclasses of `gtk::Application`

In theory we could do this by hiding the official `gtk::Application` class and subclassing it ourselves in gtk-rs, ensuring we register a callback, and then having what anyone else sees as `gtk::Application` actually be the subclass we have from gtk-rs.  Perhaps there's something cleaner?  I'm not fully au-fait with gtk/glib objects.  If we could hook the creation of any instance of or subclass of `gtk::Application` we could register the signal handler at that point instead.

**Comment by kinnison** [comment]
So the first of those could be done like this: https://github.com/kinnison/gtk/commit/804b9195d0a5945a38fb4bf035e9862ab4280a55  and the third like this: https://github.com/kinnison/gtk/commit/6e2a2e3ce2f7a9fc48ab2e586d6886ede0ba892b but I've not yet worked out how to do the second without poking at the gir crate to add some kind of "post build filter"

**Comment by sdroege** [comment]
>  I've not yet worked out how to do the second without poking at the gir crate to add some kind of "post build filter"

I don't think there's another way. The other two commits look good to me

**Comment by kinnison** [comment]
Okay, proposed approach, given the above linked gir change is:

1. For `Application::new()` instances - https://github.com/kinnison/gtk/commit/d8a50c62f2a1fd8d1192e6eb9aa81aaa8d54bfcb
2. For `ApplicationBuilder::build()` instances - https://github.com/kinnison/gtk/commit/0392dc8b5d8c74ed99960f5d324593552adcbf62
3. For subclasses of `gtk::Application` - https://github.com/kinnison/gtk/commit/aaed97a1fc623742399cacff0d36f44e638d1543

If @sdroege and @GuillaumeGomez think that looks sane, then I'll sort a PR as soon as the gir change is settled.

**Comment by kinnison** [comment]
For reference the 'gir change' mentioned above is https://github.com/gtk-rs/gir/pull/912

**Comment by sdroege** [comment]
Looks good to me
