### ISSUE TITLE
gtk::Entry::get_text should not return an Option

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk#997]
Possible workaround is to call `.get_buffer().get_text()` to get no `Option`.

I think the same applies for

- Label::get_text()
- Label::get_label()

**Comment by sdroege** [comment]
Indeed, do you want to submit a PR for this? It requires marking the return type as `nullable = false` in the `Gir.toml`.

**Comment by GuillaumeGomez** [comment]
And to run `make gir` afterwards to update the code automatically.
